### ISSUE TITLE
Can't run namespaced controller specs in isolation 

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#1008]
When I run the controller specs:
  `rspec ./spec/controllers/` => all green  ✅ 

When I try to run the specs in one namespace only:
    ` rspec ./spec/controllers/supervisors` 
it errors with:
    `1 error occurred outside of examples`
```
    NameError:
    uninitialized constant Supervisors
    # ./spec/controllers/supervisors/comments_controller_spec.rb:3:in `<top (required)>'
``` 
Note: tested on master 
It seems like I am adding more issues than I am solving 😝 

I can't te if this related to recent changes

**Comment by ramonh** [comment]
Is it possible you need to require `rails_helper`?

**Comment by pgaspar** [comment]
I think this is because we're requiring `spec_helper` instead of `rails_helper` (?)

**Comment by F3PiX** [comment]
YES! I totally missed that 🙈
