### ISSUE TITLE
`rake db:reset` spams developer with confirmation emails :)

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#1019]
letter_opener opens a gazillion tabs in $DEFAULT_WEBBROWSER :smile: 

It's more funny than a nuisance, but maybe anymore feels like fixing it (disclaimer: I don't :wink: ) This issue will self-destruct in a week or two.

**Comment by ramonh** [comment]
Should now be fixed! @carpodaster Could you please confirm?

**Comment by carpodaster** [comment]
Confirmed! Thanks, @ramonh !
