### ISSUE TITLE
Switch to SSL

### ISSUE THREAD

**Issue by bastilian** [rails-girls-summer-of-code/rgsoc-teams#107]
Should we get a cert on https://www.globalsign.com/ssl/ssl-open-source/

/cc @svenfuchs

**Comment by carpodaster** [comment]
@svenfuchs @bastilian has there been any progress on aquiring / installing the SSL certificate?

**Comment by carpodaster** [comment]
@svenfuchs has GlobalSign gotten back to you already? If not: shall we just go for the wildcard cert?

**Comment by svenfuchs** [comment]
@carpodaster actually, yes, they did. except that it ended up in my local spam folder. i have forwarded it to you.

**Comment by carpodaster** [comment]
@svenfuchs We're almost there, certificate has been issued! :tada: I just need you as the app owner to add the ssl endpoint on Heroku: `heroku addons:add ssl:endpoint -r production`

**Comment by carpodaster** [comment]
:lock: :tada: :balloon: 

![SSL at laaaast!](http://1.bp.blogspot.com/-xDy_zx18R5g/UPwwTsdyRVI/AAAAAAAAGa4/elrNYEiZPLg/s1600/its-working-its-working.gif)

**Comment by anikalindtner** [comment]
AWESOME ![](http://www.reactiongifs.com/wp-content/uploads/2012/01/haters1.gif)

**Comment by alicetragedy** [comment]
I believe it's time for the dancing cat to do the closed issue dance:

![dancingcat](https://cloud.githubusercontent.com/assets/3143348/6396818/ffdb5fa4-bde0-11e4-9e8a-62a434cd3a8d.gif)
