### ISSUE TITLE
weird view 

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#108]
when I look at the overview of the teams (logged in), it looks like this:
![screen shot 2014-06-23 at 17 49 24](https://cloud.githubusercontent.com/assets/1711357/3360105/541aa31e-faef-11e3-8036-e26d72c96c80.png)

**Comment by F3PiX** [comment]
I think we can close this, thanks to the responsive magic by @roosdebildt.

**Comment by roosdebildt** [comment]
nope, this one is still on unfortunately :(

**Comment by carpodaster** [comment]
The loooong index view could potentially be fixed by displaying different data in the corresponding controller in the orga-namespace.

**Comment by carpodaster** [comment]
I'm inclined to close this. @klappradla, do you think this will be solved by Project Admin Mode™ ?

**Comment by klappradla** [comment]
Looked at this yesterday night as well 😹 

I think it's already closed via redoing the navigation (did this last year I think).
