### ISSUE TITLE
Supervisor Dashboard

### ISSUE THREAD

**Issue by bastilian** [rails-girls-summer-of-code/rgsoc-teams#109]

**Comment by F3PiX** [comment]
![dashboard team cheesy rgsoc 2015](https://cloud.githubusercontent.com/assets/6314687/10191424/23fa9b24-6774-11e5-83e7-c0c00f09605d.png)

**Comment by alicetragedy** [comment]
:tada: :confetti_ball: :sparkles: :sparkling_heart: :space_invader: :clap:

**Comment by F3PiX** [comment]
It would be great to add markdown to the notepad, so that supervisors can use it as a to do list as well. That required more Javascript then we acquired this Summer. Anybody?

**Comment by F3PiX** [comment]
:bow: Thank you Laura!

**Comment by carpodaster** [comment]
Great work, Roos + Maud!!

PS: Adding markdown is pretty easy (see the activity log views), adding a WYSIWYG editor for MD is a bit of work. I wouldn't go the WYSIWYG route but feel free to send a PR for the the markdown rendering :)

**Comment by F3PiX** [comment]
We found that, and it looked easy, because all the hard work with RedCarpet and the config is already there. But, my problem was: we don't have a show view, because of the find_or_create_by. Do you mean that it still is solvable without JavaScript? Then I'll look at it again.
