### ISSUE TITLE
Remove mailings from activity stream?

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#120]
This is a follow-up to #115

Mailings sent our through the teams app are now only visible to their respective recipients. However, a mailing will be copied over into the activity stream where it's not feasible to restrict access to the original recipients.

I would like to remove the mailings from the activities list. Please object *now* :hammer: :wink:

**Comment by alicetragedy** [comment]
what's the status of this? 
I know that it's possible to view mailings in the stream ("All") now, and that one can select "Feed Entry" or "Mailings" (see attached screenshot).
Can this issue be closed then if the solution was to separate the stream into "feed" and "mailings" or is this still a thing/do we want to remove the mailings completely? 

![screen shot 2015-06-05 at 17 17 51](https://cloud.githubusercontent.com/assets/3143348/8009158/f816600c-0ba6-11e5-947b-8fc694ec8d05.png)

**Comment by carpodaster** [comment]
If I remember correctly it has only been fixed in a way that you have to be logged in to see the mailings. Everyone who's logged in can see the mailings, regardless of whether they were in the recipients list or not.

I would still like to see it removed from the open activity feed. Maybe we can make the original recipients access the archive of sent mailings from a student dashboard?

**Comment by carpodaster** [comment]
@alicetragedy I only saw your referenced isse #226 just now – sorry. So yes, I would definitely remove it for the time being, make it available **only for the orga-team** and re-introduce it for the intended audience later. D'accord?

**Comment by alicetragedy** [comment]
@carpodaster sounds like a plan. as outlined in issue #226 there seems to be a bug as mailings and everything else are still visible to non-logged in users. 
I +1 on making it available for orga-team only for now, and reintroducing it for the intended audience later!
