### ISSUE TITLE
Use a mail interceptor that works w/o Mailtrap

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#124]
* Mailtrap must be set up in `.(zsh|bash)rc`, lets move it to something like dotenv
* Fallback on a blackhole mail interceptor if Mailtrap is not configured

**Comment by carpodaster** [comment]
Also, only configure Mailtrap in [config/environments/development.rb ](https://github.com/rails-girls-summer-of-code/rgsoc-teams/blob/master/config/environments/development.rb) if the required env-variables are setup.

**Comment by carpodaster** [comment]
Almost done due to the awesome work of @marcgreenstock in #159. Just need a blackhole interceptor to prevent mails from being sent in development should sendmail be configured to fire incoming mails into space (it is on my machine)

**Comment by marcgreenstock** [comment]
@carpodaster how about [Letter Opener](https://github.com/ryanb/letter_opener)?

**Comment by carpodaster** [comment]
@marcgreenstock nah, I was just thinking about someting that would avoid emails being send in in the background. Something like this:

```ruby
# config/initializers/mail_interceptor.rb
Mail.register_interceptor(GitBasedMailInterceptor) if Rails.env.development?

# lib/git_based_mail_interceptor.rb
class GitBasedMailInterceptor
  def self.delivering_mail(message)
    message.to = `git config user.email`
    message.bcc = message.cc = nil
  end
end
```
(Disclaimer: not tested)
