### ISSUE TITLE
Check and fix bootstrap forms

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#126]
Looks weird and messy, at least in FF.

**Comment by carpodaster** [comment]
http://teams.railsgirlssummerofcode.org/teams/new will be hit quite often in the coming days and that one looks particularly evil. I mean it *works*, but it ain't pretty. If there is someone who could at least make the radio buttons + their labels look passable, that would be greatly appreciated :smile:

**Comment by sareg0** [comment]
Hey, it seems like something I could handle. Is there any way in particular they **_should_** look?

**Comment by alicetragedy** [comment]
to answer your question @sareg0, I think the alignment is the most important (and what makes it look pretty ugly) 
eg. 
- the radio buttons under type should align with "Sponsored" and "Voluntary"
- the Source URL field should be either aligned with its label or under it
- the github handle label should be aligned with its field
- the "Role" radio buttons should be aligned with their respective value (student, coach, etc..)

**Comment by sareg0** [comment]
aha! I think when I logged in I was not on the right page, now I see the ugliness. Thanks so much, I'll give it a work over.

**Comment by carpodaster** [comment]
Yay, thanks @sareg0 :balloon:

**Comment by sareg0** [comment]
I have lodge the PR for this one, so just see if it is up to scratch. I hope it is. That was harder than I thought it would be ;D
