### ISSUE TITLE
Implement a mini log engine

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#127]
Similar to https://idonethis.com/

* [x] Students' backend
* [x] Link to students/status_updates_controller from somewhere
* [x] Create `Activity` record
* [x] Updating/destroying a status update must also update/destroy the activity
* [ ] What photo should be used?
* [x] Allow quick access to a team's activity stream

**Comment by carpodaster** [comment]
Done. The status update activity lacks a pretty photo, but that one is related to #17 and can be done during the Summer of Code by @F3PiX and @roosdebildt :smile:

**Comment by F3PiX** [comment]
I'll put in on our to do-list! :-) <3

**Comment by alicetragedy** [comment]
brilliant! :sparkles:

**Comment by sareg0** [comment]
Hey @carpodaster could you give us a quick 'README' on the log engine? Just so we know how it works, and can talk to our teams about it.

**Comment by carpodaster** [comment]
@sareg0 As discussed last week, here are some commented screenshots:


Students have a "Status Update" link up top:

![status_update_01](https://cloud.githubusercontent.com/assets/164400/8451554/6d027152-1fe4-11e5-84dc-fb1b7d21424f.png)

----------

It brings up the listing of the team's recent updats. Choose "Create Status Update" to create one:

![status_update_02](https://cloud.githubusercontent.com/assets/164400/8451564/7c32bb50-1fe4-11e5-98f3-f9385454bfde.png)

----------

The form is pretty straightforward:

![status_update_03-form](https://cloud.githubusercontent.com/assets/164400/8451584/9aa45666-1fe4-11e5-8b41-60e3258ee23b.png)

----------

You can also use simple markdown:

![status_update_04-markdown](https://cloud.githubusercontent.com/assets/164400/8451593/ae0c7170-1fe4-11e5-9d07-590519f6e2cf.png)

----------

Save and marvel at the front page:

![status_update_05-frontpagersult](https://cloud.githubusercontent.com/assets/164400/8451601/be60627a-1fe4-11e5-9e42-3ce5dc349b8c.png)
