### ISSUE TITLE
update user profile 

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#130]
these fields should be mandatory: 

* [ ] Name
* [x] Githubname
* [x] email
* [ ] location
* [ ] t-shirt-size
* [ ] address

**Comment by anikalindtner** [comment]
+ delete: Irc handle
----

**Name**

*Email**

-Don’t show my email address to other users
hint: Only signed-in users will see your email address. If you don’t show your email address, others will have trouble contacting you.

**Github handle**
github.com/_______

**Twitter handle**(optional)
@______

**Homepage** (optional)

**Country**

**Timezone**(optional)

**City**


+ [ ] **I represent a company**

**About you**(optional)

hint: You can use basic Markdown here.

**I am interested in**

+ Finding a pair
+ Finding coaches
+ Finding a project
+ Helping as a coach
+ Helping as a mentor for a project that I am part of
+ Helping as a remote coach (helpdesk)
+ Helping as an organizer
+ Helping as a supervisor
+ Becoming a coaching company

### Private information
hint: This information will only be visible to yourself and organizers.

+ **T-Shirt size**: select: XXS XS S M L XL 2XL 3XL
hint: For sponsor T-Shirts

**Postal address**

hint: So we can send things we've received from our sponsors for you :)

**Comment by anikalindtner** [comment]
![screen shot 2015-03-02 at 15 10 03](https://cloud.githubusercontent.com/assets/1711357/6442191/3d5cb390-c0ee-11e4-94f6-65d2ca7764a1.png)

this needs to be clearer, I think. Either

+ make it a link saying [Show Application specific questions] that reveals then the fields
+ or make the title even bigger saying
++++++ONLY ++++ FOR APPLICANTS++++ APPLICATION SPECIFIC QUESTIONS+++++++++

**Comment by carpodaster** [comment]
It *does* say »Application-specific information« though…

**Comment by carpodaster** [comment]
@anikalindtner  Sorry, your screenshot didn't load until now. I think hiding them by default is an excellent idea. Ideally, it should be open when the page is accessed with the '#application_specific' anchor. That can be done with JS/client-side

**Comment by anikalindtner** [comment]
cool, sounds super good!

**Comment by carpodaster** [comment]
@lislis a direct link to `teams.railsgirlssummerofcode.org/users/<myid>/edit#application_specific` doesn't work anymore. Can you add some JS magic that detects whether the page was accessed with that anchor and start our with the folded input fields visible? (Uhm… does that make sense?)

**Comment by lislis** [comment]
Sure!

**Comment by lislis** [comment]
Here you go b1730722c2e4eee606fe085646e9cd60fd514889

**Comment by carpodaster** [comment]
@lislis Awesome, thank you! :star2:

**Comment by alicetragedy** [comment]
this issue can be closed, right? 
the fields are now mandatory, and the changes to the "application-specific" part of the profile have been updated iirc.
