### ISSUE TITLE
fix 2013 login bug

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#132]
The login menu isn't shown in the 2013 app and thus we can't log in and access the data stored in ther over the UI. Would be awesome to finally fix this! maybe @plexus @pxlpnk or @carpodaster ?

**Comment by carpodaster** [comment]
That's a tricky one. I don't think we have the code running the archived app readily available: unlike the gh-pages for the public blog, we didn't fork the codebase but only the Heroku app instead. Sadly, I don't have access to the Heroku application, either :sob:

**Comment by pxlpnk** [comment]
@carpodaster I just pulled the repo from heroku. Where can I put it to you? As I have no idea what data there might be stored in I don't want to post it public.

**Comment by pxlpnk** [comment]
I think there was reason though why this was disabled. 
One of them being that we need to setup new oauth credentials. Another that people sign up for it I guess.

You could run a local version of the app with the db dump from heroku and just disable the auth part?

**Comment by carpodaster** [comment]
@pxlpnk Checking it out locally with the prod dump sounds good! Can you 
 send it via email? My gpg-key is at https://aegisnet.de/pgp.txt

**Comment by pxlpnk** [comment]
Mail is on its way.

**Comment by anikalindtner** [comment]
\o/ awesome @pxlpnk!

**Comment by carpodaster** [comment]
I re-introduced the GH login and made sure it doesn't create new users (ie. only registered users can login). The code is pushed, awaiting a deployment.

**Comment by sareg0** [comment]
+1

**Comment by pxlpnk** [comment]
I just pushed the code to heroku.

**Comment by carpodaster** [comment]
¡Muchas gracias! Solved then.

**Comment by anikalindtner** [comment]
@carpodaster I tried it and clicked the "login with github"-link, but nothing happens O.o am i doing anything wrong?

**Comment by carpodaster** [comment]
Probably yeah, can't log in either but it worked locally :( I'll check tonight.

@svenfuchs can you add me as collaborator on Heroku?

**Comment by svenfuchs** [comment]
@carpodaster added you on all the appz :)

**Comment by carpodaster** [comment]
@svenfuchs Thank ye! :)

@anikalindtner Login is possible now. The github oauth secret id thingy was out of date. Fixed! :confetti_ball:
