### ISSUE TITLE
Move admin/organisation/supervisor-related content into separate namespace

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#136]
Rationale: we will eventually forget tossing in a cancan directive. Having a namespaced base controller with a pre-defined `before_action` puts us on the safer side in terms of a possible privilege escalation.

An `orga/` namespace already exists.

**Edit**: As of late June, a `students/` namespace now also exists.

**Comment by alicetragedy** [comment]
:+1: 
also, sorry for changing the title of the issue.. did not realise that it would show up here.. but there was a tiny typo that I had to fix. :p

**Comment by carpodaster** [comment]
hehe, no worries – thank you! :smile:

**Comment by alicetragedy** [comment]
as discussed today on the call, I think this is a great idea :+1:

**Comment by sareg0** [comment]
Did this recently get implemented? I noticed that there was a change in the /teams page

**Comment by carpodaster** [comment]
It's on its way, but I haven't moved existing functionality (with the exception of the teams management) into separate namespaces, only new stuff.

**Comment by F3PiX** [comment]
As of SoC 2015, the supervisor namespace exist as well :tada: 
Close this?

**Comment by carpodaster** [comment]
I'd like to keep it open until we've sift through the app once more to assert that we've indeed moved everything that can be moved to separate namespaces.

**Comment by carpodaster** [comment]
Closing this. I think we're 98% there.
