### ISSUE TITLE
Application form: Provide examples for skill-level self-assessment

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#137]
Working on the new application form I just remembered  that we wanted to turn the more or less meaningless 1..5 skill range into something related to concrete examples (like »I am comfortable solving a merge conflict with git«).

We don't have that list of examples yet :scream: We don't necessarily have 5 discrete states, maybe 3 or 4 are sufficient. Wdyt?

**Comment by alicetragedy** [comment]
hmm... yes, I think we need that. I've been replying to a couple of emails this week about possible applicants being *really* confused about which skill-level we are looking for and whether they should apply at all.. Needless to say, I think we really need to assess their skills differently in the application because, well, self-assessment really doesn't work. Can I help out in any way?

**Comment by alicetragedy** [comment]
and I think we would need either 3 or 5 out of these (strongly agree, agree, neither agree nor disagree, disagree, strongly disagree)

**Comment by carpodaster** [comment]
> Can I help out in any way?

Yes :)  What I would need is a mapping of Skill Level 1 -> *I can do this, I can do that*, Skill Level 2 -> *I can do that other thing, I can do a handstand w/o hands*, … I will continue to just store the numbers, we would need some real world examples for what they represent.

**Comment by alicetragedy** [comment]
:+1: you got it! consider it done

**Comment by carpodaster** [comment]
Whohooo! :kissing_cat:  But don't stress yourself: I don't need it NAO. Friday is alright.

**Comment by alicetragedy** [comment]
Friday was just what I was thinking - I will give it a thought, and I am off work on Friday so I got some time :tada:

**Comment by alicetragedy** [comment]
First few thoughts(definitely not done). I'm not sure about the open source one, and I think we could definitely add some more and move some skills around, happy about input.

*Skill Level 1*
- I understand and can explain the difference between data types (strings, booleans, integers)
- I have heard of the MVC (Model View Controller) pattern.
- I am comfortable creating and deleting files from the command line

*Skill Level 2*
- I am confident writing a simple method in ruby
- I am able to write a counter that loops through numbers (e.g. from one to ten).

*Skill Level 3* 
- I am comfortable solving a merge conflict in git.
- I am confident with the vocabulary to use when looking up a solution to a computing problem.
- I feel confident explaining the components of MVC (and their roles)
- I understand what an HTTP status code is

*Skill Level 4*
- I have written a script to automate a task before
- I have already contributed to an open source project with code

*Skill Level 5*

**Comment by sareg0** [comment]
These are really terrific examples. I was thinking about rearranging them, but I do think they actually make a lot of sense where they are :) I was going to say something along the lines of including 'i have attended a Rails Girls or equivalent workshop' in Skill Level 1, and Skill Level 2 'I have been attending a study group for at least three months'... But these are very subjective and unclear... I like your stuff better :)

**Comment by anikalindtner** [comment]
great work, laura! I'm not the best person to judge about the levels, but I really love the examples. the last one could even be "I have already contributed original code to an Open Source project"

**Comment by alicetragedy** [comment]
@sareg0 yeah, I know what you mean but I'm worried that adding those would make it, as you said, very subjective. (also because being there does not necessarily reflect any of your actual skills, and I'm guessing we have that somewhere else in the application, though I haven't looked) - but feel free to add some more examples! I'm still thinking about some more :)
@anikalindtner great, thank you for the input :) I've changed it accordingly.

**Comment by carpodaster** [comment]
That's an awesome list already, Laura!

Here at Absolventa, @BerliNinja suggested something related to TDD. Like _I am able to write a unit test_ or something. No idea what skill level that means, though.

**Comment by alicetragedy** [comment]
good tip! I would say that it would be a skill level 3 or above; complete beginners literally do not touch testing (I don't think) and people who have recently gotten started are usually not super comfortable with writing tests either, as I think writing tests requires you to be very very comfortable with code already.

**Comment by alicetragedy** [comment]
@carpodaster I've added some stuff to the list and think I've covered most areas; could you please check when you have a minute? I believe that's actually enough, unless you think we need to add more. (but I wouldn't want to overdo it)
Maybe I could add something about setting up/configuring servers for production, or deploying an app?

**Comment by alicetragedy** [comment]
we can close this, right @carpodaster?

**Comment by carpodaster** [comment]
@alicetragedy We have 'em all in https://github.com/rails-girls-summer-of-code/organization/issues/89, right? If so: case closed :bookmark_tabs: :hammer:   Thanks a lot!

**Comment by alicetragedy** [comment]
yep :+1:

**Comment by carpodaster** [comment]
Since styling things takes me a disproportional amount of time: is there anyone able to add the skill level examples to `app/views/users/edit.html.slim` ? I was thinking about a Bootstrap modal popup. @lislis  maybe? :smile_cat:

**Comment by sareg0** [comment]
I would love to help @lislis with this :) for funz and learningz

**Comment by sareg0** [comment]
I have made a commit that @carpodaster is reviewing for the last piont mentioned... thanks for @lislis and her guidance :)

**Comment by carpodaster** [comment]
@sareg0 I've cherry-picked your skill level explanation. Good stuff – ¡muchas gracias!

**Comment by sareg0** [comment]
Sweeeeet! Thank you!
