### ISSUE TITLE
Upgrade to Rails v4.2

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#139]
* Upgrade to latest 4.1.x first
* Upgrade from 4.1.x to 4.2.0

Tools: railsdiff.org

* [ ] Remove monkey patch from `config/initializers/monkey_patch_mail.rb`

**Comment by marcgreenstock** [comment]
wow, we merged? everything working as expected?

**Comment by alicetragedy** [comment]
:tada: :tada: :tada: :tada: :tada:

**Comment by carpodaster** [comment]
>  everything working as expected?

I hope so :trollface:   Nah seriously, I'm not seeing any strange behaviour. Thank you for your PR, @marcgreenstock !
