### ISSUE TITLE
retrieve activity from the teams' github repos 

### ISSUE THREAD

**Issue by ellenkoenig** [rails-girls-summer-of-code/rgsoc-teams#14]
either through a webhook/events, or polling

**Comment by carpodaster** [comment]
We have a included a micro blog system into the Teams App last year. While I completely agree that the Github activity would create visibility, I think it would also create a lot of noise. I'm closing this in favor of the Activity Log

**Comment by alicetragedy** [comment]
I think I can live with that. ;)
