### ISSUE TITLE
Team creation: Remove sponsored / voluntary radio box

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#140]
It's important after teams are accepted but it shouldn't be accessible to non-organisers

**Comment by alicetragedy** [comment]
this means that we are not asking the team if they want to apply voluntarily or only funded, right?

**Comment by carpodaster** [comment]
Not when they create a team. I will add a check box to the application form

**Comment by alicetragedy** [comment]
great, thanks! :tada:  I'll keep that in mind when answering emails then.

**Comment by carpodaster** [comment]
@alicetragedy Oh sorry, I wasn't thinking about its implications on support emails! I shall keep _that_ in mind when making changes to the app

**Comment by alicetragedy** [comment]
@carpodaster no worries, no one has brought it up until yesterday, and I waited to answer that email until I had a clearer idea of how we would handle possible volunteers in the application process :) so it's all good. Also of course good to know that they can choose to apply as both with the checkbox. thank you for doing all this great work on the teams app!!!
