### ISSUE TITLE
Remove 'Offering Desk Space' option

### ISSUE THREAD

**Issue by sareg0** [rails-girls-summer-of-code/rgsoc-teams#141]
After a discussion on hangout, and with Sven we are going to strike the option for companies to just provide deskspace. 

We feel it's a little unneccessary, and don't really want companies providing desk space but not coaching support anyway. Students may as well stay at home or find some free desk space anywhere, and the companies that offer it may not be taken up on it, so best not to offer that as an option at all.

We may remedy this someday in the future, by having an area where all sort of desk space can be offered, and students can take a look at a map. That is probably not going to happen this time around.

Please remove this option from the teams app.

**Comment by sareg0** [comment]
thanks @carpodaster

**Comment by carpodaster** [comment]
:bow:
