### ISSUE TITLE
Application form: ping coaches and mentors

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#144]
* [x] Send an email when added to a team
* [x] Add `application_drafts/index` listing all applications that they are part of
* [x] Mentors: add `PUT application_drafts#signoff` (irreversible!)

**Comment by sareg0** [comment]
Mentors will sign off AFTER close of applications. We will give teams a week after the closing of applications to get the mentor to sign off
This will save building extra functionality, and also make sure that there is a set period Mentors and Students know about to get the signoff

**Comment by carpodaster** [comment]
@marcgreenstock are you working on the last item, the mentor signoff?

#188 has a skipped example that's a placeholder for the mentor ping (some email with a link, stating that they can now sign off that application).

Technically, the sign off isn't a thing on the draft anymore as it's already converted to an application. The controller action may very well be `PUT applications#signoff`. Or we can signoff on the drafts controller, proxying the signoff to the `has_one` - associated application record. The latter doesn't feel right in a RESTful sense, but would have the charm of re-using the index template and just add a button to the application drafts listing.
