### ISSUE TITLE
Application form: define ready state for a draft

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#145]
-> validation context, see also #129 / #130

**Comment by carpodaster** [comment]
Hey @ramonh, have you had a chance to continue Sunday's work on this one?

**Comment by ramonh** [comment]
Not yet, sorry, I plan on getting this done today, though! Hope that's okay

**Comment by ramonh** [comment]
Hey @carpodaster! Should be done now. Not sure how to best have you check it out, but please see ramonh/rgsoc-teams in the branch we started

**Comment by carpodaster** [comment]
@ramonh Awesome! Can you create a PR for it?

**Comment by ramonh** [comment]
Sure! Will do

**Comment by carpodaster** [comment]
@ramonh validation branch merged! :confetti_ball: I just noticed that we need a way to tell users about possible validation errors. I have an idea but that will have to wait for tomorr :sleeping:

**Comment by ramonh** [comment]
YAY! 🎉 Okeydokey! Let me know how I can help. Really enjoyed working on this. I'll have a think about it too.
