### ISSUE TITLE
Update Teams/New

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#146]
okay, so I think it would be great if we could distinguish between accepted teams and applying teams, since some of the features (such as team twitter account, github, blog url) really don't apply unless you are accepted as a team. 

+ [x] Name-> "Team name"
hint: e.g. Anna & Jolanda, Team Unicorns etc.  You can also change this later. 

+ [x] Description 
hint: Summary of your project(s) -> tell us about you 
+ [x] link is broken: 
![screen shot 2015-03-02 at 14 10 11](https://cloud.githubusercontent.com/assets/1711357/6441211/e6a60bc6-c0e5-11e4-82c1-631702685d1c.png)
+ [x] delete: 
![screen shot 2015-03-02 at 14 16 32](https://cloud.githubusercontent.com/assets/1711357/6441283/c6c4fdde-c0e6-11e4-9acd-bb9ac084ee01.png)
 and: 
![screen shot 2015-03-02 at 14 17 05](https://cloud.githubusercontent.com/assets/1711357/6441293/d71932b8-c0e6-11e4-80ad-ba3794c1d4cb.png)

+ [x] These fields I'd only show if the team is accepted:

+ [x]  ![screen shot 2015-03-02 at 14 17 43](https://cloud.githubusercontent.com/assets/1711357/6441313/f99bbea0-c0e6-11e4-9116-2a2b7c80b1e5.png)

and 

+ [x] ![screen shot 2015-03-02 at 14 20 14](https://cloud.githubusercontent.com/assets/1711357/6441355/51ca0ac8-c0e7-11e4-9343-f78d31271733.png)

and:

+ [x] ![screen shot 2015-03-02 at 14 22 36](https://cloud.githubusercontent.com/assets/1711357/6441381/9d8ce69c-c0e7-11e4-82f2-93be6d6847f9.png)

+ [x] "add another team member" put this field right under the "Team Name" field 

+ [x] "Remove" -> Remove team member
+ [x] Remove this Event-thingy:
![screen shot 2015-03-02 at 14 27 06](https://cloud.githubusercontent.com/assets/1711357/6441470/82a427f4-c0e8-11e4-9bd2-38f357c2ecb7.png)

**Comment by anikalindtner** [comment]
also, I'd leave out the Supervisors here:

![screen shot 2015-03-02 at 14 48 41](https://cloud.githubusercontent.com/assets/1711357/6441783/49ef253c-c0eb-11e4-9eba-152fbd9eeb2d.png)

Since the students can't do anything about that and it might look as though they should, if it's shown as empty.

**Comment by carpodaster** [comment]
@anikalindtner Your view as an organizeress differes from that of a normal user. Do you have access to a locally running app where your user account is not an admin? If not, I can setup the staging-area tonight so that we may access it as normal applicants w/o admin superpowerz

**Comment by anikalindtner** [comment]
@carpodaster i set myself to student for this case. not organizer. so this was, what students see

**Comment by carpodaster** [comment]
@anikalindtner Was that on the production app? If so, you are still an organizer and that has a global effect.

**Comment by anikalindtner** [comment]
@carpodaster sara removed me as an organizer and i did have a different view on the teams. i couldn't e.g. add a supervisor to the team anymore. but i could still see the supervisor - empty field once it was created.

**Comment by carpodaster** [comment]
@anikalindtner Can you add GH's magic issue check boxes so that we can track which of these items are done?

**Comment by anikalindtner** [comment]
@carpodaster magic's done! :sparkles:

**Comment by carpodaster** [comment]
Supervisor listing looks like that now:

![screen shot 2015-03-05 at 00 18 55](https://cloud.githubusercontent.com/assets/164400/6495772/6985651c-c2cd-11e4-80ac-4288620a89c5.png)

**Comment by anikalindtner** [comment]
AWESOME! :+1:

**Comment by alicetragedy** [comment]
great!!!! :heart:
