### ISSUE TITLE
Teams-Visibility

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#149]
Also, in order to protect their privacy (e.g. from current bosses or whoever), I'd not show the teams that aren't accepted under /teams.

**Comment by carpodaster** [comment]
Maybe make it optional to remain invisible? Just like we have an option not to show a user's email address even for logged-in users.

**Comment by anikalindtner** [comment]
I'm fine with whatever solution is easier to implement :)
