### ISSUE TITLE
Update Application

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#150]
+ [x] this field is missing in the profile: 

![screen shot 2015-03-02 at 14 54 18](https://cloud.githubusercontent.com/assets/1711357/6441977/820ac092-c0ec-11e4-9857-a9c30976a68b.png)

---------------

+ [x] broken?
![screen shot 2015-03-02 at 14 53 06](https://cloud.githubusercontent.com/assets/1711357/6441982/8e4210ae-c0ec-11e4-9a86-120eb09642e9.png)
Also: the text is still missing the option of adding their own project. 

---------------

+ [ ] ![screen shot 2015-03-02 at 14 50 17](https://cloud.githubusercontent.com/assets/1711357/6442012/cc4dce2e-c0ec-11e4-8cf1-8746b02a0e26.png)
-> "You can edit the fields about you in your user profile. They are only visible to organizers."

---------------

+ [x]  ![screen shot 2015-03-02 at 14 54 41](https://cloud.githubusercontent.com/assets/1711357/6442024/e7c53db8-c0ec-11e4-8145-9061e206c5bb.png) 

Your application was saved as a draft. You can find it under "apply now". 

---------------

+ [x] Change: "Apply now" to-> My application

**Comment by carpodaster** [comment]
> "You can edit the fields about you in your user profile. They are only visible to organizers."

That is not true. Everyone in the team, that's including coaches and mentors, can also read that.

**Comment by carpodaster** [comment]
> Also: the text is still missing the option of adding their own project. 

See comment <elsewhere> (I don't know where :smile: ): Don't we insist on the project being listed (and even accepted) on the projects repo?

**Comment by alicetragedy** [comment]
I've fixed number 2 here https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/151
the field with no placeholder is for the project name :)

**Comment by alicetragedy** [comment]
and yeah, what @carpodaster said - the plan was to not have them be able to add their own project, but have them ping the mentor of a project they're interested in if the project wasn't submitted....

**Comment by carpodaster** [comment]
I've added a link in the success flash message after creation (fixes number 4)

I've left out the »*They are only visible to organizers.*« (number 3) bit since the whole team can access the application.
