### ISSUE TITLE
Team form: Adding roles / sources

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#152]
* [x] teams form: roles
* [x] teams form: soures
* [ ] user editing: roles

Some nested form elements could need some styling, @lislis maybe? :smile_cat: 

--------------------

**teams/new: editing roles**
![screen shot 2015-03-05 at 00 23 56](https://cloud.githubusercontent.com/assets/164400/6496156/da659ae2-c2d0-11e4-8910-f7dd25d57cc3.png)

--------------------

**teams/new: editing sources** (comments see above)

![screen shot 2015-03-05 at 00 45 58](https://cloud.githubusercontent.com/assets/164400/6496177/0cbf3822-c2d1-11e4-87fd-03e2d7432a91.png)
--------------------

**users/new: editing roles**

![screen shot 2015-03-05 at 00 38 11](https://cloud.githubusercontent.com/assets/164400/6496161/e6d1583e-c2d0-11e4-9bef-a807acaad415.png)

**Comment by lislis** [comment]
I'see what I can do, but probably in the afternoon. Thanks for the helpful hints :)

**Comment by carpodaster** [comment]
Thanks @lislis, looks great! Could you add the same styling to the `users/edit` template as well? The editing of roles I mean.

**Comment by lislis** [comment]
@carpodaster not sure what you mean. When I go to `/users/1/edit` I can't see an edit role section. Am I looking in the right place?

**Comment by carpodaster** [comment]
@lislis you probably are :smile:  … only you're probably missing some access rights to have it displayed. If you temp. change line 93 from `- if admin?` to `- if true`, it should appear.
