### ISSUE TITLE
users/edit: A role will not be destroyed when you 'remove' + submit

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#154]
Computer says no when I try to remove @alicetragedy from Team Origami

![](http://wowalt.com/wp-content/uploads/2014/07/computer-says-no.png)

**Comment by alicetragedy** [comment]
Okay. I just tried it, and it works if I remove myself (obviously not the point, right?)

**Comment by F3PiX** [comment]
I couldn't remove my own roles. Would be great to solve this, it will make the life of next year's Rails Girls so much easier. Someone want to pair with me on this?

**Comment by carpodaster** [comment]
Solved by #577
