### ISSUE TITLE
Application form: create an application from a valid draft

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#163]
See also ~~#145~~

**Comment by ramonh** [comment]
Hey @carpodaster :)

I've enabled the apply state validation for an `ApplicationDraft` in #173.

I'll begin investigating how we can create an `Application` from said draft.

**Comment by cypher** [comment]
@ramonh I've converted `ApplicationDraft` to use a state machine in https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/171, and have started on working #144 to implement the mentor signoff, which in turn would then trigger the conversion of an `ApplicationDraft` to an `Application`. Maybe you'd like to collaborate on that?

**Comment by carpodaster** [comment]
@ramonh @cypher Thinking about the mentor-signoff triggering the conversion: we have the not-entirely theoretical option that a mentor is not available to sign off an application draft in time. The selection committee might still decide on one such application on a case-by-case basis or contact the mentor themselves / ping them but in any case, there would be an application record to work on. Maybe we should make the mentor-sign off a mandatory state then?

**Comment by carpodaster** [comment]
^-  Edit: should **not** make the mentor-signoff a mandatory state 
![Doh](https://rafinhaea7arte.files.wordpress.com/2010/04/homer-doh.gif)

**Comment by ramonh** [comment]
Hey @carpodaster and @cypher. Sounds good. I'll take a look at this PR and see how I can help. :+1: 

In the meantime, I've also implementation the `ApplicationDrafts#apply` controller action here: ramonh@91d4f4bfd391b3aa5a2972cadaff1cd722ab8fe5
