### ISSUE TITLE
Multiple Applications: Prioritize which one is the preferred one

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#168]
Student can hand in two applications, but it would be nice if they could state which of the two is their preferred one.

Any takers?

I mentally label this a nice-to-have one. :smile:

**Comment by sareg0** [comment]
Hey @marcgreenstock do you think you have the time to take a gander at this one?

**Comment by marcgreenstock** [comment]
sure, sounds simple.

@carpodaster just a `is_preferred` boolean column on the `application_drafts` table?
When updating, it sets the other associated rows to false or a referential column on the teams table?

**Comment by carpodaster** [comment]
The simple boolean flag sounds good, @marcgreenstock – I was thinking about an integer field and a sorting plugin but since we only only two application, your approach is much better!

**Comment by marcgreenstock** [comment]
Oh like a `priority` integer. That approach might be more scalable, in case you decide that more than two application drafts can be accepted. Besides we could use `acts_as_list` in this case and wash our hands of having to code up the update ourselves. I like your approach better :) I'll think about it over lunch and take care of it when i get back.
