### ISSUE TITLE
Call for a wording check: error messages on an incomplete application draft

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#169]
The validity of an open application draft can be checked as of 32c7d39156e0a1f7e514b899ccbdddd66828a606 . (Go to the botton and click the 'Check' button). You'll get a number of error messages that are defined in [config/locales/en.yml](https://github.com/rails-girls-summer-of-code/rgsoc-teams/blob/master/config/locales/en.yml#L12).

I think the wording of some of these could be better so I am open for suggestions. Better yet: file a PR :smile:

**Comment by alicetragedy** [comment]
I've taken a look at the wording and it all sounds fine to me – there's not really anything I would change. :+1:

**Comment by carpodaster** [comment]
@alicetragedy thank you for looking into this! I'll close this issue then.
