### ISSUE TITLE
a student should not be able to edit her pair's learning period

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#170]
When editing her application and viewing her pair's information, a student should not be able to select one of the radio buttons (Learning Period) from her pair's application.

![screen shot 2015-03-21 at 17 57 16](https://cloud.githubusercontent.com/assets/3143348/6765947/05ccb1f4-cff4-11e4-8e33-565ba3517844.png)

**Comment by carpodaster** [comment]
We identified this as Chrome-related. The fields are properly `disabled` for Firefox.

The severity is very low, though: it's only the UI element, the corresponding attribute on the pair's profile will **not** be overwritten. We should still find a way to fix it, of course.
