### ISSUE TITLE
 Upgrade Ruby from 2.1.5 to latest version.

### ISSUE THREAD

**Issue by jasnow** [rails-girls-summer-of-code/rgsoc-teams#177]
As of March 30, 2015, Ruby version is 2.2.1.
  * Change version in all config files, such as .ruby-version, .travis.yml, etc.
  * Run **bundle** to create new gemset.
  * Clean up warnings and errors.

**Comment by jasnow** [comment]
Two loose ends: 
  * WARNING: Nokogiri was built against LibXML version 2.9.1, but has dynamically loaded 2.8.0
  * One line in slim file. Tagged with "FIXME:". Use **git grep FIXME** to find it.

**Comment by jasnow** [comment]
Why is **input_html** listed twice in **app/views/application_drafts/new.html.slim** file (line 54)?

```
= f.input :misc_info, as: :text, label: 'Anything else to add?', 
input_html: { rows: 4 }, hint:
'Address anything that you feel is relevant to your application and was not covered previously.',
input_html: { disabled: !application_draft.as_student? || application_draft.applied? }
```
Unclear how to fix it.

**Comment by carpodaster** [comment]
Ah, that must be a copy/paste error. Thanks for spotting it! Just but the `rows: 4` in the 2nd `input_html` hash.

**Comment by jasnow** [comment]
Show me the revised line and I will check it in and close this issue. THANKS...

**Comment by jasnow** [comment]
Too confusing with closed PR so closing.
