### ISSUE TITLE
Can not submit application form.

### ISSUE THREAD

**Issue by mymai91** [rails-girls-summer-of-code/rgsoc-teams#182]
In the part "Show application specific information" I checked fields 
Please rate your level of programming experience (1 being the 'lowest' and 5 the 'highest').
For how many months have you actively been learning after your first workshop?
But the result doesn't show on our application. I don't know why.
*This is my profile:*
![rails_girls_summer_of_code_-_teams](https://cloud.githubusercontent.com/assets/6791942/7001496/17c73808-dc64-11e4-9265-d4d2aaabe2c7.png)

*This is my team application:*
![screenshot_4_6_15__1_53_pm](https://cloud.githubusercontent.com/assets/6791942/7001505/4a9ad0b4-dc64-11e4-9e77-0b3da5ca95e8.png)

*When I check `Check Validity` button the result show but I can't submit my application.*
![rails_girls_summer_of_code_-_teams](https://cloud.githubusercontent.com/assets/6791942/7001517/a3c4fc3c-dc64-11e4-827f-bd4f15a5cb0c.png)

*Currently, I'm using Chrome Version 41.0.2272.104 (64-bit)*

Could you help me check it?

**Comment by mymai91** [comment]
*Currently, I'm using Chrome Version 41.0.2272.104 (64-bit)*

**Comment by sareg0** [comment]
Hi @mymai91 we will be opening up submissions soon. Your applications will be saved as a draft in the meantime. We will send an email out to all currently registered teams once we open submissions. I will comment this issue and close it as soon as submissions have opened, ok?

**Comment by mymai91** [comment]
@sareg0 Yes, Thank you.

**Comment by sareg0** [comment]
Hi @mymai91 you can now submit your application. Please do check your inbox, however, for a mail we sent regarding submissions. I will now close this issue.
Good luck with your application!

**Comment by mymai91** [comment]
@sareg0 How about checked fields? Like I take the pictures above. The result in the application isn't consistent with my profile.

**Comment by sareg0** [comment]
Hey @mymai91, @carpodaster has commented on your other issue. 
Please take a look under your profile, and hit 'Edit', and take a look at the 'Application Specific Information'. Your Skill Level data should be stored there. It just may not be reflected on your application draft, which is  problem we have not yet gotten to the bottom of. 
Many thanks for the understanding
