### ISSUE TITLE
Add upload functionality to application drafts

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#186]
Teams may have project plans in greater detail (even including tables and colourful charts) that can't be represented in a text area input. A file upload would be in order.

* [ ] Allow exactly one upload per application form (rationale: the selection committee has to look through them, opening several additional files per application is too much)
* [ ] Require PDF as the file format (rationale: that can be read by anyone)

**Comment by marcgreenstock** [comment]
Should we upload to S3 directly using the AWS JavaScript SDK?

**Comment by carpodaster** [comment]
I'm afraid I don't know the AWS JavaScript SDK :( I was thinking of [carrierwave](https://github.com/carrierwaveuploader/carrierwave) or paperclip. These would allow ActiveModel validations.

**Comment by marcgreenstock** [comment]
Using paperclip or friends is fine, however a process will be blocked while a file is being uploaded from the browser. Also if a user has a slow connection and/or a large file heroku will timeout after 30? seconds and will fail the upload.

Want me to take care of this one? All that's needed is an S3 bucket and an AWS IAM key and secret, but i'll set it up with my own account first and make it configurable with environment variables.

**Comment by carpodaster** [comment]
The 30 seconds timeout is definitely a very good reason to upload it directly to S3, yes. Is there a way to easily wed the JS SDK with paperclip/carrierwave?

I don't think we should bother adding the file upload at this stage of the application period. We're only open for another week and I think this is something an RGSoC team could work on over the course of the summer.

That's not to say you I want to stop you :)

**Comment by carpodaster** [comment]
@alicetragedy since you're working on some fine tuning for the application process, do we have a use case for this? If not, I'm inclined to close this.

**Comment by alicetragedy** [comment]
@carpodaster we can discuss on tonight's call, but since we decided to "kick out" the idea of the project plan, this issue would be obsolete. Should we need this in the future, we can always re-open. +1 on closing it!

**Comment by carpodaster** [comment]
@alicetragedy you're absolutely right. Cloooooosing tiiime! :musical_note:

**Comment by alicetragedy** [comment]
:dancers:
