### ISSUE TITLE
Adding coaches to application extend capacity

### ISSUE THREAD

**Issue by snjqi188** [rails-girls-summer-of-code/rgsoc-teams#189]
Hi all. My team has not been able to add more than 3 coaches in the application. I believe there's a max capacity. One of our coaches is left out of the process! Please expand the capacity!

**Comment by carpodaster** [comment]
Hi @snjqi188 – there is no upper limit for coaches in place. I've just verified it locally and I could easily add a 4th coach to a test team. Can you please describe the exact steps you took to add a coach? Also, can you add a link to your team profile (unless you flagged it as invisble/hidden) ? Thanks!

**Comment by snjqi188** [comment]
Oh I see. It says 'user has already been taken' when we try to add @link664 as a coach.
Yikes!
https://teams.railsgirlssummerofcode.org/teams/15

**Comment by carpodaster** [comment]
Are you using the Team > Edit > Members form (the one that has radio boxes) or Team > Add a member?

Just to double check: you select 'coach' as the role, right? Is link664 member of a (hidden) team as a student maybe?

**Comment by snjqi188** [comment]
Edit>Members didn't work but Team>Add a Member works just fine!

Thanks for all your help!

**Comment by carpodaster** [comment]
Glad that solved it :smile:

**Comment by sareg0** [comment]
:+1:
