### ISSUE TITLE
* nice-to-have: List overview of all the involved projects with links to the participating teams

### ISSUE THREAD

**Issue by ellenkoenig** [rails-girls-summer-of-code/rgsoc-teams#19]

**Comment by amrtanair** [comment]
When you say "links to the participating teams", do you mean the ones that got selected for that project or the ones that have applied for it?  @carpodaster @ellenkoenig

**Comment by alicetragedy** [comment]
@amrtanair the ones that got selected to participate.

**Comment by F3PiX** [comment]
Surprise! This one is done in #791 .
There is also a follow-up issue #784. 
I think we can close this? (@carpodaster)

**Comment by alicetragedy** [comment]
@F3PiX I'm not sure about this — where are the participating teams shown on the project list? I still think it would be great to see the teams + associated projects somehow, not sure if the project page is the best place for it though. wdyt?

**Comment by F3PiX** [comment]
Oops, good catch! That was done in my dreams....  ;-) I'd really like to add a column with a link to the team working on the project, preferably their activity stream.
When we are showing the 'active projects' (= accepted and with a team working on it), I'd really like to see what team is associated - preferably with a link to their activity stream. I'd say that is the most useful team information from the 'projects page point of view'. 
 See #784 about the Project Page.

**Comment by alicetragedy** [comment]
@F3PiX haha :D Yeah, I agree with you — adding that column with a link to the team working on the project makes a lot of sense. Would love to see this happen <3

**Comment by alicetragedy** [comment]
@F3PiX haha :D Yeah, I agree with you — adding that column with a link to the team working on the project makes a lot of sense. Would love to see this happen <3

**Comment by F3PiX** [comment]
Okay, let's do it!

**Comment by mkalininait** [comment]
It would be also great to show the team's project on the team's page.
I wonder if it will require changing the way we assign projects to teams and the team model.

**Comment by F3PiX** [comment]
I'll close this one, there is a follow-up issue, #784  where we can collect the discussions. Feel free to reopen if there is something that needs discussing.
