### ISSUE TITLE
Revisit application scoring for the selection process

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#191]
Due to the change in how we lodge applications now, all the scoring logic in Application has to be reviewed and/or adapted. I definitely need help with that! (Re: #188)

The selection process will start April 15th, 2015. I have time to work on this next Monday and Tuesday. Who's down? :smile:

**Comment by alicetragedy** [comment]
I'd be happy to help, and @sareg0 was down for it as well. Tuesday afternoon-evening-ish would work for me!

**Comment by alicetragedy** [comment]
we can close this I think. Our pairing session was more or less successful..  ;)

**Comment by sareg0** [comment]
a little later but :tada:
