### ISSUE TITLE
Radio buttons in application form do not correspond to user profile data

### ISSUE THREAD

**Issue by mymai91** [rails-girls-summer-of-code/rgsoc-teams#192]
In the part "Show application specific information" I checked fields 
Please rate your level of programming experience (1 being the 'lowest' and 5 the 'highest').
For how many months have you actively been learning after your first workshop?
But the result doesn't show on our application. I don't know why.
This is my profile:
![my-profile](https://cloud.githubusercontent.com/assets/6791942/7103857/f884d844-e0e4-11e4-9306-b5b84f6671db.png)

This is my team application:

![team1](https://cloud.githubusercontent.com/assets/6791942/7103853/e139b772-e0e4-11e4-9137-78b82876352e.png)

Currently, I'm using Chrome Version 41.0.2272.104 (64-bit)

Could you help me check it?

**Comment by carpodaster** [comment]
Hello @mymai91 – we are aware that this situation occurs for some applicants. Do the checkboxes show up properly for your pair, or is it just your fields that are not pre-set with values from your user profile.

To assure you: if the values are checked in your user profile, you're all good. It's weird that they don't show up in the application draft, and I have yet to get to the bottom of this, but the application data will be collected from your user profile once you hit 'Submit'.

**Comment by mymai91** [comment]
@carpodaster: I got it. Thank you.

**Comment by carpodaster** [comment]
This has been fixed for this year's application process! :confetti_ball:
