### ISSUE TITLE
Radio Buttons in application not working

### ISSUE THREAD

**Issue by mixolidia** [rails-girls-summer-of-code/rgsoc-teams#196]
For questions:
"According to these guidelines, what is your programming level (where 1 is the 'lowest')?"
and
"For how many months have you actively been learning after your first workshop?"
Chosen options are saved. When one student saves as draft the other student choices are erased.

**Comment by sareg0** [comment]
Hi Mixolidia, 

When you select your skill level, and hit 'Save draft', your 'Skill Level' selection will appear to be empty. However, the data has still been saved. If you want to verify this, navigate to your Profile page, and hit 'Edit'. Navigate to the Application Specific information in that area, and you should see your skill level listed there.

If you hit 'Check Validity', and the Teams App doesn't return any warnings about radio button fields being missing, you're application is good to send. When the draft applications is submitted, it will automatically pull 'Skill Level' data from your profile.

We sent an email to applicants about this this morning just to let them know this. I will close this issue, although we will keep on looking into it.
