### ISSUE TITLE
problem with saving the information in the field for voluntary team

### ISSUE THREAD

**Issue by soff22** [rails-girls-summer-of-code/rgsoc-teams#197]
I have a problem with saving the information in the field for voluntary team.

As a voluntary team, how many hours per week would you be able to work in the project?

The text cannot be saved after I click Save as a draft and when I look again at the field it is empty.

**Comment by alicetragedy** [comment]
hi @soff22, I believe it should work if you enter an integer only (eg. 20), I've just tried it out locally – however you are right, there is no error message implying that this field should be integer-only. Maybe we can quickly try to fix that! Thank you for pointing it out.
