### ISSUE TITLE
Application form: confirmation needed before it is submitted

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#199]
At least a javascript dialog. Better yet: asking the user to explicitly type 'yes' or something.

**Comment by sadiksha** [comment]
To get a basic idea of the project, I would like to work on this issue. 

As I understand, the dialog should appear before submitting the project. Is it right?

**Comment by carpodaster** [comment]
Hello @sadiksha ! We're in the process of reworking the application process (again…). This issue is still relevant but we are very likely to move some files around, it's probably best to implement this is as modular as possible. That way we can easily transfer the work / the patch from your branch or Pull Request to the new application process.

As for your question: absolutely right, this would be a required input as the last step, i.e. when or before the user clicks on "Apply".

**Comment by amrtanair** [comment]
Heyy I am applying for RGSoC2017 and I wanted to get a feel of the project, so I have been solving a few issues :) This seems to be an interesting one.  I wanted to use the [data-confirm-modal gem](https://github.com/ifad/data-confirm-modal) to resolve this. Should I go ahead with it?
@carpodaster

**Comment by alicetragedy** [comment]
Hi @amrtanair, I think we'd like to avoid adding an extra gem just for this purpose. Could you hold off on working on this just yet, until we've sorted it out? Thanks!

**Comment by amrtanair** [comment]
Okay @alicetragedy I'll try searching for a way I can solve this issue without using any further gems. :)

**Comment by alicetragedy** [comment]
Would be great! Note: this is not time-sensitive, as we are closing applications tomorrow already. Take your time thinking about different options and feel free to pop in here to ask questions if you're unsure about anything.
