### ISSUE TITLE
Application form:  'Apply' action should save draft / assign new attributes before converting

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#202]
When a user changes data in the form field but doesn't explicitely click 'Save draft' before submitting the application, the most recent updates are lost as the controller action only calls the state machine transition without assigning potentially updated attributes.

**Comment by michaelem** [comment]
Same thing happens when I change something and click 'Check Validity'. I guess this is not the desired behavior as well?

**Comment by carpodaster** [comment]
Ah, good catch! Sure, this appies (tehehe…) to `Apply` as well.

I'm not sure I understand the show view idea, but I fully agree that students shouldn't guess which button does save and which one doesn't. Maybe just have all buttons save stuff?

**Comment by michaelem** [comment]
I think we can probably close this since the buttons now simply disable when the form is changed.

**Comment by alicetragedy** [comment]
:+1:

**Comment by carpodaster** [comment]
Excellent work, @michaelem – thank you!
