### ISSUE TITLE
Applications view 

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#206]
It's been hard to read the applications, especially with the fields not showing the questions we asked, but just some field_name-thingy. I'd love it if we could make it this year a bit more readable and easier to rate in showing the exact question we asked the teams above their answers. For now it looks like this:

![screen shot 2015-04-17 at 18 25 40](https://cloud.githubusercontent.com/assets/1711357/7206225/8a39ccc4-e52f-11e4-8bce-d639e000436e.png)

I guess there is probably an easy way to switch out the "project_name" with "What project are you planning to work on".

Seems to me that we could jut exchange the "f.input :," with the "label:" and it should show the questions instead of the weird description?

**Comment by carpodaster** [comment]
The way the data is presented is super lazy: The view just iterates over whatever field exists in the application and displays its name together with its value. That's actually why there was little to no adaption needed even though we virtually turned the application process upside down.

There is no way of automatically infering the human-readable question without hard-coding and duplicating the field -> question association. It's certainly not rocket science, but I wouldn't do it for said duplication / hard coupling reasons.

What I can offer is using [this translation table](https://github.com/rails-girls-summer-of-code/rgsoc-teams/blob/master/config/locales/en.yml#L13) which is used to prettify error messages on an `ApplicationDraft`. Would that help / solve it?

**Comment by ramonh** [comment]
Thanks, @carpodaster! That was very helpful

**Comment by carpodaster** [comment]
Done in #208
