### ISSUE TITLE
Clicking save in the rating process should always redirect back to /todos

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#219]
Right now, every time the second student in a team is rated by a reviewer (according to the workflow team -> application -> student 1 -> student 2), the reviewer is redirected back to /applications. I think it would make more sense not to interrupt the flow and to have the reviewer be automatically sent either a) to the next team or b) to /todos.

**Comment by carpodaster** [comment]
I'd say b), but I haven't done any reviews :wink:

**Comment by anikalindtner** [comment]
hmmmm that doesn't seem to happen for me though. i'm just directed to the next student of the next team after I've rated the project

**Comment by alicetragedy** [comment]
@anikalindtner I think that this was fixed by one of @svenfuchs' recent commits. It does not happen to me anymore, but was happening constantly last week when I first started rating.

**Comment by anikalindtner** [comment]
aahh coolio. so we can close this?

**Comment by alicetragedy** [comment]
yes I think so – maybe @svenfuchs can confirm?

**Comment by carpodaster** [comment]
Yep, seems to be fixed here: 6ec65d8ab432a78d3a1061ce5b1e515287fd0e3f

**Comment by sareg0** [comment]
oh yay!! This is awesome :)
