### ISSUE TITLE
Format project plan in the application view (rating process)

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#220]
When applying, applicants can enter markdown into the "project plan" application field, however in the application view when rating, the information is shown as simple (and not formatted) text.

**Comment by carpodaster** [comment]
We don't explicitly state that we support markdown for any field in the application draft but it makes sense. I hope it doesn't break formatting for not-really-markdown attempts to format the project plan. If so, we'll just have to revert it.

**Comment by alicetragedy** [comment]
@carpodaster you're right! It's just in the team form – I was convinced we had that `hint` in the project description field, too. d'oh! https://github.com/rails-girls-summer-of-code/rgsoc-teams/blob/master/app/views/teams/_form.html.slim#L44
and thank you :sparkles:

**Comment by carpodaster** [comment]
@alicetragedy I added markdown formatting for `project_plan`, but I don't know if it's better now. Decide for yourself :) I can revert the changes if things are messed up.

**Comment by alicetragedy** [comment]
@carpodaster great, I will check it out later, and I think we'll notice soon enough if things are messed up ;) have a great day :sunny:
