### ISSUE TITLE
JUDGING WEEKEND - Extra Points Displayed in Overview

### ISSUE THREAD

**Issue by sareg0** [rails-girls-summer-of-code/rgsoc-teams#221]
This is good to have for the weekend for judging purposes.

We would like see the extra points, each judge has given the team. We would like to see this transparently, so that we can address any extremely high/low ratings, if it seems odd.

This is a task for anyone, but happy to answer questions on this. 

Not 100% sure if this is a bug, but I'm classing it as such for now.

**Comment by carpodaster** [comment]
Rating/Selection engine will be rewritten for 2016. Closing.
