### ISSUE TITLE
One GitHub account can have two RGSoC users associated with it

### ISSUE THREAD

**Issue by ankonym** [rails-girls-summer-of-code/rgsoc-teams#223]
We noticed an issue while setting up our team for the RGSoC application that seems like a bug, assuming that there should only be one RGSoC user per GitHub account:

We ended up with two users in the teams app that had different user IDs, but they both pointed to the same GitHub account. 

One of them was "Anni00" (https://teams.railsgirlssummerofcode.org/users/241), the other "anni00" (https://teams.railsgirlssummerofcode.org/users/262). 

While preparing the application, this led to some confusion because the application app was pulling the information from "anni00" while she was entering her information logged in as "Anni00". Removing user 262 from the team then allowed us to set up user 241 as a team member so that the information would be pulled from the correct account. 

(I'm not entirely sure if these were exactly the steps we took to end up in this situation, but I believe it was as follows:
She signed in with GitHub, which created user 241. 
I entered "anni00" into the form in the teams app, which created user 262.)

**Comment by carpodaster** [comment]
Hello @ankonym – thanks for reporting this. That's a bug, the Github handle should be unique and its check for uniqueness mustn't be case-sensitive.

**Comment by carpodaster** [comment]
Hi @ankonym – I've deployed a fix and the error you described shouldn't cause anyone any pain anymore. Thanks for reporting it! :beetle:   Also, I've deleted the empty user record for `anni00` (ID 262)
