### ISSUE TITLE
Filter the community and teams' list

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#224]
It should only display accepted teams after the acceptance letters have been sent

**Comment by carpodaster** [comment]
Needs doing: updating all the teams as being accepted (radio button 'voluntary' / 'sponsored') in the team's edit view. BUG: the value doesn't get saved in the DB, probably a strong parameters bug

**Comment by sareg0** [comment]
Hey, 
I have update all the teams except for two.

The following two will error though because the mentor is a team member on another team

https://teams.railsgirlssummerofcode.org/teams/18
https://teams.railsgirlssummerofcode.org/teams/28

**Comment by carpodaster** [comment]
@sareg0 there is a bug that causes the value of the radio button `kind` to be ignored and so I am afraid none of your updates have been persisted :( 

I have just pushed the fix and it should be deployed momentarily. The commits include a new organizer-scoped teams controller https://teams.railsgirlssummerofcode.org/orga/teams where you should be able to update the team's state. Can I ask you (or somebody else) to flag all the accepted teams for this year _again_ ?

**Comment by sareg0** [comment]
oh, that's a shame
Not a big deal though.  I will go through again.

**Comment by sareg0** [comment]
@carpodaster it looks like the radio buttons for 'sponsored' and 'volunteer' are no longer there?

**Comment by carpodaster** [comment]
hey @sareg0 - it's no longer there for /teams, make sure you are on /orga/teams, that is: https://teams.railsgirlssummerofcode.org/orga/teams

**Comment by sareg0** [comment]
thanks for this @carpodaster and also to @alicetragedy for taking over and gettin' it done :)
