### ISSUE TITLE
Create bogus test data for local development

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#225]

**Comment by alicetragedy** [comment]
+1 on this – it would be amazing, especially when it comes to the application process, and it would make it so much easier for everyone to contribute. yayy! :+1:

**Comment by sareg0** [comment]
totes, it's a problem we had in trying to mess about with stuff

**Comment by carpodaster** [comment]
Switched assignee as @F3PiX is already hard at work on this.

Maud, if you want to go an extra mile, you can make FactoryGirl work in development (currently only loaded for the test env) and use the defined factories in `seed.rb`.

The good thing: the defined factories are tested, the contents in `seed.rb` are not. Should our schema change or validations be added, logic `seeds.rb` is likely to break first. Factories are adapted more frequently.

**Comment by F3PiX** [comment]
O that sounds interesting. I will look into that. 
(The seeding I am doing now is basically to get a feel for the app.)

**Comment by F3PiX** [comment]
What seeds do we need most?
[ ] Filled in application forms
[ ] Teams (we do have user seeds, but they are not yet in teams)
[ ] ?

**Comment by alicetragedy** [comment]
@F3PiX maybe filled in projects as well (the application process now involves selecting an approved project from a dropdown menu, so one or two projects should be available).

**Comment by carpodaster** [comment]
@alicetragedy @F3PiX all of the above :wink: 

* An unaccepted team
* An accepted team
* A accepted, but voluntary team
* An application draft, unsubmitted
* An application draft, completed
* A  `proposed` project
* An `accepted` project
* A `rejected` project

**Comment by F3PiX** [comment]
:sparkles: Thnx

**Comment by alicetragedy** [comment]
Would be great to have this in time for the start of the program this year, so that if there is a team working on the teams app, they can get set up more easily.

**Comment by carpodaster** [comment]
Hello @F3PiX – are you still working on this or do you have a branch that someone else can continue working on? The SoC starts in approx. two weeks and it would be nice to make the setup of a local teams app installation as easy as possible

**Comment by carpodaster** [comment]
Done thanks to the amazing work of @F3PiX !
