### ISSUE TITLE
Hidden teams can not be seen by organizers

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#228]
In the teams overview, the teams that have decided to remain hidden are not shown to organizers either.
I think this is a 'conceptual' issue: do we want teams applying and ticking the 'hidden' check box to be visible to organisers anyway?

**Comment by sareg0** [comment]
I think that we want to be able to still see all teams as organizers, even if that is a 'super' role, that only a select few have, to protect their privacy. I would love to see all the teams, even if they want to be hidden to the wider userbase of the app.

**Comment by carpodaster** [comment]
hey @alicetragedy and @sareg0 – please check the new https://teams.railsgirlssummerofcode.org/orga/teams endpoint to get all the orga-access-level info for teams. You can see all teams there, invisible or not.
