### ISSUE TITLE
Investigate: "source" record got added to several teams by accident

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#231]
This is re: #230 – check where the invalid source records come from

**Comment by alicetragedy** [comment]
@carpodaster in this respect – do you want me to revert the commits made in that pull request, since it was just a one-time need to update the teams? Or should we leave it like that for now?

**Comment by carpodaster** [comment]
@alicetragedy yes, that'd be great

**Comment by carpodaster** [comment]
Hi @alicetragedy, I reverted 26a69ff. Also, I couldn't reproduce a way to get the sources into the database without passing a url value (ie. bypassing its validation).

However, removing the misbehaving `Source` record via the team's edit page should repair a stale team.

**Comment by carpodaster** [comment]
I removed 8 stale `Source` records from the DB.

Let's keep our eyes open for when this error occurs again and let's hope that we'll have a means to reproduce it then.
