### ISSUE TITLE
test 'checked up on them' feature

### ISSUE THREAD

**Issue by sareg0** [rails-girls-summer-of-code/rgsoc-teams#233]
This is just to remind us that we need to check/test this feature of the teams app.

- does it still work?
- does anything need changing?
- can it be made clearer.

Assigning to @alicetragedy first, as she has experience as a supervisor.

**Comment by alicetragedy** [comment]
Status: A couple of changes with the mailing need doing (https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/238) and pull request submitted for the UI clean-up (https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/242).

**Comment by alicetragedy** [comment]
I think we can close this! :tada:

**Comment by sareg0** [comment]
okay, let's close it then
