### ISSUE TITLE
Checked up on them: comment can also be left by orgas

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#237]
If I'm not mistaken, the checked up on them feature should be for the supervisor of a team only – meaning no one from the organisers team should have access to the form (or at least, should not be able to leave a comment). Is that the idea?
I tested the feature yesterday and it seems I could (as an organiser) comment on any team/check up on them. Is that something that needs changing before kick-off? 
@carpodaster do you have any thoughts?

**Comment by carpodaster** [comment]
@alicetragedy Orgas assume the role of admins on the teams app so they "overrule" the restrictions. We can change that, but would it not be enough to just leave the text input be as an orga person when they are not supervising a given team?

**Comment by alicetragedy** [comment]
@carpodaster yep, that's totally fine. wasn't sure if that was meant to be so or not. let's let it be – no need to complicate our lives changing the overriding of the restrictions. I'll close this issue!
