### ISSUE TITLE
/teams/info shows error page  

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#252]
Clicking on the "Teams organizers info" link (in /teams):
![screen shot 2015-07-07 at 23 30 24](https://cloud.githubusercontent.com/assets/1711357/8557843/36d03bca-2500-11e5-95b8-287dfc4380f9.png)

gives this: 
![screen shot 2015-07-07 at 23 26 48](https://cloud.githubusercontent.com/assets/1711357/8557818/106b67a2-2500-11e5-95cb-83b0f7cbfddd.png)

**Comment by alicetragedy** [comment]
I can take a look at that in the afternoon/evening and see what the deal is – unless someone else has time before that :)

**Comment by carpodaster** [comment]
@alicetragedy I bounced an exception message to your email inbox. I think that's the one that's related to this issue here

**Comment by alicetragedy** [comment]
@carpodaster Tusen takk (as they say in Norway). Will take a lookie later! :tada:

**Comment by alicetragedy** [comment]
I think we can close this issue – I feel like there are a couple of things that can still be fixed on that page, but we can see how to optimize it later ;)
