### ISSUE TITLE
/orga/teams shows all teams, not just the selected ones 

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#253]
Would be really helpful if we could have the same filter we have for /teams here, since it gets kinda chaotic with ALL teams ever created being shown here. 

@carpodaster you tweaked the /teams site so that only selected teams are shown, right? could you do some :sparkles: magic and do it for this site as well?

**Comment by ramonh** [comment]
I'm on it!

**Comment by carpodaster** [comment]
@ramonh cool! :smile: 

Could you add a predefined filter to also display all teams? Otherwise not even the orga is able to look into team data of unaccepted teams once the SoC has started.

**Comment by carpodaster** [comment]
@ramonh Are you still working on this? If not, want someone to take over?

**Comment by ramonh** [comment]
Woops! Completely forgot I had pledged to do this. Sorry, but thank you for the reminder! I'll go ahead and do it if that's cool

**Comment by carpodaster** [comment]
Yeah sure, and no hurry! I was just going through some of the issues and see if they can be closed

**Comment by ramonh** [comment]
Sounds good, thank you!

**Comment by alicetragedy** [comment]
@ramonh can we still have you on this task? I don't expect this to be an issue again until the beginning of the program starts, but it would be awesome to have by then. :)

**Comment by ramonh** [comment]
Whoa, I have no idea how this completely went past twice! Sorry about this. I'd be happy to take care of it. This time for realz. :sweat_smile:

**Comment by alicetragedy** [comment]
haha, no worries @ramonh. I believe it wasn't completely urgent, even though I can foresee problems/annoyances if we start to see teams from last year (selected and non) in our orga teams view. :joy:

**Comment by ramonh** [comment]
Thanks for understanding. That makes sense to me. I'll start looking into it this week. 

Thanks again for the reminder, @alicetragedy! I must say this is the first time I have embarrassing evidence staring me in the face. :laughing:

**Comment by F3PiX** [comment]
@anikalindtner This is solved it, isn't it? Shall we close?

**Comment by anikalindtner** [comment]
@F3PiX sure! <3
