### ISSUE TITLE
Contributor JSON should only show orga + members of accepted teams, no?

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#254]
It currently also shows coaches and mentors of teams that couldn't be accepted. Do we want to filter?

Ping @sareg0 @anikalindtner @alicetragedy

**Comment by alicetragedy** [comment]
I have to +1 with you on this one :+1:

**Comment by anikalindtner** [comment]
yay for filtering them out!

**Comment by sareg0** [comment]
This is in the process of being fixed. Pull request submitted, but not ready for merge til test is written
