### ISSUE TITLE
Feature Request: Add links to team-specific Atom-feeds

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#255]
The activity log's feed url https://teams.railsgirlssummerofcode.org/activities.atom can be filtered by appending `?team_id=<ID>`. Everything works, it just has to be made visible.

* Add a Atom-feed icon to the activity listing on teams#show
* Add a Atom-feed icon to the activity listing on status_updates#show
* Add a `<link rel="alternate" type="application/atom+xml" title="Atom Feed" ... >` element to the header section on status_updates#show

@F3PiX + @roosdebildt: this is a motivational one (ie. quick results) :wink:

**Comment by alicetragedy** [comment]
:+1:

**Comment by F3PiX** [comment]
A few days ago I already looked into it, because I added the feed to our Slack but it didn;t show updates.  I fed the feed into a feed validator and got all kind of trouble :-)
And then I stopped. :checkered_flag: 
http://feedvalidator.org/check.cgi?url=https%3A%2F%2Fteams.railsgirlssummerofcode.org%2Factivities.atom%3Fteam_id%3D38 
We'll have to look into that together, maybe Roos knows.

**Comment by carpodaster** [comment]
@F3PiX Oh. In that case it would be good to get the feed pass validation first :wink: I recommend using [the W3C validator](http://validator.w3.org/feed/), though; it allows uploading of text as opposed to referencing a website. It makes development much easier (since your localhost cannot be reached by the W3C validator machine).

**Comment by roosdebildt** [comment]
@carpodaster:
> "Add a <link rel="alternate" type="application/atom+xml" title="Atom Feed" ... > element to the header section on status_updates#show"

1. I'm presuming you mean the <head> section and not the <header>?
2. The head (and the header for that matter) are only specified generally for the whole app in layouts>applicatoin.html.slim. Do you want us to put it there?

**Comment by carpodaster** [comment]
@roosdebildt yes, the `<head>` section. The application layout file has a `yield :head if content_for?(:head)` call in line 12. You can read up on `content_for` to inject content from a sub-template into that layout file. That way it's possible to have it in `<head>`, but only on that specific page.

**Comment by roosdebildt** [comment]
@carpodaster you make new worlds open up to us every day ^^

**Comment by F3PiX** [comment]
@carpodaster What Roos said :-) 
About the second part: adding ...to status_updates#show. Does it mean you want here the activities minus the feed entries = status_updates? (For a specific team). 
Wouldn't it be nice for a team if ALL their entries were in the Atom Feed (e.g to add it to their slack channel)?

**Comment by The-Compiler** [comment]
Whoa, awesome! :sparkles: 

Planned to open an issue asking for this today, and suddenly I notice it's there :laughing:
