### ISSUE TITLE
Improve activities feed view

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#259]
Since some posts have eg. images, it would be great to improve the formatting of each post on the activities feed. 
For example:
- move time and poster information under the title
- show body of the post under the avatar (instead of starting mid-avatar like it is now) which would also fix the problem of the bullet points in a list being "stuck" to the team avatars
- "resize" images so they fit the width of the box the single updates are in

I think it should be quite an easy task, but I'm happy to take it on if nobody will ;)

**Comment by roosdebildt** [comment]
me, me, me, me! prettyplease :)?

**Comment by alicetragedy** [comment]
@roosdebildt hehe, I knew it! actually opened the issue with you in mind ;)

**Comment by roosdebildt** [comment]
almost done :)
<img width="1058" alt="screen shot 2015-07-12 at 17 28 43" src="https://cloud.githubusercontent.com/assets/11146524/8638439/9103a7bc-28bb-11e5-9659-87de55a7162e.png">

few questions for the coaches tomorrow and then I'll do a PR!

**Comment by roosdebildt** [comment]
@alicetragedy and @carpodaster almost done!

Screenshot with some random pictures in the post:
<img width="1058" alt="screen shot 2015-07-12 at 17 28 43" src="https://cloud.githubusercontent.com/assets/11146524/8638463/5040874e-28bc-11e5-8072-fa8b9dd9c0eb.png">

What do you think?

**Comment by carpodaster** [comment]
Looks great, @roosdebildt ! One question: Are the images resized / downscaled in activities#index? There are some rather big images included in some status updates and they kinda wreck the layout.

**Comment by roosdebildt** [comment]
yes, I took care of that too. I set a max-width and made them float left inside the content area. I'm drying up the code now so you can check it later :)

**Comment by alicetragedy** [comment]
Great work @roosdebildt, I think we can close this.

**Comment by F3PiX** [comment]
:+1:

**Comment by carpodaster** [comment]
It looks so pwetty! :bouquet:
