### ISSUE TITLE
Generate RSS feed for team logs

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#260]
So we do have the .json output for all the daily log activities ( for separate teams https://teams.railsgirlssummerofcode.org/activities.json?team_id=84 as well as all teams  https://teams.railsgirlssummerofcode.org/activities.json), but this is not a format RSS readers can use. 

We'd need to convert that somehow. This is something that came up not only in the discussion with mentors who want to keep track of their teams, but also with students wanting to add the feed to their Slack orga.

**Comment by alicetragedy** [comment]
There is apparently already an atom feed, see #255

**Comment by anikalindtner** [comment]
WOHA!! Awesome! Adding it to slack worked for now <3 
I think we can close this then actually :D

**Comment by alicetragedy** [comment]
:+1:
