### ISSUE TITLE
Link from blog to Activities on teams-site

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#265]
If people read the blog, there seems to be no easy way to jump to the Activities stream. Can we add a link on summerofcode.org to the teams.summerofcode.org? 
Like a navbar-item, or a banner?

**Comment by carpodaster** [comment]
Hey @F3PiX, could you create that on the [summer-of-code repo](https://github.com/rails-girls-summer-of-code/summer-of-code/issues)? Thanks! Closing.
