### ISSUE TITLE
General styling & CSS enhancements

### ISSUE THREAD

**Issue by roosdebildt** [rails-girls-summer-of-code/rgsoc-teams#266]
General styling improvements to make the teams app look nicer and more in style with //railsgirls.com/.

- improving style & views
- refactoring CSS
- dividing specific styles per pages into separate stylesheets (f.e. activity page, community etc.)
- making the app more responsive

**Comment by alicetragedy** [comment]
:+1:

**Comment by F3PiX** [comment]
We have responsive!!!!!!! Thanks to @roosdebildt's magic. Can we close this? How about the separate styleheets?
