### ISSUE TITLE
Supervising area (team profile page) layout error

### ISSUE THREAD

**Issue by idengager** [rails-girls-summer-of-code/rgsoc-teams#267]
So I put in a long long comment together with the first checkup for my team ([Rubyherzlein](https://teams.railsgirlssummerofcode.org/teams/9)) and this happened:
![screen shot 2015-07-13 at 12 07 34](https://cloud.githubusercontent.com/assets/2712383/8647459/628c2eb6-2958-11e5-91a9-35039852a59b.png)

I wouldn't mind it as such, but the comment covers the `Checked up on them button` so that it can't be clicked. Because this is just a layout issue I was able to work around it by just hiding the `information` element, but, well, this isn't sustainable.

**Comment by alicetragedy** [comment]
@idengager thanks for opening the issue! I actually noticed this on the weekend as well and was planning to fix it ;) I'll get that done sometime this week – hopefully sooner rather than later!

**Comment by sareg0** [comment]
ps I'm looking into this

**Comment by F3PiX** [comment]
@sareg0 We will be working on the supervisor dashboard from Wednesday on. Just saying... (but you know how fast we are, so if it needs a quick fix ;-)... )

**Comment by sareg0** [comment]
believe you me, this is a Quick fix (not the capital Q ;) ), and the supervisor's dashboard needs an overhaul anyway. This fix is just a stopgap, so feel free to chuck it out when you get to the dashboard. It's just so it's not so annoying right now @F3PiX

**Comment by sareg0** [comment]
Pull request now lodged

**Comment by alicetragedy** [comment]
closed via https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/291

**Comment by F3PiX** [comment]
We will do our best to make it a wonderfull dashboard for all SUPERvisors :-)
