### ISSUE TITLE
Easy access to New Status Update Button for students

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#274]
Very selfish issue :-)
As students, we have a growing list of Status Updates in students\status_updates. The New-button is at the end of the list, while it is the main reason to visit the page.  
I was thinking that there are better ways to grant easier access to the button.
E.g. give it a more prominent place above the listing, or even move the new_status_update_form to (the top at) this page and kill the button. 
Wdyt?

Ping @roosdebildt

**Comment by alicetragedy** [comment]
@F3PiX I completely agree – see comments in https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/268 ;)

**Comment by carpodaster** [comment]
Closed in #300
