### ISSUE TITLE
Status Update: Minor visual improvements

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#276]
As mentioned in this pull request (https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/268), there are definitely some minor improvements that could be made to the `status_update`, to make it more user-friendly. Here are a couple of things I noticed need work:

- on the `status_updates` new view, the buttons "Create Activity" and "Back" should be aligned. Ideally, "Create" Activity could even have a color (like green) to show that it's the 'positive' action.
- the table on the index view is pretty ugly, and the date as well as title columns are pretty narrow in comparison to the text column. 

This issue is also linked to https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/274

**Comment by F3PiX** [comment]
@alicetragedy @roosdebildt Can we close this, or do we need even better styling?

**Comment by lucaspinto** [comment]
Hey @alicetragedy, what's the status here? Is there an easy way to test it?

**Comment by alicetragedy** [comment]
update: the table / index looks acceptable. the styling can always be improved later on but I'd vote on closing this :)
