### ISSUE TITLE
Status Update: Footer is displaced

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#277]
the show view for a `status_update` does something funny if the text is too long, see image below.

![screen shot 2015-07-13 at 22 19 52](https://cloud.githubusercontent.com/assets/3143348/8761554/18e46460-2d57-11e5-921d-e9badb2ea324.png)

**Comment by F3PiX** [comment]
@roosdebildt  this is fixed, right?

**Comment by lucaspinto** [comment]
Hey @alicetragedy, what's the status here? Is there an easy way to test it?

**Comment by alicetragedy** [comment]
this particular problem is fixed. closing :+1:
