### ISSUE TITLE
Mailings doesn't show errors / doesn't sent emails

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#286]
In the last mailings (after you added the selected/everyone feature to it @sareg0 and @marcgreenstock ) there have been some issues with students not getting the emails.

I don't know why this happens, since all the other ones got them and they are on the receivers-list, but the app doesn't show any errors anymore (and also not the time stamp when the email was sent), so there is no way for me to see why that is. 

This was how it looked before:

![screen shot 2015-07-21 at 10 39 18](https://cloud.githubusercontent.com/assets/1711357/8796449/2bdb6f9c-2f95-11e5-8817-bf3d36233ccd.png)

Which was very helpful. Now the fields are empty after sending (even though the email DID get sent to most of the students): 

![screen shot 2015-07-21 at 10 39 39](https://cloud.githubusercontent.com/assets/1711357/8796456/397d8d06-2f95-11e5-921b-158ba33ed858.png)

The two students who didn't get an email this and last times are Maud and Roos. Maybe we could look in the database what happened with their emails and see if there were errors?

**Comment by anikalindtner** [comment]
after I resend the email to Maud and Roos they got their email now.

**Comment by roosdebildt** [comment]
The app doesn't like cheese :disappointed:

**Comment by anikalindtner** [comment]
Also: the sender address is "wrong". should be summer-of-code@railsgirls.com, not summer-of-code-team. 

![screen shot 2015-07-21 at 11 18 47](https://cloud.githubusercontent.com/assets/1711357/8797233/5e3aaf2a-2f9a-11e5-869c-0943bfda0b66.png)

**Comment by carpodaster** [comment]
> Also: the sender address is "wrong". should be summer-of-code@railsgirls.com, not summer-of-code-team. 

I've noticed that but the configuration for sending email uses that email address as a username to authenticate against Google Mail. If you can send me the password for the desired email address (via email or Slack or homing pidgin), I can change it.

**Comment by marcgreenstock** [comment]
Opps, sorry about this, do you want me to take a look at it?

**Comment by anikalindtner** [comment]
@marcgreenstock yes please! @carpodaster i'll have a look for that password!

**Comment by marcgreenstock** [comment]
This should address the problem: https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/296

Sorry for the delay

**Comment by sareg0** [comment]
I am closing this, but if it persists then please re-open @anikalindtner
