### ISSUE TITLE
Mailings doesn't save everyone/selected teams/ unselected teams setting 

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#287]
Every time that I wanted to sent an email to just "selected teams" (and not "everyone", which seems to be the default) and I edited the Mailing but not sent it straight away, the app forgets the box that I selected and selects "everyone" again. 

For the Students/Organizers/Mentors boxes it works though and shows the right box even when I had to go back and edit the mailing:

![screen shot 2015-07-21 at 11 24 53](https://cloud.githubusercontent.com/assets/1711357/8797350/24e2a61e-2f9b-11e5-9197-6c9d7edf2bab.png)

pinging @marcgreenstock and @sareg0

**Comment by sareg0** [comment]
hey @marcgreenstock we looked at this this morning. I'm assigning it to you for a fix.

**Comment by sareg0** [comment]
hey @marcgreenstock we need to use this feature for a mailing today. Do you think you could fix it today by close of business, or should we find another method to do our mailing?

**Comment by carpodaster** [comment]
@sareg0 This is fixed, yes?

**Comment by marcgreenstock** [comment]
@carpodaster I believe this was fixed in https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/298. I haven't heard anything more about it so I consider that a success.

**Comment by sareg0** [comment]
Ah! I haven't experienced anything else bad with the mailings thus far... So I have my hopes up that it worked. I will close this up.
Thank you @marcgreenstock and @carpodaster for helping us push this fix through :)
