### ISSUE TITLE
Checked-up-on-them comments aren't sorted by date

### ISSUE THREAD

**Issue by cypher** [rails-girls-summer-of-code/rgsoc-teams#295]
The comments posted via the "Check up with Comment" form aren't displayed in reverse chronological order.

E.g., right now, for Team Tessie, the top-most comment is from July 18th, followed by one from July 10th, then July 15th, July 24th, and finally July 6th.

**Comment by alicetragedy** [comment]
:+1:

**Comment by F3PiX** [comment]
I'll fix this, no problem :-)
