### ISSUE TITLE
Separate list of confs for the 2nd raffle round 

### ISSUE THREAD

**Issue by katrin-k** [rails-girls-summer-of-code/rgsoc-teams#303]
On page http://teams.railsgirlssummerofcode.org/conferences: For the 2nd round of the conference raffle it would be cool to have a fresh/empty list of conferences while still keeping the results from the 1st round. 

Idea: Add a 2nd table on top of the page. The list from the 1st round is somewhere below that. Nice large headline for both :). Might require an additional attribute for the conferences à la "round: 1st round / round: 2nd round". 

Reason for keeping the list of the 1st round: transparency. So people can see again who won tickets in the 1st round.

**Comment by carpodaster** [comment]
@sareg0 + @ramonh: has this been done in #310 ?

**Comment by ramonh** [comment]
@carpodaster That's right! If you go to the Conferences page, you'll see a table for the second round conferences, as well as a link to show those of the first round.

Hope this makes sense!

**Comment by carpodaster** [comment]
Great, thanks!

**Comment by ramonh** [comment]
Sure thing!
