### ISSUE TITLE
"Submit your Project" (header nav) should be more prominet 

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#322]
Maybe a text link in the nav bar won't do. What about a big fat red circle somewhere?

**Comment by carpodaster** [comment]
This is what the header looks like. If there are any suggestions on how to make more prominent: feel free to add it to the remote branch (you can check out it out locally with `git checkout origin/feature/project-proposals` (if you have checked out the repo directly, otherwise it's probably `upstream` instead of `origin`)

![bildschirmfoto 2015-12-05 um 23 11 55](https://cloud.githubusercontent.com/assets/164400/11610529/a1cc35c0-9ba5-11e5-951d-fc9656ed662c.png)

**Comment by carpodaster** [comment]
Ping @alicetragedy ? :art:

**Comment by alicetragedy** [comment]
Just saw this @carpodaster – I'm happy to take a look at it today and see what I can come up with :)

**Comment by alicetragedy** [comment]
I think we can close this!
