### ISSUE TITLE
Add comment section to projects#show

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#325]

**Comment by carpodaster** [comment]
@ramonh would you have to tackle this one? I'm still working on the season logic of the project proposal :(

**Comment by ramonh** [comment]
Hey @carpodaster! I definitely can, but will be time constricted tomorrow (having a long day of flying tomorrow). By when do we need this?

**Comment by carpodaster** [comment]
In Wednesday's hangout we decided to start testing on Sunday afternoon.

**Comment by ramonh** [comment]
Ok, Hm. I'll be flying to Japan very early in the morning, so I don't think I'll manage this in time (or if I do I'll likely not have access to WiFi) :(



—
Ramón Huidobro



http://ramonhuidobro.com

**Comment by ramonh** [comment]
However, I can start tonight. @carpodaster you mentioned that I could use the `comment` model, correct?

**Comment by carpodaster** [comment]
Sorry, @ramonh - been in the train w/o internet. It's late now and probably too late to get started, even more so when you have a big voyage tomorrow (Japaaan!? Awesome :) ).

**Comment by ramonh** [comment]
No worries! I can relate. Thanks for understanding (Yee! I'm excited and nervous)
