### ISSUE TITLE
Create basic CRUD of project

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#327]
* Form fields see db/schema.rb
* current_user becomes Project#submitter
* Editing/updating the project for the submitter only

**Comment by ramonh** [comment]
Quick question, if I understood the first point correctly, I need to add missing fields to the `projects` table, correct?

**Comment by carpodaster** [comment]
Hey Ramon. The columns on the table `projects` have already been added. You can look them up in the `db/schema.rb` file. We need a form for these columns/attributes.

**Comment by ramonh** [comment]
Right! Gotcha. Thank you for clarifying @carpodaster! I'm on it

**Comment by carpodaster** [comment]
Cool! Thank @ramonh !

**Comment by carpodaster** [comment]
Oh btw, you can base your work on the remote branch `feature/project-proposals` and if you want to lodge a PR you can base it against that same branch.

**Comment by ramonh** [comment]
Awesome, thank you! I did eventually realize that that's where I should start :)

**Comment by ramonh** [comment]
I think it makes sense to actually delete the project, carrying over from #331

**Comment by carpodaster** [comment]
You're right. Let's just flush it :)

**Comment by ramonh** [comment]
Great! I'm glad you agree :) I just made #332 for it
