### ISSUE TITLE
Team pages of "internal" teams: link to Twitter lists

### ISSUE THREAD

**Issue by kerstin** [rails-girls-summer-of-code/rgsoc-teams#33]
Suggestion:

For these teams, replace the Twitter handle @railsgirlssoc on their team page with their corresponding Twitter list:

* [Team Helpdesk](http://teams.railsgirlssummerofcode.org/teams/16): railsgirlssoc -> railsgirlssoc/rgsoc13-helpdesk ([link](https://twitter.com/railsgirlssoc/rgsoc13-helpdesk))
* [Team Organizers](http://teams.railsgirlssummerofcode.org/teams/12): railsgirlssoc -> railsgirlssoc/rgsoc13-organizers ([link](https://twitter.com/railsgirlssoc/rgsoc13-organizers))

(There are more Twitter lists, but I saw there are no separate "team" pages for the mentors or coaches.)

**Comment by carpodaster** [comment]
(Related to the 2013 dataset, closing)
