### ISSUE TITLE
Improve header nav (mobile)

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#335]
The header nav on mobile definitely needs some :heart: (see screenshot, which is what happens when clicking on the burger menu)
This is a low-priority issue, but still worth noting. I might be able to take a look at this next week but if anyone else wants to jump on this issue, feel free to do so!

<img width="679" alt="screen shot 2015-12-06 at 14 10 19" src="https://cloud.githubusercontent.com/assets/3143348/11613502/9c4e7bac-9c23-11e5-8381-c31a5f81a88c.png">

**Comment by F3PiX** [comment]
Hi @alicetragedy ! I have the exact same problem in my current pet project. I surely want to take this one, if you think it is doable for me? And maybe you point me in the right direction?

**Comment by alicetragedy** [comment]
Hi @F3PiX! For sure, I've assigned you to it as I'm absolutely certain that it's doable for you :+1: I will not be online much in the next few days, but ping me if you're stuck and I will get back to you about it :)

**Comment by beanieboi** [comment]
did #358 fix the issue? i try to lean some CSS so i was looking at the issues tagged with "styling" :)

**Comment by alicetragedy** [comment]
oops! thanks for asking @beanieboi — #358 did indeed solve the problem so I'm going to close this now. :) feel free to ping me if you want to pair on something css-related with me! :sparkles:

**Comment by beanieboi** [comment]
@alicetragedy totally! would love to do that! i will look at some CSS issues and try to work on them and try to do as much as i can to learn. when i'm stuck, i'll ping you on slack so we can schedule something? does work for you? :sparkler:

**Comment by alicetragedy** [comment]
@beanieboi sounds perfect! 👯
