### ISSUE TITLE
Project Submission: error when commenting

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#338]
I can't seem to be able to comment on a project. This is independent from project state (I tried commenting on projects that are `accepted`, `rejected` and `pending`) and from project owner (I tried with projects that belong and do not belong to me, just in case). 
Current roles of testing user: `organizer`, `reviewer` and `supervisor`.

**Comment by carpodaster** [comment]
Updated staging, works now
