### ISSUE TITLE
Fix the nav.actions.ul.list-inline.li styling

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#343]
![bildschirmfoto 2015-12-06 um 22 06 34](https://cloud.githubusercontent.com/assets/164400/11615589/b3f465f4-9c65-11e5-9cbd-59227f5b9c6a.png)

See: 

- [x] teams#show
- [x] users#show
- [x] projects#show (currently in feature branch)
* ... (probably others as well)

**Comment by alicetragedy** [comment]
Absolutely. Was thinking about this earlier, and thought maybe we could move the "Signed in as" to the right (it feels more intuitive to me that way) and navigation-related stuff to the left.

**Comment by alicetragedy** [comment]
Note to self: don't close yet — I'll add the missing one from the feature branch once we've merged.

**Comment by alicetragedy** [comment]
project views have been updated as well, see 225914891941463489923bb91e4a68ff0e58eaa4
