### ISSUE TITLE
Project comments: no emails are sent. How do we avoid spammy conversations?

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#345]
Writing a notification opt-in / opt-out logic for a project proposal's commenting system seems overkill. But lots of comments can get spammy fast. How do we go about it?

**Comment by anikalindtner** [comment]
I think it's fine that they receive emails about it, after all it's their project and they should know about what's going on. Because if they *don't* get notified, nothing will ever happen.

**Comment by alicetragedy** [comment]
Cool, I like this approach @anikalindtner — it's true that if the students comment to say they want to apply to a particular project, it would be good if the mentor is notified.

**Comment by carpodaster** [comment]
:+1:

**Comment by carpodaster** [comment]
Notifications for submitter, mentor (if not the same person), and all commenters are now active.

**Comment by alicetragedy** [comment]
brilliant!! \o/
