### ISSUE TITLE
Editing/destroying a project as an organizer not owning it returns 404

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#347]
As an organiser, I can view the Edit/Destroy buttons on a project that doesn't belong to me (and hence, which I should not be able to delete/edit). See screenshot:

<img width="1239" alt="screen shot 2015-12-07 at 12 57 13" src="https://cloud.githubusercontent.com/assets/3143348/11626336/4444e436-9ce2-11e5-9ca6-c5330152996e.png">

The same happens with the icons in the projects index. Ideally, all these links should be hidden to the non-owner — since the non-owner anyway isn't allowed those actions.

**Comment by carpodaster** [comment]
This is actually a feature: An organizer has admin-powers and can do everything she wants. This is also in line with the Github proposal system where we can edit/delete issues at will, too.

**Comment by alicetragedy** [comment]
yes, but the problem is that it doesn't let me edit/delete – I get a "Page does not exist" error message

**Comment by carpodaster** [comment]
Ah! Ok, that's a bug then.

**Comment by carpodaster** [comment]
But do we agree on the fact that we as organizers should be allowed to delete/update things?

**Comment by alicetragedy** [comment]
I think so, at least deleting. :+1: and at that point, I reckon edit should be ok too

**Comment by alicetragedy** [comment]
#bugorfeature ;)
