### ISSUE TITLE
Redirect to /projects/new after signing up

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#348]
When I click on "submit your project" and am not logged in:

After people sign up for the teams app (or log in ) they should be redirected to /projects/new and not their profile page (that's how it is for now). This is confusing. But I remember that this is a teams-app thing. The app doesn't 'remember' where I wanted to go before I logged in. Would be great if we can change that.

**Comment by carpodaster** [comment]
I'm afraid this is a general issue and cannot be fixed easily since we don't "own" the login mechanism :disappointed:
