### ISSUE TITLE
Edit Sucess-text

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#349]
After submitting a project the submission text should read something like:

Thank you for submitting you project for Rails Girls Summer of Code 2016! We will review it in the next days and come back to you with questions or feedback.

If you have any problems or questions, email us at summer-of-code@railsgirls.com. 
Cheers!

**Comment by carpodaster** [comment]
You mean instead of the "Project was successfully submitted." flash message? Your proposed text might be a little too long for that, but we can introduce a "receipt" page.

This issue is up for grabs! :smiley_cat:

**Comment by alicetragedy** [comment]
Happy to take a look. Probably not today but early tomorrow :)

**Comment by carpodaster** [comment]
You can probably copy the `app/views/applications/create` view and adapt it. The `ProjectsController#create` action would have to be changed so that it doesn't redirect anymore.

To avoid hardcoded years, the year of season can be accessed  with `@project.season.year`

**Comment by alicetragedy** [comment]
Perfect, thank you for the hints @carpodaster. Haven't done much work on the Teams App so that definitely helps give me a head start. :+1:

**Comment by alicetragedy** [comment]
the thank you page was added in 3be24371daefc5a39ac0f00b59f790b6fd02b6cd
closing this! :tada:
