### ISSUE TITLE
redesign and re-organize teams app

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#35]
heyhej,

here are some ideas i collected for the teams app:

make the user overview a little bit nicer: 
->give every participant a little box with infos like this:
![screen shot 2013-07-17 at 12 45 55 pm](https://f.cloud.github.com/assets/1711357/811249/1b60aa74-eece-11e2-947b-21b3ef818e26.png)

include a twitterstream, that shows the latest tweets from every team

on the team-site, rank the teams by activity, so that the team with the newest activity is first

make the date in "latest activity" a link that links to the latest blog post

add team pictures to the team overview

**Comment by carpodaster** [comment]
Hey @anikalindtner – is this still a thing?

**Comment by carpodaster** [comment]
I'm closing this. A redesign is certainly required but it's also a big project and probably ties into the rebranding, anyway.
