### ISSUE TITLE
Add disclaimer above the form

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#350]
To make sure, mentors have read our guide, I'd love to have a highlighted text (can be in a box or sth) above the form saying: "Please make sure you have read our mentor guide before you submit your Open Source project for Rails Girls Summer of Code 2016." And then have a link (opening in a new window) to our mentor guides.

**Comment by carpodaster** [comment]
Good point! Can you give me the link to the correct document to link to? Thanks!

**Comment by alicetragedy** [comment]
:+1:

**Comment by anikalindtner** [comment]
http://railsgirlssummerofcode.org/guide/projects/

**Comment by carpodaster** [comment]
It's on staging now. (I changed the "2016" to "upcoming" though)
