### ISSUE TITLE
Add a lock for comments

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#351]
When we want to close the projects or and signal that the students shouldn't get in contact with the mentor anymore via the comment section, we need to be able to close the comments.

**Comment by carpodaster** [comment]
Should the `rejected` state imply that the comments are locked?

**Comment by anikalindtner** [comment]
@carpodaster yes!

**Comment by carpodaster** [comment]
Comments can be locked/unlocked in the orga/projects overview (where you accept/reject them).

**Comment by alicetragedy** [comment]
:tada:
