### ISSUE TITLE
activities#index: image is too big for blog posts fetched through teams' RSS

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#357]
Activities published directly from the Teams App ("Minilog") are fine. However, updates being pulled from a teams' RSS feed will get a screenshot that's too big.

![bildschirmfoto 2015-12-10 um 21 34 05](https://cloud.githubusercontent.com/assets/164400/11728359/b0600a84-9f89-11e5-8fe8-375ed6c082d9.png)

**Comment by alicetragedy** [comment]
happy to take a look at this sometime next week.. unless you want to practice your CSS skills @carpodaster ;)

**Comment by carpodaster** [comment]
![Don't make me go that route!](http://2.bp.blogspot.com/-41v6n3Vaf5s/UeRN_XJ0keI/AAAAAAAAN2Y/YxIHhddGiaw/s1600/css.gif)

 :wink:

**Comment by alicetragedy** [comment]
that gif never gets old 😅

**Comment by alicetragedy** [comment]
fixed in 619da1bc433fc0f02ce894e2cbff2a861c9aecca 
it's an ugly fix, but it will do. YOLO!

**Comment by carpodaster** [comment]
Yess! Thanks, @alicetragedy !
