### ISSUE TITLE
Projects: accept/reject right from project view

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#359]
From a UX point of view, it would make sense to also have the accept/reject buttons in the single project view. When a project is submitted, I first look at the project description, maybe comment on the project and then decide if I want to accept or reject. It seems natural to also be able to do it from the `show` view itself, without having to go back to the project list. 
Any thoughts?

**Comment by carpodaster** [comment]
Do you mean links on `/projects` only visible to admins? That is kinda what I want to move away from as it means sprinkling the views with authorization logic.

**Comment by carpodaster** [comment]
Hey @alicetragedy, I would like to close this in favor of making the corresponding projects' view in the orga namespace more complete. D'accord?

**Comment by alicetragedy** [comment]
@carpodaster not a problem for me 👍
