### ISSUE TITLE
Change mentor sign-off to »mentor fav« (mentor pick)

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#364]
After the application phase is closed, present the mentors a list of applications referencing their project. They get to pick one team that they favor, maybe because the students have been in contact with them beforehand.

That mentor fav can serve as a soft boon during the review of the applications

**Comment by carpodaster** [comment]
This turns out to be a hard task and I'm not sure if it's worth the trouble. Major blockers:

1.  it’s really not that easy to make out relevant mentors anymore:  they need to be the `mentor_github_handle` on an accepted project of the current season AND there must be actual applications with any of their projects (being mentor for more than one project is possible) listed as either the preferred or secondary project by the applicants.
2. the logic to check if that’s a mentor fav also gets complicated by the fact that students have one application but two project options. Allowing only one mentor fav for per project_id scope will probably result in tons of custom validations that aren't easy to grasp next year (or maybe already in 4 weeks even)

I've got 1) nailed down alright but I won't have time to get to 2).

I'm strongly leaning towards ditching this feature alltogether. What do you think?

**Comment by carpodaster** [comment]
Unfinished business resides in the `feature/mentor-pick` branch

**Comment by F3PiX** [comment]
I probably don't oversee all implications, however, I see parallels to the supervisor dashboard.
Would it make sense to put the mentors behind a base controller, like the supervisors, and present them their own accepted projects, again like the supervisors. Where they can choose one fav.
If this^ makes sense at all, then maybe it is sufficient if only the view doesn't allow to pick more than one fav, with radio buttons. 
And if a team gets fav'ed by all their mentors, well, that is probably an indication that they are a potential candidate ;-)

**Comment by alicetragedy** [comment]
will this still be relevant for the 2017 edition? I know that we want to give mentors access to parts of the application answers, but we haven't discussed how to best have them suggest preferences. The email process last year was super messy, and I'd prefer not to repeat that... Is there any other way that would (easily) enable them to show a preference via the teams app?

**Comment by alicetragedy** [comment]
Some clarifications as per our call last week:
“Mentors can pick the teams they feel they are fit to work on the project and they can also fav a team or more than one team, depending on what we decide later.”

The idea was to have a mentor “sign-off” (team is fit to work on the project/have the requirements) and a mentor “fav” (I really like this team and would love to see them selected), with checkboxes for both (i.e. mentors can select as many as they want). 
Note: we should make the wording clear enough so that the mentors understand the difference between the two.

**Comment by carpodaster** [comment]
Gonna tackle this.
