### ISSUE TITLE
Application process: Remove requirement of coaches' comments

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#365]
Remove 'why successful' field.

Q: Allow students to fill in the »How much time are your coaches packin'?« question or shall we remove it alltogether?

**Comment by F3PiX** [comment]
From my experience, it is a) hard for students to foresee the availability of their coaches , and b) it is hear-say, so it is hard to compare between applications. On the other hand, it may be handy to ask the coaches directly how they see their commitment. We had very committed coaches, but came nevertheless coaching hours short, especially at times when some of the coaches were out of town.

**Comment by ramonh** [comment]
Tricky indeed. I wonder, would it perhaps be wise to advise coaches before confirming their involvement, perhaps in the form of a checkbox, that they need to be as available as possible? Perhaps this could resolve itself as we make coaches more involved in the overall communication this time around.

In any case, I'll happily handle the removal of this field.

**Comment by carpodaster** [comment]
Having meditated on this for a while now I'm in favor of leaving coaches out of the application process alltogether, save the fact that they have to accept being part of the team in the first place.

As @F3PiX pointed out, it's very difficult to estimate how much time will be available anyway so whatever is being entered may not be valid anymore come summer. Or could be fake in first place ;)

Very welcome side-effect: reducing another access level (i.e. 'coach') should also simplify the programming behind the application process.

**Comment by ramonh** [comment]
Sounds good! I'll go ahead and remove both fields, then.

**Comment by alicetragedy** [comment]
@carpodaster does this mean we are not entering any values that refer to the coaches' availability in the form at all? (fine with me, am just checking for guide update purposes)

**Comment by carpodaster** [comment]
@alicetragedy ah, good that you have The Guides™ in mind. Ooops.

The only bit of information we could us is their general level of support, e.g. having a "coaching company" or some office space. I don't think we explicitely ask for that, or do we?

So my proposal is as follows:

* Do not enable / require to edit the application draft anmore
* Remove "why will this team be successful?"
* Remove "how many hours per week?"
* Make sure that we gather information about their general support structure

**Comment by alicetragedy** [comment]
:+1: for removing ALL THE THINGS
when you write "Make sure that we gather information about their general support structure" do you mean that the coaches will be entering this somewhere? Or would you see this as the students' job? 
I believe this is info which the students/team could provide, if we really want to make the application non-editable by the coaches and have a hands-off approach (ie. we have the support of a coaching company/we have an office space in mind).
The only important thing would be to mention this in The Guides™ ("students will be entering information about your work set up, make sure that is discussed with them prior to the application is filled out" / "you will need to enter information about your work set up with your coaches; please make sure you discuss that with them prior to filling out the application")

**Comment by ramonh** [comment]
I like the sound of both of the above. I'll try and break this down into as many small tasks as possible, starting with the removal of the fields

**Comment by carpodaster** [comment]
> Or would you see this as the students' job? I believe this is info which the students/team could provide, if we really want to make the application non-editable by the coaches and have a hands-off approach

@alicetragedy Yes, I meant this as a students' job.  No coaches' mingling in the application draft form.

**Comment by carpodaster** [comment]
With #371 done and 258eff3d2174a4cb67e19acd513b5d7fb84dffa3, coaches can no longer access the draft. Done!

**Comment by ramonh** [comment]
Nice, thank you @carpodaster!
