### ISSUE TITLE
Application process: normalize location fields with Google auto-complete

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#366]
We request people to answer »Where do you plan to live July-September?« as _City, Country_ which doesn't work so well in all cases. Google provides an autocompleter for location data that could remove some of the randomness in the entered data.

**Comment by carpodaster** [comment]
If we add latitude / longitude fields to this we might even calculate the distance to a conference site. But this might be overdoing it?

**Comment by izuroxx** [comment]
hey @carpodaster ! I've been looking at this issue - can i try to do this?

**Comment by carpodaster** [comment]
Morning @izuroxx – but of course!

**Comment by mkalininait** [comment]
I've just looked at how it is implemented in the User Profile: there are two fields Country and City, the first is a dropdown and the latter is a simple input field. Does it mean that we will have different implementations of location input on the Application Form and in the User Profile?

Another thing to think about is the [Additional Info form](https://github.com/rails-girls-summer-of-code/selection_process/issues/35). We probably want to enter location the same way there (and even be filled out automatically), don't we?

**Comment by klappradla** [comment]
I'm taking a look at it. Feels kinda weird to write JS after such a long time 🙈 

Just one question: is there already a RGSoC project with a Google (Maps) API key @carpodaster ?

**Comment by carpodaster** [comment]
@klappradla I don't know of any Google Maps keys, no. Not in front of a computer right now, but maybe `heroku config` has something?

**Comment by klappradla** [comment]
Ah, good idea! Gonna look there.

I'm for now just playing around with the API. However, I guess it's not suggested to publish the API key in a repo *(especially given the fact that there are rate limits for the free plan)*. Still, this would again make the dev setup more complex 🙈

**Comment by F3PiX** [comment]
I think the advantages of autocomplete address input are well worth the extra dev setup. I am a big fan of this feature. 💃

**Comment by klappradla** [comment]
Hm, what I kinda don't like about it: you have to deliberately chose one of Google's suggestions. But ok, maybe that's what people are used to from using GoogleMaps anyways...

![autocomplete](https://cloud.githubusercontent.com/assets/3491815/21728760/28102f2a-d448-11e6-980e-dd3e467aa1db.gif)

**Comment by alicetragedy** [comment]
I'm definitely working on setting up an account that we can link to the API key, will get that done together with @klappradla once I've talked to Anika about this. Also, awesome work and thanksssss!!! ✨

**Comment by mkalininait** [comment]
Tested, looks good.

**Comment by klappradla** [comment]
Any news on the Google account @alicetragedy ? Or did you already change it?

**Comment by alicetragedy** [comment]
@klappradla thanks for pinging me about this. with everything else that was going on, I had decided to move setting up a google account for RGSoC until later. But if you think it's more wise to do that before we open up applications, I can still get that done today!

**Comment by klappradla** [comment]
No worries, fine to do it later. I cannot really estimate the load on the Google API. But I'll just verify my keys with my own creditcard - that will give us enough.

**Comment by alicetragedy** [comment]
Sure, I understand. If this is any problem at all I can still set it up later today though — just didn't seem like a huge priority compared to everything else. just ping me and I can take care of it. thank you Max!

**Comment by alicetragedy** [comment]
@klappradla the new Google account for RGSoC has been set up, what would be the next steps? do I have to create a new API key linked to that account, add our Foundation CC info, and update the environment variables? That's one of the few items left on the checklist to consolidate access to accounts: https://github.com/rails-girls-summer-of-code/organization/issues/179

**Comment by alicetragedy** [comment]
thank you!!!
