### ISSUE TITLE
Application process: define which fields should be hidden from the fellow student

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#368]
1) Financial info
2) …

Anything else?

**Comment by F3PiX** [comment]
Again, from my experience last year: there are no other fields that I would like to hide from my teamie. Based on last years form. 
Note: I can't remember it, but in the form it doesn't SAY that the financial info is hidden from the other student, it only mentions the coaches and mentor.

**Comment by F3PiX** [comment]
And for everybody who wants easy access to the form: we have a time travelling switch, which makes visiting the form easier. Go to http://localhost:3000/orga/seasons. Switch to the Application phase. 
After clicking Apply now, you have to add yourself to a team and then you can view and play with the form.

**Comment by alicetragedy** [comment]
thanks for the heads up @F3PiX! 
about the hidden info: maybe I'd also hide the "essay" they're planning to write, but I think that's about it.

**Comment by F3PiX** [comment]
Great, they have to write an essay? I would definitively want to share that with my teamie, so I don't see the need to hide that from eachother. 1) I would reckon: IF we write non-compatible opinions, that would hamper our chances to get in. 2) If we indeed HAVE uncompatible opinions, we better know that before than during summer.

**Comment by alicetragedy** [comment]
@F3PiX thanks for your input, it was really helpful.

**Comment by carpodaster** [comment]
@alicetragedy this is done, right?

**Comment by alicetragedy** [comment]
@carpodaster as of now, the financial info is visible to the other student — do we want to change that? other than that, yeah, technically, this would be done.

**Comment by carpodaster** [comment]
This is what it looks like for the pair now:

![bildschirmfoto 2016-03-14 um 12 04 09](https://cloud.githubusercontent.com/assets/164400/13742591/e3bc45f8-e9dc-11e5-8e77-61afa3b9226d.png)

**Comment by alicetragedy** [comment]
wheeee! :tada:
