### ISSUE TITLE
Hide conferences and status updates from navigation during application phase

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#385]
The conferences and status updates should not necessarily be visible during the application phase, as it would only confuse users imho. this is related to issue https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/380

**Comment by Nattivolk** [comment]
![issue385](https://cloud.githubusercontent.com/assets/1571562/13582173/0b6cc988-e4ab-11e5-985a-7e6a2f0f9c14.png)


Should it look like the picture? And we just hide the conference and last activity column for now?

**Comment by alicetragedy** [comment]
Hey @Nattivolk thank you for taking a look at this!
Sorry, I think my issue was not explicit enough — I wanted to remove / hide the "Status Updates" and "Conferences" menu points from the navigation only. It's okay if they are still shown in the teams list as columns, that's not such a big deal, but I think it's unnecessary as a menu point. 
Feel free to ping me more if you have questions :)

**Comment by alicetragedy** [comment]
Hi @Nattivolk, just checking up on you to see how far you are and if you need any help. It'd be great to have this on the weekend, as we're planning to open applications next week!

**Comment by alicetragedy** [comment]
fixed in https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/394 & https://github.com/rails-girls-summer-of-code/rgsoc-teams/commit/43962da942183b4218423b5bb3b7faba99a48fda <3
