### ISSUE TITLE
Cannot edit team github and twitter accounts 

### ISSUE THREAD

**Issue by anyangocynthia** [rails-girls-summer-of-code/rgsoc-teams#391]

**Comment by alicetragedy** [comment]
Hi @anyangocynthia, could you give us more information about this? What's the team id (or your user name, team name, or anything we can find the team by), and which steps did you go through that led up to this error? Are you getting any error message?

**Comment by anyangocynthia** [comment]
I had created a team profile last year but did not apply for RGSOC , I was editing the same team since i am applying this year . So the team profile had a different github organization and twitter accounts , once i press the edit team section , I get all the other options for editing the team members , name etc but not the github and twitter accounts . 

Unfortunately I destroyed that team and created another one .

There is no error message

**Comment by alicetragedy** [comment]
@anyangocynthia so, I just looked into it. This is not an error — the github and twitter account for the team can only be added after the team has been officially accepted. We don't expect students to provide that info before that. hope that helps!

**Comment by anyangocynthia** [comment]
Yes it does . Thanks!
