### ISSUE TITLE
Help page is no help at all

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#392]
https://teams.railsgirlssummerofcode.org/pages/help

**Comment by alicetragedy** [comment]
![post-124-0-24949000-1317876733](https://cloud.githubusercontent.com/assets/3143348/13649033/ea41debe-e63b-11e5-9af0-97b182be3899.gif)

**Comment by carpodaster** [comment]
Ok, »no help« is a bit too harsh ;)

We should remove everything that's likely to change and keep it to the bare minimum on how to use the site. And where to get further assistence.

**Comment by alicetragedy** [comment]
I'm happy to take this on if no one volunteers, but I think it's also a nice issue for newcomers, so I'd love to see if maybe @Nattivolk or Vi are interested in doing this.

**Comment by Nattivolk** [comment]
I can do this today after work. I'm just not sure, what is likely to change. 
Will write a draft and then it would be nice to get some feedback first. Are there some questions which come frequently and we should have answered there additionally?

**Comment by alicetragedy** [comment]
Hey @Nattivolk, great, thanks for jumping on this one :)
We get a lot of questions that are often team-specific (and which, in theory, are often answered in the guides..) so I wouldn't turn the Help page into a FAQ. 
But info regarding filling out the information about the teams might be good. I will take a look at what we might need exactly in the afternoon and post it here.

**Comment by alicetragedy** [comment]
one thing that comes to mind: information that needs to be filled out is dependent on the stage the application is in (and on whether the team has been accepted or not) ie. I think ( @carpodaster please correct me if I'm wrong) teams cannot fill out their team github handle and team twitter account and, possibly, team info, until the application has been sent off and they've been selected. 
This info, for example, might be important.

**Comment by carpodaster** [comment]
@alicetragedy I haven't digged through the code base to check whether or not editing their social accounts is possible. I don't remember having coded it, but maybe it was already there.

The help page is of more help now thanks to @Nattivolk and #395.

**Comment by alicetragedy** [comment]
@carpodaster just noticed it because we got a question about this from an applicant :) 
I just double-checked and the github/twitter stuff for teams can be edited under the `if f.object.accepted?` condition, so updated the help page accordingly. :+1:
