### ISSUE TITLE
List projects

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#397]
* [x] A link to `/projects` (projects#index) should be displayed during the application phase
* [x] Projects should list how many applications (1st and 2nd choice) already reference them

**Comment by michaelem** [comment]
I'll take a stab at this tonight.

**Comment by carpodaster** [comment]
Cool, thank you @michaelem. I forgot to mention: please base your work on the `application-process-2016` remote branch. Only that branch has the foreign keys `project1_id` and `project2_id` (or some such) on `ApplicationDraft`.

**Comment by carpodaster** [comment]
@michaelem I've merged the current state of `application-process-2016` into `master` just now. I plan to keep the feature/integration branch, though: it's set to auto-deploy to staging so it's probably still better to base everything against `application-process-2016`

**Comment by michaelem** [comment]
Ok, I'll use application-process-2016 then!

**Comment by carpodaster** [comment]
This is done, thanks @michaelem
