### ISSUE TITLE
Attendance must be "seasoned"

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#399]
The `Attendance` (conference feature) does not yet have a reference to the `Season` it is valid for.

**Comment by F3PiX** [comment]
Is this still needed? Or do we go with the current way of 'showing the conferences during the active season'?

**Comment by carpodaster** [comment]
I think we can close this – at least for now. Conferences are seasoned and by that, the season of an attendance can easily be infered.
