### ISSUE TITLE
Application process: Check validations for new (and removed) fields

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#402]
As discussed on Slack: there is a validation context called `:apply`.

**Comment by ramonh** [comment]
The above PR took care of the `:working_together` and `:why_selected_project` fields, which I found were new and untested in the schema. @carpodaster or @alicetragedy do you know which ones I might be missing? I went over them but didn't find any missing ones

**Comment by alicetragedy** [comment]
@ramonh if this also takes into account application fields that are part of the student model, you can find all the added ones here: https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/390/files
(check the `application_drafts_controller.rb`, the fields that have been added in the `params[:student]` bit)
hope that helps :)

**Comment by ramonh** [comment]
Ah super, thank you @alicetragedy! I'll look into that.

**Comment by ramonh** [comment]
Hey @alicetragedy! Just dug into it, and I think these are already validated. They were added to the required fields for students [here](https://github.com/rails-girls-summer-of-code/rgsoc-teams/blob/application-process-2016/app/models/student.rb#L8), which are then validated and tested by the `ApplicationDraft`s [here](https://github.com/rails-girls-summer-of-code/rgsoc-teams/blob/application-process-2016/app/models/application_draft.rb#L7) and [here](https://github.com/rails-girls-summer-of-code/rgsoc-teams/blob/application-process-2016/spec/models/application_draft_spec.rb#L127), respectively.

I think that's therefore already resolved!

**Comment by alicetragedy** [comment]
you're right — then I guess the issue can be closed, right? :)

**Comment by ramonh** [comment]
I think so, yes!
