### ISSUE TITLE
Change deadline for submitting the applications

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#405]
Before deploying to production, we should change the deadline for submitting the applications. According to our timeline, if we open applications on Monday, we will close on April 10th — suggested time 17:59:59 UTC?

**Comment by carpodaster** [comment]
I've modified the form for `/orga/seasons` in 793653728040ba280cf13dfb8c5769b2fe8f8142 and updated the deadline for the 2016 season. Feel free to edit the deadlines.

Note: It's not available on staging … yet.
