### ISSUE TITLE
UI: Rework Error Message 

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#408]
The error messages should not be a huge text field as it is now, but just show how many errors you have and where. All error messages should be shown directly in the fields where the error accurs (this is already the case for *some* errors). 

### My proposal: 

+ [ ] all errors need to be shown directly in the field where the error occurs 
+ [ ] error messages should tell you **where**, that means **in which tab the info is missing**. This can be either:
  + in the summary:
" 
### About yourself 
error message
### About your project 
error message
"

  + or shown in the tabs directly (e.g. by having a red border around the ones who have error messages, so you know where to look)
![screen shot 2016-03-13 at 20 00 28](https://cloud.githubusercontent.com/assets/1711357/13730690/5a801944-e956-11e5-94af-3a291be85c0a.png)

### MUST FIX::

+ [x] "4 errors to go before you can apply:" <- this is invisible (red on red).

### NICE TO HAVE

+ [x] change black on red writing to black on white writing and add only red border / or change font to red on white without a border.

**Comment by michaelem** [comment]
I'm probably at least touching these while fixing #202.

**Comment by anikalindtner** [comment]
@michaelem awesome! so for now we'll wait until you are finished and then see what's left, right?

**Comment by michaelem** [comment]
yepp, since everything else probably will end in merge-conflict hell :see_no_evil:

**Comment by alicetragedy** [comment]
The thing with the fields (first on the list) is still a bit tricky, but we're looking into a fix. :see_no_evil:
