### ISSUE TITLE
Update Application info in edit profile

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#412]
I noticed earlier today that there is a mismatch between the fields in the application form fields in the edit profile page, and the ones in the application. I am in the process of getting it fixed! :muscle:

**Comment by carpodaster** [comment]
@alicetragedy this is done now that PR #416 has been merged, right?

**Comment by alicetragedy** [comment]
yes @carpodaster! :+1:
