### ISSUE TITLE
Information pulled from github should not be editable/deleted

### ISSUE THREAD

**Issue by Nattivolk** [rails-girls-summer-of-code/rgsoc-teams#413]
- [ ] github handle and email have a star i guess for indicating a mandatory field, but i can save without an email address. This happend, because I deleted the email. Might happen, if a candidate wants a different email, deletes it and then forgets to add the new one. 
- [x] I'm not sure, if this is wanted, but I can also change the github handle. As I signed in with a specific account I don't know if we want to allow to change this field?
  Same here, I just edited the github account to a different one and could save the application

Possible fix: Github handle used for sign up should not be editable and email should be verified.

**Comment by carpodaster** [comment]
Hey @Nattivolk - thanks!

The reason behind 1) is that a `User` record is indeed created w/o an email address at first: the rest gets pull from the GH API asynchronously. We should improve that, though. A validation context should fix that: the easy win would be to allow a `User` to _created_ w/o an email address, just not _updated_

2) Making the GH-handle of a created `User` immutable is sounds like a really good idea!

**Comment by izuroxx** [comment]
hi @carpodaster! is this what you have in mind? (github_handle taken out of the params, field disabled; validation on email) 
![gh_greyedout_email_validation](https://cloud.githubusercontent.com/assets/14924179/16730923/c6e5ebae-4775-11e6-81f2-9aba53197636.jpg)

**Comment by carpodaster** [comment]
Hey @izuroxx. Yes, looks good! The email validation should only kick it when _updating_ the record though (for reasons stated above). But we can discuss / check on that in a PR.

**Comment by izuroxx** [comment]
@carpodaster there's one more thing :) - while finding all occurrences of Github_handle fields, I also found them in /teams/:id/edit, and also editable - you can change team members through changing the g_h field - would you like those fields to be disabled, too?

**Comment by ramonh** [comment]
@izuroxx I think these should be left as editable so that students for example can add their team members. I hope I understood correctly

**Comment by F3PiX** [comment]
I think Ramon is right, as far as teams in current season are concerned. Then again, I can edit _everything_ in my team from _last_ year. Maybe we should 'freeze' team info from previous seasons. Or is that a problem, @anikalindtner @carpodaster ?

**Comment by carpodaster** [comment]
@izuroxx fixed the github_handle mutability! 🎊

**Comment by F3PiX** [comment]
Can we extract a new issue, with only the first checkbox? @carpodaster

**Comment by carpodaster** [comment]
@f3pix let‘s do it!

**Comment by F3PiX** [comment]
Closing this. The leftover checkbox nr 1 is moved to #885.
