### ISSUE TITLE
Application submission fails in a weird way

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#419]
If my coaches are not confirmed and I submit an application, I don't get any error messages on the Application form. Instead I get redirected to the page of my team.

![screen shot 2016-03-14 at 23 14 04](https://cloud.githubusercontent.com/assets/1745735/13762101/04787450-ea3d-11e5-8eee-5e3d984fb181.png)
  
My application is still available for editing and submitting.

Another thing you can see on this screenshot is that I have two coaches which are marked as confirmed, and I still see the message, that the coaches are not confirmed. We should probably restrict adding coaches, who are already students in this (or another) team.

**Comment by alicetragedy** [comment]
yep, you are right. I guess this has to do with the student being a coach.

**Comment by ramonh** [comment]
Definitely a bug having students be coaches of their own team, thanks for catching this!

I thought it would be helpful for students to see which of their coaches hasn't confirmed yet. Do you think it's better not to redirect to the team's page?

**Comment by alicetragedy** [comment]
@ramonh maybe an alternative would be an error message "Your coaches have not confirmed their membership" with a link to the specific team in there? so the student can go and check out what the deal is, but only if they want to ;)

**Comment by ramonh** [comment]
Yeah, that makes more sense! Thank you @alicetragedy

**Comment by ramonh** [comment]
The above PR should take care of the redirecting. About the second problem, I could restrict students from also being coaches. Of course, if they were students last season and want to be coaches this season, this should be fine. I'll look into whether this is fine.

**Comment by alicetragedy** [comment]
@ramonh did you get a chance to look into this?

**Comment by ramonh** [comment]
Hey @alicetragedy, I did start but haven't finished yet! Will have a pr ready for tomorrow, hopefully.

**Comment by carpodaster** [comment]
@ramonh @mkalininait Did the PR  (merged and now live on staging) fix the issue?

**Comment by ramonh** [comment]
It should be fixed, @carpodaster. I've tried adding myself as a student and a coach to my team, and had no luck :) 
![screen shot 2016-03-18 at 10 31 25](https://cloud.githubusercontent.com/assets/656318/13873878/a4bc9338-ecf4-11e5-9d19-c5e6a32da235.png)

**Comment by alicetragedy** [comment]
looks good, I think we can close this.
