### ISSUE TITLE
New Team / Edit Team issues

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#420]
1. When an error happens, all my deleted fields come back.
   For example, I have a team with Student X and Student Y. If I delete Student X and add Student Z, who is already a member of another team, and submit the form, I will get an error, and Student X will appear on the form again.
2. I think we should not allow creating empty teams. Now it's possible.

**Comment by mkalininait** [comment]
Tested on [Staging](https://rgsoc-teams-staging.herokuapp.com), was able to reproduce both bugs.

**Comment by bitboxer** [comment]
Sorry for the delay. Fixed the code, need to fix a few tests and then will be done. Working on it this afternoon

**Comment by bitboxer** [comment]
Sadly I ran into a little problem with number 2: lots of the test code thinks that you can create empty teams. After I changed the minimum requirement to at least 1 team member, 43 tests failed. I tried to start to fix them, but it will take me at least 2 days to fix that everywhere. I would vote to skip number two and just do the first thing. Would that be okay? Empty teams can't apply anyway...

**Comment by mkalininait** [comment]
@bitboxer My problem with empty teams was that once you [accidentally] created an empty team, you couldn't delete it anymore without magic orga superpowers. But I agree, that empty teams don't do any harm actively, and it's not even a common use case. 
Skipping this bug is totally ok for me considering the efforts it requires.

**Comment by mkalininait** [comment]
Tested issue 1 locally, it is fixed.
