### ISSUE TITLE
Add field for mentors to add a link to their project's Code of Conduct

### ISSUE THREAD

**Issue by ramonh** [rails-girls-summer-of-code/rgsoc-teams#427]
As discussed, having a field where mentors can add a URL to their project's Code of Conduct would make it a lot easier to find and make it known that those are a criterion for accepted projects.

**Comment by alicetragedy** [comment]
+1

**Comment by mkalininait** [comment]
Do we really want to add it this year? Call for projects will end in 4 days.

**Comment by alicetragedy** [comment]
I think this is just meant as a quick to-do for a team that might want to work on the teams app in the summer @mkalininait

**Comment by carpodaster** [comment]
Done in #450
