### ISSUE TITLE
Hide 'Review and Submit' tab for already submitted applications

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#428]
Now I can see the tab 'Review and Submit' in the application, which I have already submitted, and this tab is blank.

**Comment by alicetragedy** [comment]
hey @mkalininait do you still want to work on this? if not, I can reassign to someone else, just let me know! It would be cool to have it this/next week, before applications really start flowing in.

**Comment by mkalininait** [comment]
@alicetragedy Ah damn, l totally forgot about this issue. Let me see if I can do it over the weekend.

**Comment by alicetragedy** [comment]
I did as well — sometimes repo cleanups help ;) 
Great, thank you! :sparkles:

**Comment by alicetragedy** [comment]
we can close this issue. thank you @mkalininait! :tada:
