### ISSUE TITLE
Add a 'Tags' column to the list of projects

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#435]
This is a wish from one potential student.

**Comment by alicetragedy** [comment]
this is already in the /orga/projects, so should be easy to implement. :+1:

**Comment by alicetragedy** [comment]
this has been solved, but we talked about at least one "extra" thing:
- showing only non-rejected projects (ie. with status accepted, pending)

do you want to add that as a separate issue, or add it to this one? It's up to you :) If you add it as a separate issue, you can close this one, as you've fixed it with your PR.
