### ISSUE TITLE
Preview function for project proposals

### ISSUE THREAD

**Issue by The-Compiler** [rails-girls-summer-of-code/rgsoc-teams#437]
I just submitted a new project, and it would've been nice to be able to preview the rendered output before doing the submission.

Minor nitpick of course - submitting and editing worked fine as well :wink:

**Comment by alicetragedy** [comment]
Hey @The-Compiler — that is absolutely right, we had in fact thought about it already, but due to deadlines, we did not implement it for the current submission period. I'd definitely like to keep this in mind for next year and believe it would also be a great task for newcomers to the project. :)
Thanks for the suggestion!

**Comment by izuroxx** [comment]
@ramonh may I look also at this one?

**Comment by ramonh** [comment]
Hi @izuroxx, thank you! Please do go for it :)

**Comment by izuroxx** [comment]
@ramonh i wanted to make something to start a discussion, My current attempts look like this
![preview1](https://cloud.githubusercontent.com/assets/14924179/17325444/e7893cb6-58ab-11e6-81f5-1e4079fe64ca.png)
![preview2](https://cloud.githubusercontent.com/assets/14924179/17325450/eeb62422-58ab-11e6-86e4-ccf5a56bee7a.png)
preview renders above the form after clicking on a preview button. I wanted to try do this, but i guess it's not very readable and should be on a separate page?

**Comment by ramonh** [comment]
Hey nice one @izuroxx! Looks great so far.

Hm, I'd actually say that having it appear below would be better. Maybe even side by side?

Actually, the way Github does it is pretty good too, with a tab-based approach. I'd say this would be best. 

What do you think?

**Comment by izuroxx** [comment]
the tab-based one is cool, it crossed my mind while writing the comment earlier :) i have to take a close look at this

**Comment by ramonh** [comment]
Cool, glad you agree! Let me know if I can help.
