### ISSUE TITLE
Application process: coach unable to confirm belonging to a team

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#438]
According to a student's bug report, the team coaches were unable to confirm themselves through the UI after being added to a team. I investigated a little bit, and it seems that this fails for teams whose coaches were added prior to us introducing the "coach confirmation" (meaning, no `confirmation_token` was created). 
I don't think too many teams are affected, but this is something we should keep in mind.

**Comment by carpodaster** [comment]
I have added confirmation tokens to all six 2016 coach roles existing prior to us merging the confirmation logic.

**Comment by alicetragedy** [comment]
:tada:
