### ISSUE TITLE
Change appliaction count in projects view to only count submitted applications

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#440]
For now - as I understand it - the applications for a project are counted when someone creates a draft. I'd say we should only count submitted applications.

Reason: last year showed that a lot of drafts are not even going to be sent off and thus a higher count on projects might scare some teams away, but in the end it could turn out that actually no one applied for this project, because it was just all drafts.

**Comment by carpodaster** [comment]
I'm not really in favour of this feature request. We know that most applications will be sent in very close to the deadline. The counter will be very, very for the duration of the application phase, creating a false sense of 'safety' - basically we revert the insecurity that your feature request aims to fix.

**Comment by alicetragedy** [comment]
I'm wondering if we shouldn't simply hide the counter completely as an in-between solution? I don't know, I also have mixed feelings and felt the same way about the fact that most people will send their application very close to the deadline, and I don't know which way is best. Maybe, we can clarify that these are application drafts?

**Comment by anikalindtner** [comment]
yeah, if we keep it we definitely have to clarify that these are drafts. maybe we could just show both? submitted and drafts? or is that too overengineered?
