### ISSUE TITLE
Selection App 

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#441]
We have another monster inside the teams app monster and that is the selection process. What once was a hack based on infos that came in through google forms is now an out-dated app where we don't have any tests or documentation for. 

This worked last year, but only with a lot of :see_no_evil: and :speak_no_evil:s. This year we'd love to 
+ add a stage of blind selection to the process (meaning hiding certain information of the applications). 

We also would love to just throw away the code and build something new. Sven, who wrote the selection app once, recommended that instead of building more stuff onto the old code. He also said that yes, it is ugly and confusing (all the google form hashes), but if you had some time, you could definitely figure our how the app works by reading it and building a new one. 

+ We need someone to take some time to poke around the selection part of the teams app and give (There is a model `rating.rb` and `rating_data.rb` (and an associated controller) that is where most of the info from the selection app would be)

+ Then you should be able to give feedback about if this would be at all possible to build a new selection app until Mid-April. 

@michaelem and @klappradla: would you be willing to take this on? 

I'm guessing this will probably be a close call regarding the timing, but if you have some time to really dig into it, it might work? As a fallback we always have the old monster to use for this year's selection again.

**Comment by anikalindtner** [comment]
Also: If you have questions regarding the code, I can always ping Sven about it. He can help a bit with answering specific questions.

**Comment by michaelem** [comment]
Yepp, I think I can spend some time this week and go spelunking in the old code.

**Comment by alicetragedy** [comment]
Awesome, thanks @michaelem. we'll try to discuss some guidelines for the selection that are important to us in one of the next team calls, so I can give you more info after that. :)

**Comment by anikalindtner** [comment]
yay, thank you @michaelem! :star: :rocket: :sparkles:

**Comment by carpodaster** [comment]
yay, thanks @michaelem

**Comment by klappradla** [comment]
I'd be happy to help you in April @michaelem if still necessary then.

**Comment by michaelem** [comment]
Can someone walk me through the current process? I'm kinda guessing how this is all inteded to work by looking at controllers...

**Comment by alicetragedy** [comment]
@michaelem happy to give you a hand and walk you through it :)

**Comment by anikalindtner** [comment]
👯

**Comment by anikalindtner** [comment]
Okay so looking at the time, we thought pushing for building a new app in 10 days is maybe not the best idea. We'd love to concentrate on making the one we have a bit easier to use (maybe some improvements to the UX and definitely updating the tags - @alicetragedy offered to help). 

It's still super important to have ppl who understand the app and can help to make it a bit better and maybe even understand the algorythms -  so @michaelem and @klappradla all the work you can put in is super valuable. I just wanted to say that **building a new app** will not be a goal for this year's selection anymore. Do you think that makes sense?

**Comment by michaelem** [comment]
@anikalindtner : as far as I have seen I would not break this out into a separate app anyway. (It was apparently once a separate app and then got integrated.) Anyway, it does not look super complicated, I would like to sit down with someone who cares and knows about the process and figure out where we want to go. (What to hide in the blind selection and what to change in the existing process.)

**Comment by anikalindtner** [comment]
@michaelem awesome, that sounds good! i know that @alicetragedy wanted to pair. maybe we can all sit together next week when i'm in vienna? maybe @klappradla is also available?

**Comment by alicetragedy** [comment]
in-person would be great. I think Max might still be busy then, but let's see what he says. I'm flexible :)

**Comment by anikalindtner** [comment]
maybe @mkalininait can join too, if she wants! :)

**Comment by ramonh** [comment]
I could also help, if needed!

**Comment by anikalindtner** [comment]
help is *always* super appreciated @ramonh :sparkling_heart:

**Comment by ramonh** [comment]
Count me in, then! :smile_cat:

**Comment by mkalininait** [comment]
@anikalindtner I'd love to! However I'm not in Vienna next week, so only in remote mode at the moment.

**Comment by klappradla** [comment]
@alicetragedy joining in there seems sustainably invested time to me as it will prob. fasten my understanding of the whole thing. So I'm in.
I'm *"flexible"* besides meetups and stuff (same as Ramón I guess).

**Comment by klappradla** [comment]
Just to make sure: @alicetragedy, a user can only edit her own ratings on a student, team, etc., right?
*(just wondering why only the create is scoped to the current_user and I cannot find any superadmin that might be able to navigate somewhere to edit other user's ratings, that's why I ask)*

**Comment by alicetragedy** [comment]
@klappradla that's exactly right, a user can only edit their own rating and no one else's. :)

**Comment by klappradla** [comment]
As we're getting rid of most of the statistics stuff, we planned to have the table at `/applications` have these columns *(besides the basic ones on student, application etc. of course)*:

| Picks | SumPoints | AvgPoints | Max | Anika | ... |
| --- | --- | --- | --- | --- | --- | --- | ---
| 2 | 300 | 100 | 100 | 100 | ...

| ... | MentorPick | Volunteering | Remote | 
| --- | --- | --- | --- | --- | --- | --- | ---
| ... | x | x | - | 

Tell me if you are missing anything important.

**Comment by mkalininait** [comment]
@klappradla thanks Max!
A couple of questions from my side:
* Who fills out the 'MentorPick' and 'Volunteering' columns? I guess the 'Volunteering' flag can be set automatically, and the 'MentorPick' is set by a person who interacts with mentors. Is it so?
* What exactly the 'Remote' column mean? Do we retrieve students' and coaches' locations and check if they are from the same location automatically? Or how does it work?
* As far as I understand, the 'Remote' flag is a definite NO-GO for a team. Should we include the 'Gender' and 'Age' flag there as well?

**Comment by klappradla** [comment]
If I as a reviewer viewing an application in the reviewing context, I have a `Edit additional Info` Button, where I can set all these flags, including `Remote`.

For `Gender` and `Age`, I don't know where they come from, and I guess they aren't *flags* in the sense that they can be displayed as `x` or ` `, do they? Should it be both student's gender and age somehow summarized?

Anyways, here's a screenshot of the `additional info` form (I guess it's not reachable on staging):
![screen shot 2016-04-11 at 23 57 33](https://cloud.githubusercontent.com/assets/3491815/14443877/4fe29784-0042-11e6-965d-9657d81a021c.png)

**Comment by mkalininait** [comment]
@klappradla Oh wow, it's a secret form. I didn't know about it. I wonder who fills it out.
It feels like the field 'Volunteering team' is filled out by applicants, don't see why we fill it out again here. May be we should add 'Gender' here too (it's a text field in the application form).
WRT age, we have several categories to select in the application form. We could just put a flag on those teams where at least one applicant in 'below 18'.

**Comment by klappradla** [comment]
I think all of the needed behavior is in place. Maybe someone could check out out the [ratings branch](https://github.com/rails-girls-summer-of-code/rgsoc-teams/tree/ratings-overhaul) and walk through some of the selection / rating steps.

**Todos**
I updated the todos *(`/rating/todos`)* to only show applications (scoped to the current season). For the sake of time and simplicity, I got rid of the "step-through" process though.

**Applications**
I refactored the table *(`/rating/applications`)* to work as before, but with current data and scoped to the current season. Again for the sake of time and simplicity got rid of the "next" and "prev" buttons.

**Question**
One thing I could not figure out though: was there a way to navigate to all these parts of the application without manually entering the url?

**Comment by anikalindtner** [comment]
@klappradla iirc there was no way to navigate to all these parts before. but this https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/456 should hopefully fix this.

**Comment by michaelem** [comment]
can we close this now?

**Comment by klappradla** [comment]
I guess so - there are other issues taking care of the leftovers.

**Comment by mkalininait** [comment]
I agree with @klappradla , but let's @anikalindtner make this decision since it's her issue.

**Comment by anikalindtner** [comment]
aaaand CLOSED :D
