### ISSUE TITLE
Remote Coaches

### ISSUE THREAD

**Issue by ishishruti** [rails-girls-summer-of-code/rgsoc-teams#449]
I along with my team partner are having difficulty in finding coaches in our own city i.e. Pune . So is it possible that we apply for coaches who are not in the city. We are in contact with people outside India having great skills who can help us. We can always be in contact with them on Skype.
So can we apply for remote coaches?

**Comment by alicetragedy** [comment]
Hi @ishishruti, this is not the right place to submit support questions for student applications. You can find our email address in the [student application guide](http://railsgirlssummerofcode.org/students/application/#place-application). Thank you!!
