### ISSUE TITLE
add contributing guidelines

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#454]
I'd like to add some contributing guidelines to make it more easy and accessible for newcomers and people outside of the RGSoC team to contribute :) 

Things we might want to have:
- guidelines on finding an appropriate issue (ie. the usage of labels and what they mean)
- guidelines on how to call "dibs" on an issue 
- guidelines on making pull requests (ie. branches we use, information that should be in the PR)

Maybe also add the handles of some of the more present contributors that can be pinged for questions.
Is there anything I've forgotten, @carpodaster?

**Comment by carpodaster** [comment]
Sounds really good!

**Comment by carpodaster** [comment]
This may be old news, but Gh automagically provides a link to a `CONTRIBUTING.md` file on every PR made to a repo where such a file exists.

**Comment by alicetragedy** [comment]
@carpodaster I did not know this :) might even have some time for it this week. I didn't think about how it might be useful to have during the application process :cry:
