### ISSUE TITLE
Application page: comments are not ordered

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#460]
Comments should be ordered by date, newest on top.

**Comment by klappradla** [comment]
I think they are actually automatically ordered *(by ID => by time)*. But the other way round, oldest on top - same system as here on Github.
Did you have a timewise jumble of comments?

**Comment by mkalininait** [comment]
@klappradla plz look here

![screen shot 2016-05-15 at 23 08 58](https://cloud.githubusercontent.com/assets/1745735/15276786/4f57b8f6-1af2-11e6-9269-2fe07732d0f9.png)

**Comment by klappradla** [comment]
Oh, definitely worth being titled as "bug" - thanx!
I can take a look at it tomorrow morning. Are you fine with sticking to Github-like ordering? I personally find it very intuitive, but may only be me.

**Comment by mkalininait** [comment]
@klappradla Thank you! I don't mind any order, as long as there is logic behind it :)
