### ISSUE TITLE
Move conferences CRUD to orga namespace

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#463]

**Comment by F3PiX** [comment]
I'll gladly take this one. Best to wait until  #512 is finished? To avoid complications.

**Comment by carpodaster** [comment]
Hey @F3PiX, did you link the correct issue? #512 seems unrelated.

**Comment by F3PiX** [comment]
thnx, It is #503.

**Comment by F3PiX** [comment]
Closed by #546
