### ISSUE TITLE
CSV exports

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#467]
Hej @anasofiapinho and @mkalininait – you mentioned a CSV export feature today. Could you briefly scetch what kind of data you would need exported on a regular basis?

**Comment by anasofiapinho** [comment]
Hey @carpodaster!
We usually need the contacts and some of profile data for several purposes, such as sending acceptance and rejection emails and afaik we will also need to send the boxes with the merchandise from the sponsors, so we will need their addresses and t-shirt size.

* Name
* Email
* Country
* City
* Address
* T-shirt size

@mkalininait, do you think we need any other field?

**Comment by anasofiapinho** [comment]
Can you also export the project they are working on?

I was also wondering if we could export the contacts of the coaches and mentors associated with a team. We will probably have to send all of them emails...

**Comment by mkalininait** [comment]
@carpodaster We used this table during the selection process: https://docs.google.com/spreadsheets/d/1bdqjSdLliThNWY3snsU4v_up1j0OP62E7CQcVGlHpOI/edit?usp=sharing
In order to get it, we had to pull emails from the DB, and then add other missing information manually. This was not super efficient.

Now I need the same information about coaches (names, emails, teams at the very least). Is it something that can be done quickly enough or is it a task for later? In the latter case I will just get the data manually again and hope it will be easier next year :)

**Comment by carpodaster** [comment]
It looks like we need three different exports:

1. Users
2. Teams (with mentors and coaches)
3. Projects?

All of this just for the current season (to start with). 

Is it ok to have teams and users in separate CSV tables? You can join them with a little spreadsheet magic (disclaimer: I'm not good at wielding Excel/OpenOffice magic).

**Comment by mkalininait** [comment]
@carpodaster Should be fine! We can try :) (I like casting magic in spreadsheets :) )

**Comment by mkalininait** [comment]
@carpodaster Do you think it can be implemented this week or should I pull contacts from the DB this time again? (jftr: I'm absolutely fine with that too!)

**Comment by carpodaster** [comment]
@mkalininait I'm on a long-distance train ride this Saturday so I can do it this week. If Saturday is not too late for you.

**Comment by mkalininait** [comment]
@carpodaster It definitely works, thank you so much!

**Comment by carpodaster** [comment]
Hey @mkalininait, there are some exports ready for grabs at https://teams.railsgirlssummerofcode.org/orga/exports – Teams#current containts student + coach info. Ping me if you need more data … I won't be able to get to it until tomorrow night though.

**Comment by mkalininait** [comment]
@carpodaster Thank you so much!
I've tested the exports, all work except the users#for_rejection_letter (just to let you know in case you are not aware of it).
I think I will get coaches' emails from the Teams#current export. Is there any way to add coaches' names there?

**Comment by carpodaster** [comment]
Thanks for the feedback, Maria. I haven't tested `#for_rejection_letter` but I assumed it wouldn't work any more: it's quite old, untested, it even has a comment that it probably breaks at a certain point. I just carried it over because I was too lazy to delete it. It's gone now.

I've added the coaches' names in a separate column.

**Comment by carpodaster** [comment]
@anasofiapinho I've added the students' export with location + tshirt sizes.

**Comment by anasofiapinho** [comment]
So awesome @carpodaster! Thank you! <3
This will really make our lives easier! \o/
