### ISSUE TITLE
review email setup

### ISSUE THREAD

**Issue by michaelem** [rails-girls-summer-of-code/rgsoc-teams#469]
Since we will be adding more notification emails I thought it would be a good idea to review the mail setup. Can someone ( @alicetragedy ?) walk me trough the email setup?
My hunch is that we might be able to improve our delivery rates by adding SPF policies and so on. (And maybe start using a different from address with a domain that we have more easy access to.)

**Comment by alicetragedy** [comment]
I think that's a great idea @michaelem. I don't have any insight into the email setup, but can maybe look over it with you if @carpodaster is busy. :)

**Comment by carpodaster** [comment]
The Teams App sends mail as summer-of-code-team@railsgirls.com via Google Mail.

**Comment by michaelem** [comment]
Ok, if it's actually sending via gmail it should be fine for now.

**Comment by carpodaster** [comment]
I've just checked with `dig txt railsgirls.com`: the domain has no SPF data. I don't know how much mail services encorce SPF settings these days, but in any event: we don't control the domain so it's not in our hands. Does anyone know who could add [SPF data to railsgirls.com's DNS](https://support.google.com/a/answer/178723?hl=en) ?

**Comment by michaelem** [comment]
Yep, that was what I originally noticed: no SPF or dmarc.
It looks like the dns provided by linode.
It would help all email sent from the domain so there would be an advantage for the maintainers of the domain as well.
