### ISSUE TITLE
Links to supervisor wiki

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#474]
Hi!
I was checking the supervisor's dashboard. The dashboard has 2 links to Supervisor's documentation: the guide and the wike. The links are currently pointing to two non-existent github repo's. 
Are there new url's for these guides? 
https://github.com/rails-girls-summer-of-code/supervisors/wiki
https://github.com/rails-girls-summer-of-code/supervisors

**Comment by carpodaster** [comment]
Hey Maud, thanks for filing that issue. The repos do exists but only supervisors have access to it.

**Comment by F3PiX** [comment]
👍
