### ISSUE TITLE
More CSV exports (applications)

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#477]
Hi @carpodaster !
Here is a small follow-up to [Issue #467](https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/467).
Would it be possible for you to add export of the 'applications' table to csv?
I'm collecting statistics on applications 2016. I think this export will be useful next years as well.

Thanks!

**Comment by carpodaster** [comment]
@mkalininait will deal with it tomorrow!

**Comment by carpodaster** [comment]
@mkalininait the exporter is online now. Ping me if you need additional columns or close this issue if it's all good ☀️

**Comment by mkalininait** [comment]
@carpodaster I've looked through the resulting csv, looks great, thank you!
Would it be possible to add data from the additional form there, WDYT? Could be handy to retrieve locations, coaching companies, flags.

**Comment by carpodaster** [comment]
@mkalininait I'll look into it tonight

**Comment by carpodaster** [comment]
@mkalininait I've added a couple more fields. Please check if you need more :)

**Comment by mkalininait** [comment]
@carpodaster Looks awesome, thank you!! 👍
