### ISSUE TITLE
Activity Stream: Proxy http:// images through camo

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#479]
Currently images embedded / referenced to the activity stream ("minilog" feature) that do not use the https protocol scheme cause browsers to display a mixed content warning.

It's more of a nuisance than a real security threat of course, but it still doesn't feel right.

There is a service called [camo](https://github.com/atmos/camo) that proxies insecure assets through a TLS connection. It has to be self-hosted. It's a nice thing to play around with, I believe, but otoh, it adds complexity and takes some time to implement.

Is it worth it?

**Comment by carpodaster** [comment]
omg works flawlessly: https://teams.railsgirlssummerofcode.org/status_updates/1623-day-10-upcoming-blog-post-d  😄

**Comment by alicetragedy** [comment]
@carpodaster another day, another (aka: the same old) gif.

![css](https://cloud.githubusercontent.com/assets/3143348/16878237/14cc8010-4aac-11e6-81c7-144a26de37d6.gif)

**Comment by carpodaster** [comment]
Yes, yes 😆  - but that's my Baustelle 😉   The image is loaded from https://rgsoc-teams-camo.herokuapp.com - it originally referenced imgur.com and is now transparently proxied.

**Comment by F3PiX** [comment]
Aaaah no worries. Modern culture values image over text :-)
