### ISSUE TITLE
Only show selected teams in the drop down menu

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#485]
Hey all, I've recently added some members to teams and it's really confusing and hard, because we have a seemingly endless list of teams to choose from - not just this year's teams, but also teams from last year and teams who applied but didn't get selected:

![screen shot 2016-07-06 at 08 47 22](https://cloud.githubusercontent.com/assets/1711357/16609690/51eeb8f8-4356-11e6-8fd0-0ed7f6a5ac60.png)

Who can change that? @F3PiX do you want to take that on?

**Comment by carpodaster** [comment]
It's a valid point! Problem: we need to make the teams list for the select box Season phase-aware.

To get it fixed fast, I suggest we differentiate between "after rejection letters have been sent and coding phase has not yet ended" and "rest of the season" only. In the former case: feed the select box selected teams only.

**Comment by F3PiX** [comment]
Cool, I will have a look.

**Comment by F3PiX** [comment]
Where does this select-box live? Is it somewhere in orga(name)space?

**Comment by F3PiX** [comment]
I will do the quick fix first. Then again, the workflow here looks a bit cumbersome to me for the beloved orga's. :-) Maybe look into this for a future Orga Dashboard?

**Comment by F3PiX** [comment]
O sorry. Do we have a policy that only the opener of the issue can close? Or can I close this when it is merged.

**Comment by carpodaster** [comment]
> Do we have a policy that only the opener of the issue can close? 

We do not have this set in stone, no. I usually ping the author of the issue via a comment when I think I fixed something and assign it back to them (only possible for project collaborators), but I do close issues myself if there hasn't been a response in some time. The original author will get a notification anyway and can re-open if necessary.
