### ISSUE TITLE
Refactor season switch into a separate class

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#499]
The season switch methods [add some complexity](https://codeclimate.com/github/rails-girls-summer-of-code/rgsoc-teams/Season?from_sha=17c93b66&to_sha=1b9c7d0b) to the `Season` class according to CodeClimate.

There are three steps:
- [ ] Extract default dates for a newly created season into some form of constant
- [ ] Re-use these constant default values in `set_application_dates` (where applicable) and `back_to_reality`
- [ ] Move the `fake_*_phase` and `back_to_reality` into a service class

**Comment by F3PiX** [comment]
Yes, I saw the code climate score earlier this week and it made me very sad ;-) I would love to improve it.

**Comment by carpodaster** [comment]
Sure Maud!

**Comment by F3PiX** [comment]
Goal accomplished 🎉 
![season after refactoring](https://cloud.githubusercontent.com/assets/6314687/21317835/19c29970-c607-11e6-92ac-a3408bba2e5a.png)
