### ISSUE TITLE
Past Teams

### ISSUE THREAD

**Issue by inescoelho** [rails-girls-summer-of-code/rgsoc-teams#502]
- [ ] It would be nice if we were able to browse past teams' activity. Some of this information is still available when people is connected with past teams (like me, since I was a student last year and now I'm a supervisor).
- [x] Moreover, the team profile presents the starting date and finishing date of the team. However, this information only displays day and month. Now that we are in the 4th edition of RGSoC, it get's confusing... It would be useful to add the year as well.

**Comment by F3PiX** [comment]
I like the idea of browsing in the history. I would prefer to set up the design for the majority of users, for who the current year matters only. And thus, adding the year 2016 is a bit of noise. Maybe we can add something like a select box to filter activities by year and/or previous team names and what not?

**Comment by inescoelho** [comment]
Hi @F3PiX! When you have someone involved in several teams like [this](https://teams.railsgirlssummerofcode.org/users/474), it's kinda hard to figure out where those teams come from. After opening each profile, you have to scroll down to their activity to figure out from each edition they are and it would be nice to have something more immediate.
The browsing on history feature could be useful to show to the world what is our program and what it has been done throughout the years. This could easily be done with a selection box on the Teams page, where you select the year and the table would display the teams of that year. ;)

**Comment by F3PiX** [comment]
Haha, great profile page. 
I see what you mean about adding the year to the start and end date on the Team's profile page. I do think that is a good idea. 
And sure, browsing the history in one way or another can be useful. I am not sure if the best way is to add a filter to the teams index page. I think the community page is a better place for that? There is not much room for an extra column though. Apart from that, how do you think about that?

**Comment by carpodaster** [comment]
Hey @inescoelho. I agree that it would be nice to make past teams more visible, but I also agree with @F3PiX that our main focus is always on the current season and it's therefore not super-high on our priority list. Would you maybe like to work on it yourself and send a PR? 😄 

You raise a valid point with the date format: that should be fixed. I took the liberty of editing your issue to create a checkable bullet list.

**Comment by branquinhoaa** [comment]
Hello! what do you people think about this layout for this issue?
It is /teams index, as suggested by Ines.
![past_teams](https://user-images.githubusercontent.com/15239141/29176144-66920bba-7dc1-11e7-9bed-2f8465f3c2cf.png)

**Comment by klappradla** [comment]
Closing this via #814
