### ISSUE TITLE
Conferences - small improvements for adding new

### ISSUE THREAD

**Issue by agnik5** [rails-girls-summer-of-code/rgsoc-teams#503]
- [x] 1/ When trying to add a conference without its name, conference is not being added, but the view is broken. I guess there should be for example some alert like 'fill in the name' or a view informing that a conference haven't been added with "Back to index" option.
  ![screenshot from 2016-07-15 16-00-16](https://cloud.githubusercontent.com/assets/12581810/16878048/48267e62-4aab-11e6-9587-5cc5e6dca753.png)
- [ ] 2/ It's possible to add a conference with end date earlier than start date.
  ![screenshot from 2016-07-15 15-42-21](https://cloud.githubusercontent.com/assets/12581810/16878147/b3c63a5e-4aab-11e6-81bf-13452c3fdc60.png)
  ![screenshot from 2016-07-15 15-44-37](https://cloud.githubusercontent.com/assets/12581810/16878146/b3c58140-4aab-11e6-8532-f02b4fa393a7.png)
- [x] 3/ When adding a conference it's possible to choose not round 1 or 2, but 16, 21, -11 etc. You get a view like conference has been created /but it's not on the list/. There's no alert about incorrect round chosen. I think there should be only two values to chose from /1 or 2/.
- [x] 4/ Similar problem in tickets and flights. You can create a conf with -50 tickets and -40 flight and it gets on the list.
  ![screenshot from 2016-07-15 16-55-35](https://cloud.githubusercontent.com/assets/12581810/16878696/d01a15f2-4aad-11e6-8382-6b627d5a779f.png)
  ![screenshot from 2016-07-15 17-00-40](https://cloud.githubusercontent.com/assets/12581810/16878695/d0173968-4aad-11e6-8a46-524eb38fb678.png)

These are not crucial improvements, as conferences are being added by Orga Team and so risk of mistake is close to zero. Only suggesting.

**Comment by carpodaster** [comment]
Hey @agnik5, 👍 to everything you said 😄 . The numbered items fall all nicely into place as a priority list. I think no. 1 should _really_ be fixed. The `save!`  call raises an exception if the record is invalid. This would have to be changed to a normal `save` (w/o the bang). The form has to be re-rendered when there was an error and redirected in case everything went well.

**Comment by F3PiX** [comment]
There is something strange with the date format as well....
![schermafbeelding 2016-07-26 om 16 20 22](https://cloud.githubusercontent.com/assets/6314687/17150852/5a672bb6-5371-11e6-84b7-578a6f05f20a.png)

**Comment by carpodaster** [comment]
@F3PiX Can you post on which controller action / URL that is?

**Comment by F3PiX** [comment]
Hi Carsten, This was on my profile page. localhost:3000/users/33
And on the team's profile page localhost:3000/teams/4 it is like this:
![teams profile page](https://cloud.githubusercontent.com/assets/6314687/17868976/769412d6-68b1-11e6-8cfc-fd36d192a375.png)

**Comment by F3PiX** [comment]
YAY. Last bullet solved. Thanks to @carpodaster and @klappradla for all the support 💯
