### ISSUE TITLE
Refactoring of styling - global.sass

### ISSUE THREAD

**Issue by agnik5** [rails-girls-summer-of-code/rgsoc-teams#504]
I think the file `app/assets/stylesheets/global.sass` may be reconsidered as global properties got mixed with those applying to certain elements/files. 
Nothing urgent, but a little clarification may be helpful for working with stylesheets files.

**Comment by katrin-k** [comment]
I also had a few confusions when browsing through the files.  Since I'm currently digging through `/app`anyways and trying to solve the most obvious mobile issues I might as well work on the sass files.

**Comment by katrin-k** [comment]
I'll close this issue. The PR #510 is not yet reviewed/merged, but any remarks can go there, I suppose.
