### ISSUE TITLE
Error pages should indicate the type of error

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#506]
The page should also state "500 internal server error" or "404 not found" in addition to the cat cuties.

**Comment by katrin-k** [comment]
Additionally, I'll add a `home` link to all error pages.

**Comment by katrin-k** [comment]
@carpodaster Can this issue be closed?

**Comment by carpodaster** [comment]
Yes! Thanks a lot, @katrin-k !
