### ISSUE TITLE
Slow loading with search

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#529]
It takes a lot of time for the page to load after submitting a search. I found that the Time to First Byte is very long: 

![search page loading](https://cloud.githubusercontent.com/assets/6314687/17717868/d33fdfba-6410-11e6-913a-13a9cccfdeda.png)

I don't know how to find the cause for this. Hints? Ideas?

**Comment by carpodaster** [comment]
Hello Maud, thanks for reporting this! I could reproduce it locally the other day. It would seem that the current season is fetched from the DB way too often (n+1 problem?). Haven't had the time to dig deeper – if anyone wants to tackle this: it's up for grabs 😄 

It's a performance issue, but not a really pressing one. I don't have any data too back this, but I should think that `GET /users` is not our most frequented endpoint.

**Comment by F3PiX** [comment]
- About the n+1 : Sometimes it renders very fast. If it would be a n+1 problem, wouldn't it be _always_ slow? 
- What I found: WHEN it renders slow, it is mostly the views that takes a long time (over 200 ms).

**Comment by F3PiX** [comment]
I found that  it has to do with the [Google analytics script](https://github.com/TeamCheesy/rgsoc-teams/commit/1ee473d473d217f802a570f3ed978fb957a24915#diff-1ccd3e5828c7330cdc2450c78847cd35R32) in application.html.slim  .
With this switched off, everything loads under the recommended 200 ms. With the script switched on, even the plain `users` view needs way over 400 ms. 

Makes sense?

**Comment by F3PiX** [comment]
Cool! This is solved by 33f2021. 💃 
![schermafbeelding 2016-11-24 om 00 05 03](https://cloud.githubusercontent.com/assets/6314687/20581776/6b684c56-b1db-11e6-9149-01f7072e96bf.png)
Can be closed now.

**Comment by carpodaster** [comment]
Nice! And what a cool side-effect :)

**Comment by alicetragedy** [comment]
hahaha that's brilliant! 🙌 ✨
