### ISSUE TITLE
improve mobile experience

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#532]
While we can safely assume that most users are viewing the Teams App from a laptop or otherwise bigger screen/device, there are still a couple of glitches with the overall mobile experience that we can't really ignore 😂 

This is a feeble attempt at collecting several "smaller" issues and bugs currently happening on the Teams app. 
- [x] 1) box for content filter on the activities page is smaller than its content (see screenshot 1)
- [x] 2) Signed in as and sign out link info (top right) is being wrapped onto the next line (see screenshot 2) (note from and for Katrin: try margin-left: auto; and different width on this one)
- [x] 3) the burger menu is a little all over the place: it doesn't always show all links (e.g. Community and Home), is at times hidden behind other elements (e.g. behind the Activity filter box), is transparent or makes it difficult for the links to be clicked because of the transparency. On some pages, it even pushes the "sign out" link down out of the way. (see screenshot 3 & 4)

I'd love to have some of these issues fixed <3

On top of those, the tables on the teams and community pages are not responsive (I realise that this is a bigger issue which is why I don't think it can get done at the same pace as the above, but it would be great to think about a way of solving that someday)

screenshot 1
<img width="396" alt="screen shot 2016-08-26 at 17 35 55" src="https://cloud.githubusercontent.com/assets/3143348/18011054/adaad7d2-6bb3-11e6-899d-56a616ed97ca.png">

screenshot 2
![img_2311](https://cloud.githubusercontent.com/assets/3143348/18011378/34c4e19e-6bb5-11e6-8773-301c4f31c380.PNG)

screenshot 3
![fullsizerender](https://cloud.githubusercontent.com/assets/3143348/18011501/c0d2a626-6bb5-11e6-9bb0-fd85ea723e48.jpg)

screenshot 4
![img_2313](https://cloud.githubusercontent.com/assets/3143348/18011668/6640086a-6bb6-11e6-9e17-1eb2a365fb71.PNG)

**Comment by nbogis** [comment]
I can take a look at this issue

**Comment by alicetragedy** [comment]
@nbogis awesome! I know that @katrin-k had also started looking at it (see first list item which has already been done) — can you see if you can coordinate with her so you don't work on the same thing at the same time? thanks so much for helping!!

**Comment by katrin-k** [comment]
@nbogis feel free to go ahead on both the above mentioned header/menu issues :). 

So far, I have only tried to locate the reason for the bug. My enlightenments so far: It only happens on the "Activities" page which is also the root/index page. The only difference to all other pages is that Activities has the rss-feed link. Removing it didn't help, but double-checking also doesn't hurt ;).

**Comment by nbogis** [comment]
I solved the second one. The one with the collapsed menu needs more research. I think I need to write a js function to move all the stuff down when the burger is clicked

**Comment by nbogis** [comment]
![image](https://cloud.githubusercontent.com/assets/3867533/18622269/cf5a159c-7de1-11e6-91b0-2d3c49ff894a.png)

Does this look good?

**Comment by F3PiX** [comment]
IMO: on a phone screen, the dropped down menu should confidently take over the screen, and being the main visual presence on the screen. So I would not mind if the dropped down menu would push all the other content out of the way, or blurr them or something.

One more thing. We had discussions on the navigation previously, and I - being a backender so be gentle, please  ;-) , - have the strong impression that a lot of the issues in the header are caused by the fact that we do not have implemented a proper Bootstrap navigation bar. I know because I implemented part of it. LOL Wouldn't implementing the Bootstrap navigation bar properly be a nice first step? I think it will automatically take care of most of the responsiveness issues.

**Comment by alicetragedy** [comment]
Awesome @nbogis! I agree with @F3PiX, that's totally okay for me if the menu takes over the screen/hides part of the page. So for item 3, the menu can definitely hide the sign out link, etc...

Regarding the bootstrap navigation: I was actually under the impression that the only changes that had been made were in the styling and colors and that the rest had been implemented as should, but if it's not, I agree that the way to go is to do it "properly". Maybe @nbogis or @katrin-k are interested in that.

**Comment by F3PiX** [comment]
See #380 Not sure if Ramon is working on the navbar, or only on the issues re: links. @ramonh ?

**Comment by nbogis** [comment]
ok thanks all for your insights. I didn't js file. I figured that I would just change the z-index and give more priority to the menu bar. The only problem I'm having is that sign in div doesn't look good. I will see if I can hide it without creating other issues. @F3PiX, I think this is the right bootstrap. Most of the boostrap themes have navbars on top with a big image under it so when the navbar is clicked, it covers the image and thats fine. Our case we have text which doesn't look good if they're covered.

**Comment by F3PiX** [comment]
Do you mean we have the bootstrap navbar properly installed? I have the impression we have a header with rows, where the header contains the nav items, instead of a navbar class that contains the nav items. Not true?

**Comment by klappradla** [comment]
@F3PiX from what I remember to have seen, you should be right. Bootstrap's way to go is wrapping  a navbar (e.g. using `navbar navbar-default`) around a container. For the Teams app it's the other way round: a container / row containing a `nav`element.

**Comment by ramonh** [comment]
Hey @F3PiX! I still own @katrin-k a mindmap draft for which links to use in the navbar 😅

**Comment by F3PiX** [comment]
@klappradla Thanks, that explanation is superclear
@ramonh I only meant to ask if you were working on the navbar, before someone else started to do the same works. :-)

**Comment by nbogis** [comment]
ok I will try to implement this. Another way I saw is to implement it as a dropdown menu. I tried it but things look weird on other sizes so I went with the z-index solution. I will see the bootstrap way idea

**Comment by nbogis** [comment]
I believe this issue is resolved.

**Comment by alicetragedy** [comment]
closed in https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/540
