### ISSUE TITLE
Preview function for daily student updates

### ISSUE THREAD

**Issue by izuroxx** [rails-girls-summer-of-code/rgsoc-teams#534]
@carpodaster @ramonh 
During the past weekend I've created preview function for student updates -> based on preview function for projects, which I recently finished, wanted to practice off-hours what i did in #530 .
I wanted to share this with you and ask if you would like to add this kind of feature to student updates? 

[video demo here](https://vimeo.com/181628590)

There are a few things in my current version ([my branch](https://github.com/izuroxx/rgsoc-teams/tree/student_updates_preview)), that still need fixing (like f.ex. "Back" button under preview for edit student update, that will confuse everybody), which I will fix asap.

**Comment by carpodaster** [comment]
Hi @izuroxx – that's amazing! Looking forward to it :)

**Comment by ramonh** [comment]
Super neat, thanks @izuroxx! I look forward to see how it looks! 🚀

**Comment by F3PiX** [comment]
Wow that is super cool!!!
