### ISSUE TITLE
Project Weamsite: Exploration

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#544]
Carsten's (open) notepad to evaluate the implications of a merge of the Teams App and the public website.
- [ ] Rails CMS
- [ ] Importing static pages (guides et al) files into CMS
- [ ] Importing blog posts
- [ ] MD as template engine?

**Comment by michaelem** [comment]
Hm, at the end-of-summer party in vienna we where talking about how nice it is that writing blog posts involves pull requests and so on. If they are not that familiar with git and github it provides participants a relatively low-risk environment to get going.

**Comment by F3PiX** [comment]
I agree on the goal of getting familiar with git, not sure if this is the right means. Speaking from my experience last year, the first post didn't feel at all like a 'low-risk' environment. As they are doing only 2 blogposts, one very early in the Summer: I am not sure that is the way to ease someone into git. ;-) OTOH, I am very glad that I learned so much git and gh during the summer, and I wouldn't mind if (teaching) git becomes a requirement for project proposals and/or coaching companies.

**Comment by klappradla** [comment]
Maybe a bit late to the party 🙈 
Just wanted to give my +1 for what @michaelem said about blog posts involving PRs. Therefore a minus for Rails CMS... .md as template engine would work and still provide these benefits though. However, people would probably need to run the whole rails app...

I already looked at integrating Jekyll **into** Rails. It works, but is slightly hacky and blowing up a monolith to 💥  😉 .  The most difficult and probably hackiest part is getting Rails' layouts and assets into Jekyll then - from what I remember one of the main points / benefits for merging both apps.

So maybe *"aligning"* would be a better approach? One could for instance extract key parts of the layout into a gem and use it in both apps. Gems can now have non-ruby assets, so this can almost be a CSS framework. Just some thoughts on this.

**Comment by carpodaster** [comment]
Closing this. I doubt this will be an issue anytime soon.
