### ISSUE TITLE
Offer a "login as other" user to allow filling in application as team mate in development

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#548]
In order locally test the entire application process, a 2nd user (ie. a team mate) is needed.

This feature should allow the currently logged in user to be swapped with a selected user from the listing at `users#index` – only in development.

**Comment by pgaspar** [comment]
I can take a look :+1:

**Comment by carpodaster** [comment]
Very cool, @pgaspar!

**Comment by pgaspar** [comment]
@carpodaster 1 month later, I finally had the time and headspace to seriously look at this 😞 I'm so sorry!

I have some questions:
- Is this something that should live in the orga section? Or should it be a button in `users#show` on the public section? 
  - I noticed there's no UserController in the orga section yet - I can certainly create it for this, though.
- Any idea as to how the flow for stopping the impersonation should look like?

**Comment by carpodaster** [comment]
@pgaspar no worries!

My initial thought was to put it into the public `users#index`. The main issue would be  to indicate that this is a development-mode only feature.

As for returning back to normal: I haven't given it much thought yet, no. The easiest would be just use the normal logout when the _login is as other_ just sets changes the user id in the session (or the devise equivalent of it). What do you think?

**Comment by pgaspar** [comment]
@carpodaster I think that sounds good!

I started doing a couple of things before and had something like this in the public `user#show` page:

<img width="360" alt="screen shot 2016-12-07 at 22 29 35" src="https://cloud.githubusercontent.com/assets/31735/20991216/2354bf94-bcd5-11e6-8d73-b1e3ec4e7ebd.png">

Alternatively (or additionally) I can also add a new column with a button on `user#index`.

I was thinking about using a gem like [pretender](https://github.com/ankane/pretender). I've used it before at work and it makes life a lot easier - what do you think?
