### ISSUE TITLE
404 is broken

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#562]
https://teams.railsgirlssummerofcode.org/conferences/600

When I try to access a conference that doesn't exist, I get this 404:
![schermafbeelding 2016-11-27 om 22 06 42](https://cloud.githubusercontent.com/assets/6314687/20652484/90e8b494-b4fa-11e6-9a3a-295fb962aec5.png)

instead of this:

![schermafbeelding 2016-11-27 om 22 07 08](https://cloud.githubusercontent.com/assets/6314687/20652483/859d52d4-b4fa-11e6-82cf-6e46d16a6e12.png)

**Comment by carpodaster** [comment]
Thanks for reporting this, Maud!
