### ISSUE TITLE
Add orga index

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#563]
We might eventually decide to create a small orga dashboard (which would be 👍 ), but in the meanwhile, it would be great to have a simple index for `/orga`. The thought behind it: most organisers don't really keep track of which hidden "features" are found in the dashboard controller, and since there is no menu for this anywhere, it becomes tedious to remember the URLs or look it up in the `routes` every time. Especially for people who are active organisers but not super development-savvy, it would be great to be able to access the orga pages from a simple index for now. Thoughts?

**Comment by F3PiX** [comment]
Great idea! The orga's really deserve their own dashboard. 
I think it will be super easy do: just adding a dashboard controller and view; the namespace and the base controller are in place.
The first iteration would be adding the links to the dashboard.
After that we can try to make it as cool as the supervisor dashboard.

**Comment by carpodaster** [comment]
Super goed! Yes, the orga-only items on the Teams App are totally invisible. It kinda touches #380 but a dashboard/orga-landingpage would definitely be supercool.

**Comment by klappradla** [comment]
Accidentally doing this as part of the navigation things around #581 and #380.
