### ISSUE TITLE
Frontend, JS: toggle 'Add a conference'-button

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#576]
In the user's profile, a user can select conferences to attend.
No more than 3 attendances are allowed (see #575). With more than 3 conferences selected, an  error is thrown on saving. However, the button "Add a conference" will still be present. Thus suggesting that more conferences can be added.

In an earlier attempt, we try to toggle the button depending on how many 'nested fields' are shown. 
See [this](https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/565/files/e85921e81e4a07a921a277f54bd5469c8f858c58#diff-f6d341720b72e0ebb0de6b0e55afdbf2) file and discussion. 
The [solution given in the Nested Form Wiki](https://github.com/ryanb/nested_form/wiki/How-to:-limit-max-count-of-nested-fields) looks like a good starting point but has undesirable side-effects.

**Comment by klappradla** [comment]
I think this is solved by having the new `ConferencePreference` model with only two possible associations to `Confereces`
<img width="1035" alt="screen shot 2017-08-20 at 16 30 10" src="https://user-images.githubusercontent.com/3491815/29495712-f37a702a-85c4-11e7-87ae-379165046d8c.png">
