### ISSUE TITLE
Application Form: Set character limit to some fields

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#578]
There are a few fields in the application form that are a bit too prone to applicants writing long texts, which we wish to avoid. A way to solve this would be to set a character limit on those fields.

**Implementation**
- The character limit should be set at the view level in the form
- The length should *probably* be validated at the model level as well (that would be `user` and `application_draft`)
- Each input field should contain a hint about the number of characters allowed
- *Bonus / nice to have*: character count going down as the user types (i.e. like you have on twitter) 

**The fields that need a character limit are the following:**

"Please tell us a little bit about yourself. What is your background?" (1000 characters)
"How did you get into programming?" (1000)
"Please give us a short summary of your programming skills" (1000)
"Tell us about your community involvement" (1000)
"Please summarize what you have been doing to learn programming since your first workshop" (1000)
"What do you want to achieve by the end of the summer?" (2000)
"Why are you applying to this program, and what do you think you can give back?" (2000)

**Comment by carpodaster** [comment]
@alicetragedy would it be possible to have an equal character limit for all fields? It would make it so much easier to implement.

**Comment by alicetragedy** [comment]
@carpodaster the character limits were a suggestion by @mkalininait, I'm ok with a 2000 character limit on all these fields instead of having them mixed. :)

**Comment by carpodaster** [comment]
@alicetragedy ok, perfect. The final limit can be easily adjusted (maybe down to 1500 or something?) – that's easily doable when we just flag an attribute as character-limited and define the limit elsewhere

**Comment by mkalininait** [comment]
@alicetragedy @carpodaster I'm afraid that the 2000 char limit won't let us achieve our main goal to make applications more laconic. I'd totally make the limit lower than 2000 (1500 or even 1000).

**Comment by carpodaster** [comment]
@mkalininait The concrete limit can be adjusted; the main issue here was to agree on a character limit (however high or low) that applies to _all_ fields with input limits.

**Comment by mkalininait** [comment]
Tested on Staging: if I exceed the limit in one of the fields and then validate the application, I get the following error message: "There are still some fields missing". It sounds a bit confusing.
