### ISSUE TITLE
Application Form: Set pre-defined values for “how did you find out about RGSoC”

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#580]
Right now, the `:heard_about_it` field is just a text field; having a list of pre-defined answers rather than a free-form field would allow us to have a better overview of how applicants find out about us, which is valuable information.

**Implementation**
- this list could lead either to something like a dropdown (i.e. only one possible answer) or a list of checkboxes (leading to one or more answers). Maybe the latter is preferable.

**Available Options**

Friends
RGSoC alumna
Social media (Twitter, Facebook)
Conference
Study group / Workshop
Newsletter
Other (please specify)
[additional text field for other]

**Comment by mkalininait** [comment]
I would propose to extend the list in a way, which helps us differentiate our promotion channels better. Something like this:

**RGSoC direct outreach:**
 * RGSoC Blog
 * RGSoC Twitter
 * RGSoC Facebook
 * RGSoC Newsletter
 * RGSoC Organisers

**Past participants or 'Partners':**
 * Past RGSoC participants
 * Another diversity initiative outreach
 * Study group / Workshop
 * Conference

**Other channels:**
 * Friends
 * Mass media
 * Other (please specify)
 * [additional text field for other]

**Comment by alicetragedy** [comment]
works for me!

**Comment by ramonh** [comment]
Hello! I'll go ahead and give this a go if nobody has yet

**Comment by alicetragedy** [comment]
@ramonh awesome! you can use the final list that Maria made. It doesn't need to be split into categories necessarily, those are just for us (I think).

**Comment by ramonh** [comment]
Thanks for clarifying, @alicetragedy! Just to make sure, you mean that on the actual form the student sees the categories won't be displayed?

**Comment by alicetragedy** [comment]
@ramonh yes, that's correct — I think it would be ok if it was just a list of all the options as checkboxes, without the user/student seeing what category each checkbox belongs to :)

**Comment by ramonh** [comment]
Great, thank you, @alicetragedy!

**Comment by carpodaster** [comment]
@ramonh @mkalininait @alicetragedy can we close this?

**Comment by alicetragedy** [comment]
yes :D
