### ISSUE TITLE
Application Form: Create separate view of submitted applications for mentors

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#581]
Since this year project maintainers will be more involved in the application process, they should be given access to applications submitted for their project (1st and 2nd choice applications). The best way to do so, rather than messing too much with giving access to application drafts, is to create a separate view for mentors to access (for **submitted applications** only). 

The separate view for mentors should only include answers to the following questions:
- "Short summary of your programming skills"
- "What is your programming level"
- "For how many months have you been learning the language of your primary project?"
- "Please summarize what you have been doing to learn programming since your first workshop"
- "Please provide examples of your code"
- "Project" (1st or 2nd choice correspondingly)
- "Why did you select the project?" (1st or 2nd choice correspondingly)
- "Which features are you planning to work on in the project?" (1st or 2nd choice correspondingly)

⚠️ The above fields should also have a notice or disclaimer for students in their application form to let them know that the maintainers will have access to those answers.

**Comment by mkalininait** [comment]
Depends on Issue #579

**Comment by alicetragedy** [comment]
@klappradla is this something you might be interested in working on maybe?

**Comment by klappradla** [comment]
Yeah, seems fine. I did not dive into details yet, but I'll just assign them to me then.

What in terms of deadlines does `high-priority` mean @alicetragedy?

**Comment by alicetragedy** [comment]
@klappradla high-priority means that these must absolutely be fixed by the time we open up the applications, the other ones are more like “small improvements” than anything, I think.

Regarding deadlines: I've left us a bit of breathing room there. The plan was to start testing the app on the weekend already (so ideally, with most of the bigger changes/`high-priority` issues already implemented, which is obviously not going to happen) so that we have a full week to test, and an extra week at the end as buffer. I think we should look to finish high-priority tasks/features by end of next week at the latest, so we can iron out any weird kinks if needed and still be on schedule.

**Comment by alicetragedy** [comment]
We also talked about this feature in the call last week, and I wanted to expand a bit on the issue:

The idea is to have a overview with a list of all the applications that have submitted for the project (as either 1st or 2nd choice). Clicking on a single application (e.g. team name) will take the mentor to the detailed view of the application, where the above-mentioned answers can be found. (similar to the projects overview+detailed view).

This show view should include:
- a comment box (meant as a note-taking possibility for the mentor, this needs to be clarified / explained in a description)
- picks/favs (see https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/364)

Alternatively, picks/favs should be available from the dashboard/index, not sure what makes the most sense, UI/UX-wise!

**Comment by klappradla** [comment]
Wow, thanx a million for the explanation @alicetragedy 🙏  - just perfect!

**Comment by klappradla** [comment]
Quick question @alicetragedy: should the maintainers know whether their project is the team's first or second choice?

**Comment by alicetragedy** [comment]
That's a very good question, and I'm not sure if I have an answer for this. On the one hand, I think the maintainers would be interested in knowing whether their project is in a team's first or second choice; on the other hand, I think this would probably influence the maintainer's “favourite” teams maybe? 
I think that I would be ok with providing maintainers all the information they need to make a choice: so, informing them about which teams have selected their project as a first choice project. Do you personally have any strong opinions about this, also when it comes to the implementation?

**Comment by alicetragedy** [comment]
quick (unrelated) note @klappradla: I think @carpodaster is planning to take a shot at https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/364, so there might be some overlap in your work — maybe you can talk to each other to make sure you don't do the same work twice. :)

**Comment by carpodaster** [comment]
@alicetragedy ah, good call. I was planning to create another separate view/action for this, not including the fav in any existing templates. It used to be in `projects#index` in 2015 iirc, but since we collect more info now, I'm not gonna put it there. I think we can work independently and if we have time later (rofl), we can maybe combine both views when both have been merged to master.

**Comment by klappradla** [comment]
Hm, @alicetragedy I'm not 100% sure if I understand your answer 😂  - so you mean "yes they should know wether their project was 1st or 2nd choice"?

And @carpodaster I saw you're working on this stuff and did not touch anything related to this yet. I threw in a `mentor` namespace with a respective `Mentor::ApplicationController` *(same pattern as for the other namespaces, etc)* so it's all separate.
But I can already push #579 if this is of any help for you.

**Comment by alicetragedy** [comment]
@klappradla yes, they should know. I think that's the best way to go about it 👍

**Comment by carpodaster** [comment]
@klappradla new namespace sounds good! 👍 Take your time. I haven't written any code yet and probably won't have time for it before Tuesday.

**Comment by klappradla** [comment]
Well, I'm for now skipping anything *mentor-fav* related and just add an empty column in the views, so we can then add the respective data there @carpodaster.

**Comment by klappradla** [comment]
Just to keep you updates: I'm not sure if I find the time to continue on this before Tuesday, but I pushed my current WIP state to [this branch](https://github.com/rails-girls-summer-of-code/rgsoc-teams/tree/581) *(in case someone wants to have a look / try out things)*

**Comment by klappradla** [comment]
Hm, @alicetragedy, the notes / comments part is a bit trickier than I thought: the `comment` model has a certain callback behavior for comments on both, `applications` and `teams` - I'd rather not mix in a mentor's notes here *(it would mix with orga comments, etc.)*.

There's also a `notes` model. It's eventually even more suitable, since I'd have allowed only a single comment per application for each mentor which she could then always update - just like a notes field. However, the notes are tied to supervisiors, I also don't want to cause confusion there 🙈 

Should I just add another attribute to the `note` model and still reuse it?
