### ISSUE TITLE
Application Form: Rename “Please link to pull requests”

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#582]
The description and hint of this field should be more direct, so a suggested improvement would be to rename to “Please provide examples of your code” and add the following hint: “Links to completed coding challenge provided by the mentor (if present), commits / pull requests on GitHub or other concise examples of your code. Links to GitHub profiles and repositories won't be considered.”

Alternatively, the above could be combined into a single label/description of the field, i.e. “Please provide examples of your code: links to completed coding challenge provided by the mentor (if present), commits / pull requests on GitHub or other concise examples of your code. Links to GitHub profiles and repositories won't be considered.”

**Comment by carpodaster** [comment]
Do we expect them to copy/paste entire code blobs into that textarea field? Why do we not consider external links? If the code exercise is mainly for the mentors, they will hardly be able to blindly select people anyway, right?

**Comment by alicetragedy** [comment]
@carpodaster no, it should/could still be links, sorry if the wording made it sound like we wouldn't take links. what we don't want are links to *profiles* and *complete repos*, as often they're just e.g. super basic, generated code from scaffolds in the case of Rails apps.
But I think we could change the wording to make what we want more explicit. Maybe, “**Links to** completed coding challenge provided by the mentor (if present), commits / pull requests on GitHub or other concise examples of your code.”

**Comment by mkalininait** [comment]
Good point @alicetragedy @carpodaster

**Comment by alicetragedy** [comment]
I've updated the description accordingly :)

**Comment by mkalininait** [comment]
Tested locally, looks good.
