### ISSUE TITLE
Application Form: add a community involvement section

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#583]
This would allow us to separate entirely programming skills from community involvement.

- Create a “Community Involvement” section (maybe somewhere between "Background information" and "Your programming skills")
- Move community-related fields ("Tell us about your community involvement") from the "Your programming skills" section to the newly created “Community Involvement” section.
- Add a new field "What do you think you could give back to the community?". 
- Remove the "giving back" part from the field "Why are you applying to this program".

**Comment by bitboxer** [comment]
The first question is: what is the application form? How do I get it?

Do you have a document somewhere explaining key concepts of the app and the terminology used here?

**Comment by F3PiX** [comment]
You beat me to it ;-) I am working right now on listing the steps to get there, and post them somewhere. Wiki? Readme? Slack?

**Comment by bitboxer** [comment]
I would prefer the wiki (and link it in the readme ;) ). That way other people after me will find it easily and it doesn't clutter the readme too much.

**Comment by alicetragedy** [comment]
@F3PiX I think it might be a good idea to have these concepts in the wiki, and possibly linking to them from the readme? it's quite a bit of info.

**Comment by alicetragedy** [comment]
ops, @bitboxer, you were too fast :D

**Comment by F3PiX** [comment]
@bitboxer If you are in a hurry, here is the first draft. https://github.com/rails-girls-summer-of-code/rgsoc-teams/wiki/How-to:-get-to-the-application-form.

**Comment by bitboxer** [comment]
Awesome. Thanks!

**Comment by F3PiX** [comment]
Can you let me know if this level of detail works for you, please?

**Comment by bitboxer** [comment]
Yes, it works. I am now editing the Form 👍 .

After I added the new input field here, is there a backend view that needs to be updated to show this field? Or is adding the new field in this form enough?

**Comment by bitboxer** [comment]
Ah and: is the giving back field a required field?

**Comment by carpodaster** [comment]
@bitboxer you'll find the fields required per student in `app/models/student.rb`; the validations (for context `:apply`) are in `ApplicationDraft`

**Comment by bitboxer** [comment]
Yes, I saw that. The question is: should they be required to fill out by the students in the validation? Or to be more precise: should I add the new field to the `REQUIRED_DRAFT_FIELDS` list?

**Comment by carpodaster** [comment]
Sorry @bitboxer – should have read both the initial issue text and your comment more thoroughly 🙃

I would say it's a required field, yes.

**Comment by bitboxer** [comment]
Thanks! One question left: is there another view where I have to show the new field?

**Comment by carpodaster** [comment]
No, not for now. We've just discussed in #184 that we'll remove the other option to edit per-user application info.

**Comment by bitboxer** [comment]
Nearly done. Only one thing left: what should be the text below the field that explains in detail what is expected in that field?

**Comment by mkalininait** [comment]
I have just remembered, we should probably set the char limit on the new "giving back" field (see https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/578)

@bitboxer Regarding the text below the field, I wouldn't write anything. We *could* provide some hints like: "For example: mentor newcomers in your local community, run workshops, become a RGSoC coach etc", but I would really like to give our applicants a room for independent thinking. And I definitely don't want copypasted answers. Maybe other team members have a different opinion though.

**Comment by carpodaster** [comment]
@bitboxer @mkalininait I'm already working on the char limits. Will add the flag to "giving back" once it's merged.

**Comment by bitboxer** [comment]
Okay, done.

**Comment by mkalininait** [comment]
The "Why are you applying to this program" field still contains the "what do you think you can give back?" part in the name. I guess it has happened while resolving the merging conflict (see [this here](https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/605#issuecomment-272322525))

**Comment by bitboxer** [comment]
Let's discuss this in [here](https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/588#issuecomment-273464790). No need to talk in 2 different positions about it ;)

**Comment by mkalininait** [comment]
Tested locally, looks good.
