### ISSUE TITLE
New bug with the conferences....

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#586]
The fix in #584 causes a new error locally (`NoMethodError at /users/34
undefined method 'name' for nil:NilClass`) ,  in the user/show view where the conferences are called: 
https://github.com/rails-girls-summer-of-code/rgsoc-teams/blob/master/app/views/users/show.html.slim#L53

It can be fixed by changing `@user.attendances.includes(:conference)` into `@user.attendances.joins(:conference)`  
I can submit this fix as well.
Or do we need another approach?

**Comment by F3PiX** [comment]
Reproduce the bug:
In dev env:
- Click 'Community'
- Select user with conference (I add conferences to my own profile from the user profile page)
- Error occurs

I can't reproduce it in the production. I selected a user who has a conference on her profile, and it shows the profile and the conference as expected:
https://teams.railsgirlssummerofcode.org/users/621

**Comment by carpodaster** [comment]
Thanks Maud. PR is up!
