### ISSUE TITLE
Application Form: Blind selection warning

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#587]
In 2016 the blind phase of the selection process wasn't really blind. Although we asked the students not to mention some of the information in certain fields (e.g. location), we still could sometimes tell from the writing where the student comes from (mentions of workshop names, university names etc.)

**Possible solution**  
After the block "Basics" and before the block "Background Information" put a warning, something like: "In your answers below, please don't mention names (geographical features, universities, companies etc.) which can point to your location and introduce bias during the selection process!".

**Comment by F3PiX** [comment]
I added the warning to the Application Form. 

![schermafbeelding 2017-01-09 om 18 30 49](https://cloud.githubusercontent.com/assets/6314687/21776257/faa3863c-d699-11e6-827d-2b0e5de1fa83.png)


Am I right that it is meant for both the "Tell us about you" and the "Programming Background"? Not for everything after the Basics? 

(Note: I didn't add the warning to the User Profile fields, because I suppose we are going to do a shared partial, right, @carpodaster?)

**Comment by mkalininait** [comment]
@F3PiX Actually this warning applies to *all* fields after the "Basics" section. I should have specified this more explicitly :/

I was thinking that we could make a warning like this, so that it's super visible:
![warning-app-form-2017](https://cloud.githubusercontent.com/assets/1745735/21803580/ee822c82-d72a-11e6-990d-544d13415fd6.png)

We don't need such a warning in the User Profile, because we don't look into user profiles during the blind phase of selection.

**Comment by carpodaster** [comment]
> We don't need such a warning in the User Profile, because we don't look into user profiles during the blind phase of selection.

@mkalininait this only means that there are two ways of _filling out_ the info. It's not visible on a user's profile anyway. It's subject to removal (see #184).

The color of the info box should probably be yellow/orange instead of blue.

**Comment by mkalininait** [comment]
@carpodaster @F3PiX I had something like this in mind
![warning-2-app-form-2017](https://cloud.githubusercontent.com/assets/1745735/21804008/1c4cc7ba-d72d-11e6-982a-d61775c8d4ce.png)

**Comment by mkalininait** [comment]
We should also remove the same warning from the name of this field: "Why are you applying to this program?"  since we have one global warning now.

**Comment by mkalininait** [comment]
@F3PiX Thanks!

**Comment by mkalininait** [comment]
Tested locally, looks good.
