### ISSUE TITLE
Application Form: Remove "Learning period since your 1st workshop"

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#588]
In 2016, the field "For how many months have you actively been learning after your first workshop?" was confusing for students who didn't attend a 'benchmark' workshop. It also didn't help us a lot during the selection process.

**Suggested solution:**  
 - Remove the field "For how many months have you actively been learning after your first workshop?".
 - Rename the field "Please summarize what you have been doing to learn programming since your first workshop"  to "Please summarize what you have been doing to learn programming".

**Comment by bitboxer** [comment]
Will do this after #583 is finished

**Comment by bitboxer** [comment]
Should I also remove the field from the database? Or should it stay in there?

**Comment by carpodaster** [comment]
> Should I also remove the field from the database? Or should it stay in there?

I'm 80% in favour of removing it. The remaining 20% are doubts about mingling with existing `ApplicationDraft` records. otoh, we do have the lodged `Application` with all data and past students aren't able to browser their old draft anyway. So yeah, let's remove it!

**Comment by bitboxer** [comment]
Okay, will do tomorrow!

**Comment by mkalininait** [comment]
Weird, but I don't see the "Please summarize what you have been doing to learn programming" field, neither on Staging, nor locally. I see that it has NOT been deleted in the associated PR (#602). I'm wondering where is has gone and why. 
I'm writing it here, because I'm not sure where to write it.

**Comment by bitboxer** [comment]
It was deleted in [this merge](https://github.com/rails-girls-summer-of-code/rgsoc-teams/commit/f196d01e6c2c50097195cdb150401ace89bc2ca1#diff-d45e18661240fe214cc441821264339dL45). 

@carpodaster can you confirm? I can add that line back, but I think it is better that you check if anything else is strange in that merge.

**Comment by carpodaster** [comment]
@bitboxer @mkalininait It may indeed have fallen victim to me using a new `git mergetool` (meld on Ubuntu instead of opendiff on Mac). Would be great if you could add it back, thanks!

**Comment by bitboxer** [comment]
Also there are other things missing. Quoting from (here)[https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/583#issuecomment-273465910]:

> The "Why are you applying to this program" field still contains the "what do you think you can give back?" part in the name. I guess it has happened while resolving the merging conflict (see this here)
>
> We also forgot to fix the placeholder text of this field: "This is my 750 word essay. I'm applying to this program because it's awesome, and I think I can give a lot back. I will not share information about my age, name or location."
> Should be: "This is my essay. I'm applying to this program because it's awesome. I will not share information about my age, name or location."

**Comment by bitboxer** [comment]
I am now a bit confused what is missing/wrong. Not easy to tell by the pr 😢

**Comment by bitboxer** [comment]
Will try to do my best now.

**Comment by bitboxer** [comment]
@mkalininait what do you mean with the "750 word essay" text? I can't find it in the application. Can you say where it is so that I can fix it? Thanks!

**Comment by mkalininait** [comment]
@bitboxer Apparently, I was wrong, it was not a placeholder, but a custom text which looked like a placeholder :/
![screen shot 2017-01-18 at 20 04 09](https://cloud.githubusercontent.com/assets/1745735/22078814/b05d0f5e-ddb9-11e6-825b-c29168e1af7b.png)

I don't see this text locally. Sorry for the confusion.

But the name of the field "Why are you applying to this program" seems to be wrong still, unless someone has fixed it quickly.

**Comment by bitboxer** [comment]
Yes, the text will be fixed in pr #622

**Comment by mkalininait** [comment]
Tested locally, looks good.
