### ISSUE TITLE
Application Form: "Gender" autocomplete

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#591]
To make it a bit easier for us to process applications we decided to make an improvement over the field "Gender". We've been thinking a lot about how to implement a new/better “Gender Self-Identification” field so that on the one hand it had some pre-defined options and on the other hand wasn't exclusive for anyone. The majority voted for the following solution.

The Gender field should look like a simple text field with autocomplete (similar to how we have the license autocomplete for project submissions). It can look like this:
![gender](https://cloud.githubusercontent.com/assets/1745735/21742349/1962c33e-d4ed-11e6-8e2f-08261fbb3dfe.jpg)

Here is the list of gender options on Facebook, we could use it for starters or find a different one: http://alphabetizer.flap.tv/lists/list-of-facebook-gender-options.php

**Comment by alicetragedy** [comment]
I'd love to take a shot at this. :)

**Comment by alicetragedy** [comment]
My proposed list to choose from for now: "Agender", "Bigender", "Cisgender Woman", "Gender Fluid", "Gender Nonconforming", "Gender Questioning", "Genderqueer", "Non-binary", "Transgender Woman". (we can always expand on it if needed, this list specifically leaves out “Cisgender Man” as requested by Anika). 

The field should give the possibility to choose from the above mentioned list, or to add your own (like in a “normal” input field) if your preferred option is not available.

**Comment by carpodaster** [comment]
Fixed in #631

**Comment by mkalininait** [comment]
Tested locally. Looks good!
