### ISSUE TITLE
Application Form: "Diversity" field

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#592]
Our program aims at supporting diversity, and at the same time we don't have a special field for this on the application form. It would be great it we could support not only female/non-binary/trans people, but also take other special life circumstances into account.

**Possible solution:**  
Add an extra text field next to the gender field, something like: "Please tell us about any special circumstances which you want us to consider while reviewing your application (e.g. LGBTQI / people of colour / people with disabilities / single parents / people taking care of family members etc.)”. 

Of course, people should share only what they feel comfortable sharing.

**Comment by anikalindtner** [comment]
plus one for the diversity field

**Comment by alicetragedy** [comment]
+1 from my side as well

**Comment by mkalininait** [comment]
Tested locally, looks good.
