### ISSUE TITLE
create student dashboard

### ISSUE THREAD

**Issue by katrin-k** [rails-girls-summer-of-code/rgsoc-teams#60]
Arne came up with the idea to have a dashboard providing a fast look at the latest acitvities in all coached/mentored/supervised teams to help realise when a team gets stuck. 

Below's a first sketch on how a dashboard could look like:

![draft rgsoc teams app dashboard](https://cloud.githubusercontent.com/assets/164400/16706834/af5f7362-45bb-11e6-839d-1fb073743e35.png)

**Comment by carpodaster** [comment]
Possible duplicate of #109 ?

**Comment by carpodaster** [comment]
Continued in #462
