### ISSUE TITLE
Mobile optimisations for projects

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#600]
Currently these items do not work properly on mobile:

* The "soft" login required on /projects/new
* The `/projects` index
* The table at the top of a project's detail page (projects#show)

Any frontend wizard/witch who can take on this?

**Comment by carpodaster** [comment]
@katrin-k maybe? 😁

**Comment by alicetragedy** [comment]
I'd be up for looking at it later this week if Katrin is not available! ✌️

**Comment by katrin-k** [comment]
@alicetragedy yeah, it'd be great if you could take care of this. thanks <3

**Comment by alicetragedy** [comment]
@carpodaster this is almost done (see https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/608) — the only issue I have right now is that my development environment shows no problems with the projects#show view, so I have no idea how to fix this problem in production 😢
