### ISSUE TITLE
User Profile: tech fields for all users

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#612]
This issue originates from this one: https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/593

We would like to have more information about user technical skills primarily to make it easier for students and coaches to find each other.

**Suggested solution:**
Add the following fields (all required):
- "Technologies of expertise” - tags separated by comma (similar to the "Tags" field in Project)
- "Technologies of interest” - tags separated by comma (similar to the "Tags" field in Project)

**Comment by Anagha22** [comment]
Hey, we are team Bundledore, we would like to work on this issue.

**Comment by Anagha22** [comment]
I have submitted a PR for this issue . Please suggest changes if any.

**Comment by Anagha22** [comment]
I have submitted the PR with all the changes mentioned. Please review it.

**Comment by mkalininait** [comment]
Hi @Anagha22 Both of your PRs are closed. Are you going to make another one? I'm confused.

**Comment by Anagha22** [comment]
@mkalininait Yeah, sorry for the delay, I got some technical issues. It's fixed now. Will send a PR soon.

**Comment by branquinhoaa** [comment]
I'm not sure if this will be done by @Anagha22 or if I can take it. It is part of the community milestone, I would like to do if she won't. :smile:

**Comment by branquinhoaa** [comment]
@klappradla  do you think this issue can be part of our community milestone?

**Comment by klappradla** [comment]
Sure 👍  Good point!

**Comment by branquinhoaa** [comment]
@mkalininait do you want to show the technologies fields in the user page? or this info will be there just for search?

**Comment by klappradla** [comment]
Regarding the layout I already left some comments in #863 

For whether or not the fields should be mandatory:
I see some difficulties here...
1. From a technical perspective: it would make all existing user profiles invalid 🙈. I know we had something similar with the "city" or "country" field one, but I don't remember how we solved it...
2. From a human perspective: we may eventually insult or scare off groups of people unsure about the level of their knowledge and experience by "forcing" them to come up with some technologies and languages they are experienced in...

Maybe we have to come up with "softer" approaches to get this data. I could for instance imagine adding a reminder to fill out the profile information into the confirmation email or showing a friendly reminder when a user without a filled out profile logs in... there are several possibilities.

**Comment by klappradla** [comment]
Closed via #863
