### ISSUE TITLE
Improvements to the help page

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#614]
The help page(s) for students were a bit confusing last year, so we should definitely review and improve them (especially if some things have changed in the application process) before the open the applications. This includes:
- [x] review “How to create an account” and “how to fill out your application” pages
- [x] review text on the main help page
- [x] make a link to the help page more prominent?
- [x] improve headings and structure of the help page 
- [x] improve “how to confirm your coach status” (add screenshot for coaches to confirm themselves, improve wording)
- [x] add page “how to contact your mentor” (could also be part of “how to fill your application”) — with screenshot of where to find user information
- [x] add instructions about how to add coaching company info to application form (i.e. needs to be added to the “Anything else to add?” field, cannot be named, can also be added to coach profiles and named there if necessary)

**Comment by mkalininait** [comment]
> make a link to the help page more prominent?
Oh yes! I had to google to find it on the website :D 
I think the link should be on the Nav bar.

**Comment by carpodaster** [comment]
I'm closing this. The help page looks waaaay more informative now and the link to it is more prominently positioned.

**Comment by alicetragedy** [comment]
Also: add instructions about how to add coaching company info to application form (i.e. needs to be added to the “Anything else to add?” field, cannot be named, can also be added to coach profiles and named there if necessary)

**Comment by alicetragedy** [comment]
@mkalininait taking over this, as discussed this morning — if there is any work you've already done and/or committed, let me know, you can maybe push it to a branch so that I can take over easily?
