### ISSUE TITLE
Possible security problem in Orga::ExportsController

### ISSUE THREAD

**Issue by bitboxer** [rails-girls-summer-of-code/rgsoc-teams#615]
In the ExportsController we have this starting at line 10:

```
exporter, meth = params[:export].to_s.split('#', 2)
csv = exporter.constantize.public_send(meth)
```

Instead of constantizing a random user input and calling a method on it, we should check against the whitelist that is generated in the `available_exports` method in that class to prevent a security problem.

**Comment by carpodaster** [comment]
Thanks for spotting this! Impact is very low since only Orga-people have access to that controller currently. It's still a bug 🐛

**Comment by bitboxer** [comment]
Yep, that is true. And this is the only place in the codebase that is using `constantize`. When I fix this I will also run brakeman to check if it finds other problems just to be on the safe side.

**Comment by bitboxer** [comment]
I checked with brakeman and also fixed 2 other minor things. Brakeman also found a few unscoped calls to the `find` method of models, but I think in those cases it is okay to do them. There are two things marked as `high` that I am not sure if and how we want to fix them: 

The `AttendancesController` has redirect_to's to an url you can define in the parameter (see why it warns about them [here](http://brakemanscanner.org/docs/warning_types/redirect/) ). Ideally we would check if the redirect_to is not going to another site using a fixed list of domains or check if the urls are only relative and not absolute.

**Comment by carpodaster** [comment]
About the `params[:return_to]`: It only appears in `app/views/users/show.html.slim` and from what I get, we could easily ditch the param and to for a `redirect_to :back`

**Comment by bitboxer** [comment]
I was worried that the static site (or something else) links to it with a specially crafted `:return_to` url. If this isn't the case, then a `redirect_to :back` would be totally fine. If you can confirm this, I will create a PR to fix this.

**Comment by carpodaster** [comment]
I am positive external links aren't an issue: it's the `users#show` page, meaning the linking page needs a user's id to create the route. It's also a `PUT` request which is even harder to construct from the static site. I say: let's kill it with 🔥
