### ISSUE TITLE
Bug: "My Team" button opens wrong page

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#621]
I have two teams in different seasons: 2016 and 2017. The "My Team" button opens the team of 2016 for some reason.

![myteam](https://cloud.githubusercontent.com/assets/1745735/22079333/be95bd9e-ddbb-11e6-995e-6a2b35831d6c.gif)

**Comment by Nada1996** [comment]
@mkalininait I think the problem is in the definition of current team
`  def current_team
    @current_team ||= current_user.teams.first
  end`
and on your profile ,it seems like the teams are sorted by chronological order, so if I wasn't mistaken, this makes "Team Rackless pinguins [2016] " the first team , therefore = @current_team
`link_to 'My Team', current_student.current_team, class: 'btn btn-default btn-sm' if current_student.current_team`

Hope this helps 😃

**Comment by mkalininait** [comment]
@Nada1996 Cool, I think that's the problem! Thank you for the investigation 👍

**Comment by Nada1996** [comment]
I hope that this solves the issue.
I'm glad to help 😃

**Comment by mkalininait** [comment]
@Nada1996 Would you like to make a pull request? If you have time of course. Investigation is often the hardest part, and you already did it :)
Otherwise we will make it, not a problem either.

**Comment by Nada1996** [comment]
@mkalininait yeah sure, I'll start working on it 👍

**Comment by mkalininait** [comment]
@Nada1996 I've just noticed the following thing: in my application draft, on the "About your pair" tab, I see my partner from 2016, not the current one, too. Will the currently submitted PR resolve this issue, too?

**Comment by carpodaster** [comment]
> UPD: It's actually not just the partner. The whole application draft is of 2016, and not the current one.

@mkalininait that sounds like a different problem. This sounds like one of the problems that Maud described in #611

**Comment by carpodaster** [comment]
As for the original bug report: what is our expected behaviour for the "My Team" button, considering one can be part of more than one team (past and present)?

Can we just remove it or a "My Team(s)" item to the nav bar that leads to a filtered `teams#index` with only those teams I am part of?

**Comment by mkalininait** [comment]
@carpodaster Sorry for not replying earlier, I've missed this comment somehow.

The initial idea was that the "My team" button opens my team in the current season. You are right that some people can be part of multiple teams, for example coaches. Although it's not a very popular case, we should take it into account, too.

Your solution sounds good to me. Maybe we can even add this filter to the teams page explicitly:
 * [ ] My Team(s)

**Comment by mkalininait** [comment]
When I make a status update (daily log), it also assigns to my last year's team. Writing it here just in case all these things are related; will write the same in #611.

**Comment by mkalininait** [comment]
Ok, the team ProdyoGEEKY (Padawans in 2016) have the problem mentioned in the comment above :( They can't write daily logs.

**Comment by juuh42dias** [comment]
@mkalininait button disabled too? I'll see this problem...

**Comment by mkalininait** [comment]
@juuh42dias No, there is actually another problem. The students have two team, because they applied twice: in 2016 and 2017. They have been accepted this year. Now when they try to write daily logs, the logs get associated with their team of 2016.

**Comment by mkalininait** [comment]
The issue is fixed for the moment. I've also created a related issue #790.
Closing this one.
