### ISSUE TITLE
Bug: can't save an application draft

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#629]
When I try to save an application draft, I get this error: 
"Validation failed: Country can't be blank"

![save-app-draft](https://cloud.githubusercontent.com/assets/1745735/22226888/aa051292-e1c8-11e6-8d14-c1acc1f83c4d.png)

This happened because the Location field in my User Profile was not filled out (it was not required before https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/593). 

We should show a normal error message on the application draft edit form in case some fields in associated User Profiles are missing.

**Comment by alicetragedy** [comment]
I think the biggest problem, as a user/student filling out the application, is that I don't have this information (some fields are missing!) before filling out the draft, and may risk losing information I've added to the application form. 
I think there are two ways in which we could solve this:
- force all users that have a profile not filled out correctly to fill it out before they can even create an ApplicationDraft (which is anyway consistent with what we want)
- show a note at the top after creating a new ApplicationDraft if the user has an incomplete profile (e.g. “Your user profile seems to be missing some fields, you will not be able to save this draft unless you fill them out”). I think this note might be a little cryptic though.

**Comment by carpodaster** [comment]
Another possible option could be to only validate the country when an application is submitted. This has he implication that we only require this for students / applicants, not mentors and coaches. The pro side would be that it's the least obtrusive approach.

**Comment by mkalininait** [comment]
Just to make it accurate, this bug applies to the following User Profile fields: Email, Country, City.

![screen shot 2017-01-31 at 00 22 42](https://cloud.githubusercontent.com/assets/1745735/22446202/b84e56c8-e74b-11e6-9e61-2f64794c5e69.png)

**Comment by alicetragedy** [comment]
@carpodaster if I understood correctly, this is not consistent with the changes made to force users to fill out their user profiles. (all users are asked to fill out their location and other fields upon registering). Do you see value in changing this though? 
One other point: we **need** to have the locations of coaches when the application is submitted, as this is part of what we rate applications on (though not a hard requirement).

**Comment by carpodaster** [comment]
@alicetragedy yeah, you're right.

I fiddled with the validation error locally yesterday night after my comment on this issue. I am more in favor of either redirecting to the user profile directly (the unpolite, but easiest approach) or add an intermediate step where an applicant can edit their profile in-place (the more convenient, but also slightly hackier way).

**Comment by alicetragedy** [comment]
Connected: https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/635
