### ISSUE TITLE
[feature request] add new tag “in review” to projects overview

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#633]
Currently, when reviewing projects we only have 3 states available: “proposed”, “accepted” and “rejected”. Usually reviewing projects is pretty straight forward and we can make decisions right away, but in some cases, I found myself needing to check something with the maintainers (it usually takes a couple of days) or asking for feedback from the rest of the team, and then moving on. As I usually review projects in batches, I sometimes forget which projects I've commented on or am waiting for an answer from; this leads to me clicking projects I've already partly “reviewed” when I go through new applications. Maybe a new tag or state could be added to at least give me some visual aid? 
I could imagine that a yellow tag would fit well with the current tags we have for project status :)

**Comment by alicetragedy** [comment]
Hey @techchic, sorry for not getting back to you on this one — I was about to reply with some clarifications on the feature last Friday, but then I saw the PR :) @carpodaster has already reviewed it, so once you make the necessary changes, I can take a look at it as well. Thank you for your interest and for your contribution! 👍

**Comment by techchic** [comment]
@alicetragedy Thanks for the response @carpodaster thank you for your feedback.Lemme work on the changes and send another pull request.

**Comment by alicetragedy** [comment]
@techchic quick tip: if you stay on the branch you created to make the first pull request (`pending-tag` in your fork), you should be able to make the changes there and push — that way, you won't have to create a new PR, the changes will be added automatically to your current PR ( #668 )
Let me know if you need any help with that :)

**Comment by alicetragedy** [comment]
Hey @branquinhoaa, I think you expressed interest in working on this with your team mate Juliana. Please go ahead if you're interested, your mentor @carpodaster should be able to answer any questions you might have :)
