### ISSUE TITLE
Sore thumbnail :-)

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#643]
I use the github avatar and this happens with the thumbnail in the navbar

![schermafbeelding 2017-02-05 om 19 40 47](https://cloud.githubusercontent.com/assets/6314687/22628820/3c530854-ebdb-11e6-9e7b-7e0fd7ab9a87.png)

**Comment by alicetragedy** [comment]
Ouch.

**Comment by alicetragedy** [comment]
@F3PiX can you give any other details, e.g. if this happens in a specific browser or in all of them, is this on staging, production, locally... or everywhere? 
I'm sorry you have to see this, it's a little big 😂😳

**Comment by mkalininait** [comment]
I had the same bug :) MacOS Sierra 10.12.3, Google Chrome Version 55.0.2883.95 (64-bit).

![screen shot 2017-02-06 at 12 17 15](https://cloud.githubusercontent.com/assets/1745735/22691203/93933454-ed39-11e6-95e6-16f58114d51c.png)

How it happens:
 1. I added **@mkalininait-test** to my team; this user didn't exist in the DB yet.
 2. **Then** I logged in as  **@mkalininait-test** and got this sore icon.

The icon looks fine if you sign in for the first time without being added to a team.

**Comment by mkalininait** [comment]
With a different user @unknownuser365 I get a huuuuge thumbnail whatever way I sign in... just as F3PiX describes. So weird.

**Comment by alicetragedy** [comment]
This should have been fixed with https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/654 🎉 
@F3PiX, can you confirm and close the issue if it's fixed? thank you!

**Comment by F3PiX** [comment]
🎉
