### ISSUE TITLE
GitHub ribbon causes vertical overflow of body

### ISSUE THREAD

**Issue by untitaker** [rails-girls-summer-of-code/rgsoc-teams#644]
On Firefox 51, the GitHub ribbon causes a vertical scrollbar for the entire page. After scrolling sideways to the right:

![2017-02-06-181144_280x298_scrot](https://cloud.githubusercontent.com/assets/837573/22657737/ce4fa4da-ec97-11e6-8750-e81d079a317d.png)

**Comment by carpodaster** [comment]
Thanks, @untitaker, for reporting this.

@klappradla @alicetragedy could this be a side-effect of the new navigation bar?

**Comment by untitaker** [comment]
If I delete the `.ribbon` element this issue is gone, IIRC the problem has been there before too.

**Comment by klappradla** [comment]
Oh thanx @untitaker 💚  - that has to to with the new navigation, you're right @carpodaster. I had to adapt some of the styling, since the old ribbon was not *"bootstrap-confirm*". I'll get Firefox and take care of this *(unless it's super urgent)*.

**Comment by klappradla** [comment]
Hm, to be honest, I'd prefer to fix this issue by just replacing the current approach with an adapted version of [this one](https://github.com/simonwhitaker/github-fork-ribbon-css) - it's simply the best 💚 
The one we currently have uses an approach [like this](https://codepen.io/hmps/pen/kiFum), which results in overflowing edges and is way harder to fix than just using a single `a` tag.

I'm way too tired now, but I'll find time during this week I think.

**Comment by alicetragedy** [comment]
Sounds good @klappradla. Thanks for looking into it!
