### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#646]
Today we got a message from a student on Slack: "Hi. My team member is trying to log in with her GitHub account for the first time on RGSoC website. However, she is not receiving any activation email or getting signed in."
 * [Team Pixelate](https://teams.railsgirlssummerofcode.org/teams/299)
 * [User Aqsa Ahmed](https://teams.railsgirlssummerofcode.org/users/1554)

------
I faced the same issue testing the app locally:
 - Tried to log in as @mkalininait-test, failed
 - Opened the profile of @mkalininait-test, didn't find anything special about it

![cannot-sign-in](https://cloud.githubusercontent.com/assets/1745735/22716457/6767f402-ed96-11e6-9ca2-d83a77dc151e.gif)

Can't reproduce it on Production though.

**Comment by mkalininait** [comment]
Closing as a duplicate

**Comment by Aastha23** [comment]
I am also facing a similar issue. I haven't received a confirmation mail yet.

**Comment by mkalininait** [comment]
Hi @Aastha23 I've fixed your account on the Teams app. Please check your mailbox, you should get an email to confirm your email address.

**Comment by Aastha23** [comment]
Thanks a lot!!!
