### ISSUE TITLE
Hide the “Submit a Project” button on the projects list

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#658]
We should probably show this button only during the Project Submission phase. The same applies to the "Submit your Project" link on the Nab Bar. 

![screen shot 2017-02-10 at 13 21 11](https://cloud.githubusercontent.com/assets/1745735/22826691/ed5951b0-ef93-11e6-8115-9f89f1dbd366.png)

**Comment by alicetragedy** [comment]
@mkalininait the “Submit Your Project” link in the navigation bar only shows during the project submission phase, so it should be alright as is.
+1 on removing the other button.

**Comment by mkalininait** [comment]
@alicetragedy Ah, ok, thanks, I wasn't sure about it.
