### ISSUE TITLE
User confirmation: the "Resend" button

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#673]
When user email address is not confirmed, we should display a warning about this with the “Re-send confirmation” button which triggers sending an email with a confirmation token.
**UPD from Bodo:** "we can add that to all pages to the top right below the navbar. that way no user can say that they haven’t seen it :slightly_smiling_face:"

**Context:** many users don’t get confirmation emails. In some cases we send them, but they don't reach users and in some cases we don’t even send them. I can’t say in which cases specifically we don't send emails, this needs to be tested thoroughly. But the Resend button would be a sufficient hot-fix for such cases for the moment.

**Comment by bitboxer** [comment]
I added a PR for this. In that I also change that if a user has a incomplete Profile, that user is automatically redirected to the profile edit form. Just to be sure.

**Comment by mkalininait** [comment]
Hey @bodo, thanks for your work! A couple of comments from my side:

1) I think you sent your PR to bitboxer/rgsoc-teams, not to rails-girls-summer-of-code/rgsoc-teams

2) Just to clear this up: do we redirect a user to the profile edit if she filled out her profile, but didn't confirm her email address?

**Comment by bitboxer** [comment]
For 1: this is fixed now.
For 2: No. We only redirect if the user is not valid or was just imported using the github data import.

**Comment by mkalininait** [comment]
@bitboxer That's clear, thank you!
