### ISSUE TITLE
Show all info about a season on season's “show” page

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#676]
Currently, the season's show view looks like this:
<img width="1192" alt="screen shot 2017-02-27 at 10 42 32" src="https://cloud.githubusercontent.com/assets/3143348/23356277/84fbad22-fcd9-11e6-98d8-e6034d55dd3d.png">

In order to view all information about a season's application opening and closing dates, we need to go into the edit view (see below), which is unpractical. 

<img width="1409" alt="screen shot 2017-02-27 at 10 36 09" src="https://cloud.githubusercontent.com/assets/3143348/23356349/c94d5b92-fcd9-11e6-9864-f6429eeca2d0.png">

I'd suggest having all important season dates in the season “show” view directly.

This should be a fairly quick fix, even for someone not extremely familiar with the Teams App architecture. :)

**Comment by amrtanair** [comment]
Heyy, I'd love to work on this. I am applying for this years RGSoC, this seems to be a good task :)

**Comment by amrtanair** [comment]
Sent another PR with the requested changes. Please let me know if I should change anything else :')
