### ISSUE TITLE
Team's name can't be blank

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#679]
NOTE: I thought we had this issue from the last years, but I can't find it anymore; sorry if this issue is a duplicate.

Now one can create a team without a name. We should make the Name field required. 

This is not only confusing, but also can cause bugs, e.g.:
 * https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/678
 * https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/667

![joxi_screenshot_1488201548078](https://cloud.githubusercontent.com/assets/1745735/23384058/7e6213fa-fd49-11e6-9302-e60c32b7db91.png)

**Comment by carpodaster** [comment]
Done in #681
