### ISSUE TITLE
Show a better error page during outages or maintenance

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#686]
Heroku gives you [the possibility](https://devcenter.heroku.com/articles/error-pages#customize-pages) to create custom error and maintenance pages. While I've never done that, maybe we could look into doing it? With the recent AWS outage, the site was down for a while and showed a page that was not particularly informative. We also [got a tweet](https://twitter.com/untitaker/status/836696176657330182) suggesting a better / more informative page.
I don't think this is particularly pressing, but does anyone see value in doing it? Would love for everyone's thoughts on this.

**Comment by carpodaster** [comment]
Ironically, the howto illustrates uploading the custom error page to … wait for it … Amazon S3 😂 It wouldn't have done us any good during the recent outage.

I wouldn't bother. Sure, if anyone wants to get their hands dirty with this (dirty is meant in a positive fashion I might add), we can upload a custom one. The application error one is probably what we need, I don't recall having switched on maintenance mode for the Teams App over the course of the last years. Otoh, it's indeed not very pressing and just a minor issue and I wouldn't like to have this open linger for months on end just in case someone wants to grab it.

**Comment by alicetragedy** [comment]
@carpodaster it seems like during the outage Heroku was showing a “maintenance” page (which is a bit confusing). I understand your reasons, so we can close this issue if no one wants to pick up this task and work on it. I know how you feel about long issue lists ;)

**Comment by carpodaster** [comment]
> it seems like during the outage Heroku was showing a “maintenance” page (which is a bit confusing)

Maybe they changed their plattform during the S3 outage to show a Heroku-provided maintenance page since they knew no custom S3 error pages would load?

`/shrug` 

I'm voting to close this. Is that ok with you, @alicetragedy ?

**Comment by alicetragedy** [comment]
👍
