### ISSUE TITLE
Export of applications 2017 doesn't work

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#690]
https://teams.railsgirlssummerofcode.org/orga/exports

 * Exporters::Applications#applications_2017
 * Exporters::Applications#applications_current

Error 500

**Comment by carpodaster** [comment]
@mkalininait it's a deleted team again 😢  I've pushed a changed that should fix it. Can you verify it once it's deployed?

**Comment by mkalininait** [comment]
@carpodaster It works now, thank you!
