### ISSUE TITLE
Link to All Projects on the project page

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#693]
1. Open a project from the list `/projects/`
2. The link 'All projects' leads to `/orga/projects` (which is unavailable for everyone but the organizers)

![joxi_screenshot_1489480426269](https://cloud.githubusercontent.com/assets/1745735/23892316/5599be62-089a-11e7-9eb6-079c3c2da8c2.png)

**Comment by carpodaster** [comment]
The link's target is based on the user's role. It was an explicit feature request and was added in 144c4487

**Comment by mkalininait** [comment]
Thank you for the link @carpodaster 
This logic still looks a bit non-transparent to me. As a user, I'd expect to return back to the list where I came from. Especially because those two lists contain very different information about the projects.
Maybe one day we can make breadcrumbs everywhere.

**Comment by carpodaster** [comment]
@mkalininait I totally agree, Maria. I prefer to have all admin-related stuff in the admin namespace and ideally have every role see the same thing – or don't allow access altogether. We've had this confuse us before.

@alicetragedy wdyt?

**Comment by alicetragedy** [comment]
@carpodaster @mkalininait I'm ok with making this change. At the time, we didn't have a place from where orgas could access all their different links, and during the project reviewing phase, it was easiest to deal with getting back to the main project page that way :)
Also +1 on the breadcrumbs.

**Comment by carpodaster** [comment]
You are absolutely right, @alicetragedy  – we didn't have our shiny dashboards at that time. I've reverted the change in 7afdbd78559f0629334579580284fbdc65f1b827
