### ISSUE TITLE
Locations in the list of teams is in duplicates

### ISSUE THREAD

**Issue by amrtanair** [rails-girls-summer-of-code/rgsoc-teams#711]
For example, if the students are from the same place and have entered the location in a different fashion(say, one has entered it in capitals while the other has not). 

Image attached below: 
![whatsapp image 2017-03-26 at 9 34 55 am](https://cloud.githubusercontent.com/assets/16919437/24328451/9a90e772-1207-11e7-9126-b42742b9b576.jpeg)

**Comment by amrtanair** [comment]
Can I try tackling this issue?

**Comment by beanieboi** [comment]
@amrtanair that would be really cool! I'm happy to help if you have questions.

**Comment by F3PiX** [comment]
Hi @amrtanair ! I take it you are not working on this, so I assigned myself. If you do want to take this on, please unassign me and assign yourself!

**Comment by amrtanair** [comment]
Hi @F3PiX  ! I am sorry I took so long to reply. I am currently working on another project for RGSoC'17 and I would love to solve this issue. it kinda was on the back of my head, but I never got around to working on it :( If you want to, do go ahead, else just notify me and I will make it a point to resolve it :')

**Comment by F3PiX** [comment]
@carpodaster I'd like to add the very cool [geocoder gem](https://github.com/alexreisner/geocoder) as a starting point for solving this. Is that okay?

**Comment by carpodaster** [comment]
@F3PiX Why do you think we need exact geocoords? I'm not against geocoder, but I don't currently see why we would need it to de-duplicate locations. Your solution in #807 seems like the better approach to me.

**Comment by F3PiX** [comment]
Apart from  all the cool things we can do with it... 
The solution on #807 works, given the user input is correct. If someone enters a city incorrect, or one student calls their city "Beijing" and the second student "Peking", we can't catch that now. With geocoding we get one unique name.
(We do not need the geocoder gem for that, Max already introduced geocoding for the application forms, but the gem offers a lot of possibilities. )

**Comment by F3PiX** [comment]
Hmmm either way, it is probably a bad idea to do this mid-season. 
Closing this, and I'll check back in after summer.
