### ISSUE TITLE
Cleanup Rating - Application reference

### ISSUE THREAD

**Issue by beanieboi** [rails-girls-summer-of-code/rgsoc-teams#726]
Right now the ratings tables has 2 possibilities to reference an application.

you can reference an application using the polymorphic `rateable` association (`rateable_type` and `rateable_id`) or you can use `application_id` directly.

We should settle on one style of connecting applications and ratings, either via `rateable`  or `application_id`

**Comment by klappradla** [comment]
Yes, voting for `application_id` - this will however mean, that last / this season's ratings aren't compatible with the schema any more. But I don't think this should be a problem, the whole process changes over time anyways.

**Comment by carpodaster** [comment]
I stumbled over this inconsistency today myself. I also +1 `application_id` – we probably only ever rate applications, no other model.

**Comment by klappradla** [comment]
Closing via https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/875
