### ISSUE TITLE
Star legend disappeared from team page

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#754]
On the teams page, sponsored teams have a red star, volunteers teams have a white star. 
At the bottom of the table, the red star has vanished.
![schermafbeelding 2017-06-05 om 14 56 15](https://cloud.githubusercontent.com/assets/6314687/26784787/a13c7c28-49ff-11e7-9007-9f3af0978422.png)

**Comment by juuh42dias** [comment]
Hey, @F3PiX can assign for me? :)

**Comment by F3PiX** [comment]
Hey @juuh42dias Done! 
I think you have the access rights to assign yourself. See in the menu on the right. You can assign yourself there.

**Comment by juuh42dias** [comment]
Oh yeah, i have :+1:

**Comment by juuh42dias** [comment]
Was it supposed to show like this? The red star icon 
![rgsoc teams app 4](https://user-images.githubusercontent.com/1828204/27879354-b14da308-6197-11e7-968c-0a7e4f9e566b.png)

**Comment by F3PiX** [comment]
I think so, yes! 💯

**Comment by juuh42dias** [comment]
@F3PiX, @carpodaster what do you think? 
![rgsoc teams app 5](https://user-images.githubusercontent.com/1828204/27889196-3437d9b8-61c1-11e7-8193-e13427a117dd.png)

**Comment by carpodaster** [comment]
Looks good! As for the wording: I would name it "Sponsored team" and "Volunteering team"

**Comment by juuh42dias** [comment]
That's ok? (Let's PR?)

![rgsoc teams app 6](https://user-images.githubusercontent.com/1828204/27910639-6896f35e-622c-11e7-8c3d-f6b30be600b8.png)

**Comment by carpodaster** [comment]
> Let's PR?

Yes! 🎈

**Comment by alicetragedy** [comment]
awesomeeeee! 🎉

**Comment by carpodaster** [comment]
Done by #779
