### ISSUE TITLE
Move mailer into orga namespace

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#757]
Orga users can send email to targeted groups via `.../mailings/new` . The use of this feature is suboptimal. Especially because the mailer is not suited (yet) to play a part in more complicate workflows.

As only orga users use the email functionality, it should live in the orga namespace.

**Comment by alicetragedy** [comment]
I totally approve of this! +1

**Comment by F3PiX** [comment]
@carpodaster WDYT?

**Comment by carpodaster** [comment]
Sure, moving it makes sense!
