### ISSUE TITLE
add company to teams.app

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-teams#76]
so this is the problem:

only individuals can say "offer space", but students can't see what kind of space, where is the office, etc. So i'd say we 

-> make it possible to register as a company. We could have a profile a little bit altered than for the individuals, but provide more info on where the office is, how much space (e.g. 2-6 teams)

Technically maybe we could do it like the "teams", people can belong to. (http://2013.teams.railsgirlssummerofcode.org/teams) so that there is a "company" you can belong to. And if you click on the company you'll see more details. 
But this is just an idea how to fix this easily. 

Other ideas? Who could take this on? @carpodaster @plexus @pxlpnk @svenfuchs ?

**Comment by carpodaster** [comment]
Closed with #94
