### ISSUE TITLE
Remove 'event' views

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#760]
We have a directory with views for events, but there is no model and no controller. 

Can we remove the views? Or should we add the backend?

**Comment by alicetragedy** [comment]
+1 for removing it; it's an old thing that was put in place to have the different seasons (see [here](https://github.com/rails-girls-summer-of-code/rgsoc-teams/commit/3d2298a8f4b6945a3112a9be2ff182ad3a770383)) but was later [removed](https://github.com/rails-girls-summer-of-code/rgsoc-teams/commit/e14322e421d3ab2b540db9170894182de2120177). I can only assume the view was accidentally left there. :)
Do you want to take this?

**Comment by F3PiX** [comment]
I am collecting some beginner friendly issues. Not hard to do, but nice starters to see how our PR and code reviews work. :-)

**Comment by carpodaster** [comment]
That is most awesome, @F3PiX ! 🌷

**Comment by alicetragedy** [comment]
yeah that's perfect @F3PiX! Was going to add the `beginner-friendly` label but I saw that you beat me to it ;)

**Comment by carpodaster** [comment]
It would seem that [someone](https://github.com/carpodaster) didn't do their job properly when [deleting code](https://github.com/rails-girls-summer-of-code/rgsoc-teams/commit/e14322e421d3ab2b540db9170894182de2120177).

![](https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fstarecat.com%2Fcontent%2Fwp-content%2Fuploads%2Fwhen-you-delete-a-block-of-code-that-you-thought-was-useless-pink-panther-gif-animation.gif&f=1)
