### ISSUE TITLE
[Conferences] #1: Import a longlist of conferences

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#762]
Goal:
Orga user wants to show the students a 'long-list' of the conferences. The conferences are currently managed with a Google Doc. 
Later on, students will interact with the list, to choose their preferences, suggest other conferences etc. The scope of this issue is only uploading the file. 

- Add a file importer, so that an orga can upload a csv-file. The contents will be shown in the existing Conference table view and saved in the conferences db table. 
- Update the existing conference table structure to show the relevant fields.* 
- Write specs. 

* @mkalininait :   
- I am thinking: conference `name`, `link to` their websites, `dates`, `location`, for now. 
Maybe also: what the conference is about. Do you collect that kind of data in your Google Doc? For example , front/back end, language specific, devops. Otherwise we can add a simple 'notes' column. 
- In Google Docs, can you make a csv-export with just the columns we want to show? Or should we make it so that the not-listed columns are ignored. 
  
**UPD by @mkalininait:**
 * The entire idea: https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/751#issuecomment-308574743
 * Full list of conference user stories: https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/751#issuecomment-309138513

**Comment by mkalininait** [comment]
Hey @F3PiX Thanks for creating this issue.

The set of fields looks reasonable to me. We didn't use any 'notes' last year, and I'm not sure we will do this year. Usually conference's purpose is clear from it's name.

I think it shouldn't be a problem to export only the columns we want in the Teams app.

**Comment by F3PiX** [comment]
(@carpodaster or @klappradla or whom it may concern 🎯 ) 
I am working on an importer for the conferences. 
Is it okay if I start with an #import action in the admin/conferences_controller? I'd rather start with that simpler solution, instead of the elegant and more complicated setup like for the Exporters. WDYT?

**Comment by F3PiX** [comment]
@mkalininait Could you send me an empty csv file, please, exactly like it is when you do 'save as csv' in your Google Doc? Some example data would come in handy, or I will create them. 
You don't need to filter the columns that we need to import, the importer will filter them out.

**Comment by mkalininait** [comment]
@F3PiX Hey, I've sent you the file via Slack. Hope it's useful.

**Comment by F3PiX** [comment]
Hi @mkalininait Thanks for the file. Very useful!
It leads to the following questions.
- [ ] It looks useful for the students to see the csv's City and Country fields in the Teams app table (instead of the venue, as it is currently showing.) Okay?
- [ ] Do the students need to see the csv's Region as well? Or is that only in use for orga's.
- [ ]  I made it so that every import updates the conferences that are already in the table. That means that you can make changes in the Google Doc, and only the changes (including new conferences) will be added to the table. (Because you won't be able to edit the conferences in the table.) Okay?

And two requests, because that would speed this issue up:
- [ ] Do you _need_ the year in the `name` column in Google Docs or can the year be in a separate column (preferably named `season`)?
- [ ] Is it possible that you use 2 columns in Google Docs for the dates: `start_date` and `end_date` ? 
Thanks!

**Comment by klappradla** [comment]
For your question on controller action vs. service objects @F3PiX (I suppose the exporters are service objects - I tbh don't know them in detail): starting with the controller action is obviously the best approach. Why **start** things complex? **BUT**: if the corresponding action turns too big *(will probably happen if you parse and validate a CSV file)* I'd highly recommend to move this business logic into service objects and then just call them from your controller method. The main benefit: testability (and of course readability).

Complex business logic does not really belong into controllers, therefore probably testing ones where one violates this may turn out to be unnecessary complex and painful. Having the business logic encapsulated in easier testable service objects and then just testing the interface between the controllers and them is way easier and less error prone.

I hope that answers your question. Again, sorry for being super late to the party 😞

**Comment by F3PiX** [comment]
@mkalininait The main issue is that I need a column with a unique field to identify conferences. The title of the conference is not suitable for that. (Because you won't be allowed to change the title at all.) Do you mind to add a column to the Google Docs with a uniq code? For instance : 2017001, 2017002 . I think you should be able to let Google do the counting. The '2017' part would be the `season` when we offer the conference.  
And in that case, opposed to what I asked yesterday, you can leave the year in the conference title, and we won't need a separate column with the year.  
Would this be complicating things for you?

**Comment by mkalininait** [comment]
@F3PiX Sure, I can add a uid to the spreadsheet.

To the questions from yesterday:
1) I think it doesn't matter much how we show location: in one field or two. We started splitting country and city this year, and I can't say if it will be useful or not. But we can try.
2) I actually think that Region might be very useful for the students, because they can only look for the conferences in their region and not struggle with the entire list. Last year we made a Google Form, where all conferences were split in 6 groups with accordance to their regions. I wonder if we could make the same categories in the table/dropdowns in the Teams app.
3) Sounds okay. I guess we can add editing someday in future if we need it, right?
4) Not relevant anymore.
5) Yes, I can do.

I'll sent you the updated csv soon.

**Comment by F3PiX** [comment]
I created a preliminary PR in my fork https://github.com/TeamCheesy/rgsoc-teams/pull/49, so you can see the code.
- [ ] Question 1: I created a `Conferences::Importer`. 
After I finished it I wondered: shouldn't I instantiate the Importer?
- [ ] Question 2:  I want to add a csv file for the specs. I searched for inspiration in the Webz and in the Teams app, but I can't figure it out yet. Tips?

**Comment by F3PiX** [comment]
Shouldn't this close on :merge?

**Comment by F3PiX** [comment]
@maria 
Hey! Would you mind to change the year format in the Google Doc from `17` to `2017` ?
The date formatter now reads the date as '17 jan 0013' instead of '13/1 17'.
I can change it in the code, but that is bound to be error prone. So I'd rather rely on the formatter.

**Comment by F3PiX** [comment]
@mkalininait Hi Maria, You can use the Importer now. See note ^ about the date format in the Google Doc. Enjoy!

**Comment by mkalininait** [comment]
@F3PiX Thank you so much!!
I've tested it and found one minor issue which I already reported to you on Slack. 
Google exports csv's with the `,` separator, while in the code you suggest the `;` separator. Other than that the feature looks great to me! <3

**Comment by F3PiX** [comment]
@mkalininait
Yes, exports are comma separated, the `col_sep` option is not about what Google exports.

I can't reproduce the issue. Your .csv test file does upload here locally, and don't when I change the `col_sep`.
Can you please try to upload the _first_  test file that you sent to me? (Without changing the code/`col_sep`).  And please use the exported version, i.e. exactly what you sent to me. Not exporting the Google Doc again. For now. 👍

**Comment by F3PiX** [comment]
@mkalininait  ^ edited

**Comment by F3PiX** [comment]
I'd like to hear Carsten's opinion first, then report back to you 👍

**Comment by carpodaster** [comment]
@mkalininait @F3PiX we need to find a way how to make Google export its data in a deterministic format. If it's format A today and format B tomorrow (or same day, but different computer), we'll never find a reliable CSV col_sep setting

**Comment by F3PiX** [comment]
.csv is not a standardized format, so some apps use comma, the more modern way is to use semicolon.
Google, same as for example Numbers, don't allow to set export settings. Only import settings. 
That is why I proposed to use the .tsv, that is for all OS's, apps, computer settings and dates ;-) the same. 
Starting point was that Maria needs GoogleDocs for the conferences management, and that has limited possibilities for straightforward export.

**Comment by carpodaster** [comment]
@F3PiX I'm not so much concerned about which format we go for (I've never heard of .tsv before, but that doesn't mean anything 🙃 ). I took it from your conversation that Google Docs exported the same data with different column seperators, once with semicolon (that you used for implementing the feature) and now with comma. Or was the first one (with semicolon) not exported from Google Docs?

**Comment by F3PiX** [comment]
As I know now: Google docs always exports comma. I can't recall exactly what happened, but I probably opened it on my Mac, and then it gets saved with semicolon. That is why the .csv format is not solid enough; this can happen to any user, who wants to check the exported .csv file before uploading. 
.tsv solves all that. (As I understand it, it is the same as you get when you open a .csv file in a text editor. But with the .tsv extension).

**Comment by mkalininait** [comment]
Hey @F3PiX I tried uploading the first csv file I sent to you and I got the same error with the separator. 
It confuses me so much. From what I see and understand, Google always exports csv with the `,` separator; both files I sent to you have the `,` separator for me. I never edit/save these exported csv files in any editors, I just import what I exported from Google.
Did you use any editors to make changes in the csv files before uploading them? Maybe they saved the files with the `;` separator. I don't have any other ideas ¯\_(ツ)_/¯

cc @carpodaster

**Comment by carpodaster** [comment]
So when Google is unable to configure the export format, how do we tell it to use tabs instead of `,` ? Does `.tsv` get us anywhere?

Does Google deterministically  enclose fields (=table values) in `"` quotation marks?

**Comment by mkalininait** [comment]
@F3PiX @carpodaster As per the tsv format I'm a bit concerned about it. It's not very well-known; many applications can't export to tsv (e.g. Numbers). It will probably work for now, but I don't know if it will be convenient for future generations.

**Comment by mkalininait** [comment]
@carpodaster You can tell Google to export either to csv or tsv, but can't set options.
If there is a `,` symbol in a cell, Google Sheets will put `"` around the value.
E.g. `2017002,JSFoo 2017,"Sep 15, 2017","Sep 16, 2017",Bangalore,India,Asia Pacific,https://jsfoo.in/2017/,,,`

**Comment by F3PiX** [comment]
@carpodaster Misunderstanding: you can configure to export to .tsv, you just can set export settings for individual files. So, we tell it to use tab separators by telling to export to .tsv
AFAIK in .tsv, we don't care about the quotation marks, because it will never interprets `Aug 17, 2017` as two columns. 
I added a tsv test file to PR #798. 
How about the YOLO way: merge the PR and let Maria test in production? Nobody else is using the feature anyway. 

@mkalininait We are not exporting .tsv, we are importing it.

**Comment by mkalininait** [comment]
@F3PiX Yes, but in order to import a tsv, we need to export it from somewhere :) Now it's Google Sheets, but I don't know if it will stay this way when someone else starts working with conferences.

**Comment by mkalininait** [comment]
I still don't get the issue with csv :/ Google exports csv with the `,` separator; it also wraps values containing `,` in double quotes. The current importer processes such files perfectly, if we change the separator from `;` to `,` in the code. The only limitation is that we shouldn't open/edit/save exported files locally (in some editors) before importing them in the Teams app. But why would we do it anyway, if we can work with them in Google Sheets before exporting?
I'm sorry if I'm missing something @F3PiX @carpodaster

**Comment by carpodaster** [comment]
@mkalininait I agree. I thought the problem with Google's `,` CSV was that it doesn't quote the `,` in its field values. If it does, Ruby's [CSV lib](http://ruby-doc.org/stdlib-2.4.1/libdoc/csv/rdoc/CSV.html#method-c-new) should handle this without problems: the `:quote_char` option is set to `"` by default.

**Comment by F3PiX** [comment]
Okay, let's do it the YOLO way and test it in production :-)

**Comment by mitsuhiko** [comment]
@carpodaster it does for me:

| | A  | B | C |
| - | ---- | ---- | ---- |
| *1* | a | b,c | d |

Gets exported as

```
a,"b,c",d
```
