### ISSUE TITLE
DRY up conferences controllers

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#763]
There are currently two conferences controller, controllers/orga/conferences_controller.rb and controllers/conferences_controller.rb.
They share a few methods, like the methods for sorting the columns. 

- [x] Propose a solution to make those methods shared by the two controllers.
- [x] Make it happen 🚀

**Comment by juuh42dias** [comment]
Has any possibility for work together on this issue? Me and @branquinhoaa

**Comment by F3PiX** [comment]
The conferences controllers will change dramatically after #775 
I'd suggest to wait for that one, or be sure to check with your coaches/mentors.

**Comment by carpodaster** [comment]
I think the conference controller has undergone its heavy-weight changes now. It would be ready for refactoring.

**Comment by m-gb** [comment]
Is this project open to pull requests?

**Comment by klappradla** [comment]
Sure it is @m-gb 🤗 
Please check our [Readme](https://github.com/rails-girls-summer-of-code/rgsoc-teams) for all general information and especially our [contribution guide](https://github.com/rails-girls-summer-of-code/rgsoc-teams/blob/master/CONTRIBUTING.md) on how to get involved 📚 

**Before doing anything**, please be sure you have read and understood our [code of conduct](https://github.com/rails-girls-summer-of-code/rgsoc-teams/blob/master/CODE_OF_CONDUCT.md) 🦄

**Comment by m-gb** [comment]
Hi @klappradla, I've created PR #842 to address the issue, let e know what you think!

**Comment by klappradla** [comment]
Closed via https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/842

**Comment by F3PiX** [comment]
@m-gb 👏  🎉  🥇 
Great to see this solved, and chapeau for the way you solved it. 🙇

**Comment by F3PiX** [comment]
@m-gb Just to confirm:  I noticed that you picked one of the few issues that are labeled beginner friendly, and not rgsoc17. You are very welcome to pick issues with the rgsoc17 label as well. Just check if someone is assigned, or ask in the Issue if it is available.
