### ISSUE TITLE
[Conferences] #3: Adding a new conference

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#766]
The idea: https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/751#issuecomment-308574743
Full list of conference user stories: https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/751#issuecomment-309138513

**User Story:**
As a student, I can add a cool conference which is missing in the longlist; I can choose it as my team's primary or secondary conference then.

**Things to do:**
On the Team's page, in the Conference preferences block (see Issue #767) add a new button: "I want to suggest another conference!", which opens the form "New conference" (this form existed at one point but I'm not sure we can re-use it). The form should contain the same fields which we import with the Importer (see Issue #762), except "id".

**Comment by branquinhoaa** [comment]
@mkalininait we would like to do this, but I am almost sure that the previous issue has to be merged before I start this one. Am I right?

**Comment by branquinhoaa** [comment]
@klappradla Could you take a look too? we have changed the things you asked for

**Comment by mkalininait** [comment]
@branquinhoaa Hm.. Do you mean this PR? https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/789 This task looks independent to me. I *think* you can start working on it.

**Comment by carpodaster** [comment]
@mkalininait is this solved by #802 ?

**Comment by mkalininait** [comment]
@carpodaster jup!
