### ISSUE TITLE
[Conferences] #2: Students' preferences

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#767]
The idea: https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/751#issuecomment-308574743
Full list of conference user stories: https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/751#issuecomment-309138513

**User Story:**
As a student, I can choose my team's primary and secondary choices from the conferences longlist.

**Things to do:**
1. Move the Conference block from User to Team.
2. Who can see the Conference block:
 - Students of this team
 - Supervisors
 - Orga
3. Who can edit the Conference block:
 - Students of this team
 - Orga
4. UI:
Block title: Conference preferences
Field 1 (dropdown): Conference (primary choice)
Field 2 (dropdown): Conference (secondary choice)
5. Contents of the dropdowns: longist of conferences (see Issue #762). If would be super great, if we could visually split the list into sub-lists according to the conferences' regions (Africa, Asia Pacific, Europe, North America, South America).

**Comment by branquinhoaa** [comment]
I want to do this one, but we will need the previously story ready, right? We will need the list to choose the options. Or maybe not, we can put fake data on the two dropdown and start from there.

**Comment by mkalininait** [comment]
Hi @branquinhoaa Yes, you are right, in order to complete this task, we need to have the list of conferences finished. But I agree that it should be possible to start with the things you listed. Plus you can implement permissions: only students who belong to a team can see and edit the entire Conference block  on the team's page. Unfortunately we can't provide conference tickets to coaches.

I'm not sure I understood your question about attendances. What do you mean? Do you refer to the user stories 7 and 8? If so, then yes, we will assign conferences which are willing to provide us tickets to teams as well.
