### ISSUE TITLE
[Conferences] #6: Export of students' preferences

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#770]
The idea: https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/751#issuecomment-308574743
Full list of conference user stories: https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/751#issuecomment-309138513

**User Story:**
As an RGSoC orga, I want to export teams' conference preferences as a csv.

**Things to do:**
1. Permissions:
 - Orga
2. Format: csv
3. Available from:
 - `/orga/exports`
 - `/orga/conferences` (see the comment below)
4. Exported data (only selected teams of the current season):
 - Team name
 - Team location (optional)
 - Project name (optional)
 - Project technologies (optional) // skipping it for the moment, see https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/813#issuecomment-322189616
 - Conference primary choice
 - Conference secondary choice
 - We would like to give a LT (see #768)
 - Comments (see #768)
 - Terms accepted (YES if both checkboxes in #769 are checked)

If the optional fields are hard to retrieve, we can skip them.

**Comment by branquinhoaa** [comment]
@mkalininait this export button can be in the conference/index, like this:
![export_btn](https://user-images.githubusercontent.com/15239141/28574103-3c5f8a2a-7123-11e7-9b93-65c8dc448c06.png)

**Comment by mkalininait** [comment]
@branquinhoaa Good suggestion! And we should also add it here: `/orga/exports`

**Comment by mkalininait** [comment]
@branquinhoaa I've updated the description of this task ☝️

**Comment by branquinhoaa** [comment]
@mkalininait What about the additional info about chosen conferences #768? Will it be exported too?

**Comment by mkalininait** [comment]
@branquinhoaa Goooood point, thank you! Yes, it will. I've updated the task description.

**Comment by branquinhoaa** [comment]
Hi, @mkalininait! 
this one is done, but considering that the PR #810 change the conference preference model structure, we will need to wait for it to be merged (I get all the export data from Conference preference new model, so I need it).

There is just one field that I couldn't find: project technologies. Each team has a column named project_name, but no fields or relation with other models that have the project technology info.

Do you know how can I get this info?

**Comment by mkalininait** [comment]
Hi @branquinhoaa Great news!

Sorry, I was not accurate enough. By project technologies I meant project tags (the "Tags" column in the "Projects" table).
