### ISSUE TITLE
Redirect to user profile after submitting changes

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#773]
Problem:
When a user updates their profile, they are redirected to the home page. So they can't see their new and updated profile.

Solution:
Redirect to user profile after update.

**Comment by mkalininait** [comment]
Oh yes, this is super annoying!

**Comment by branquinhoaa** [comment]
I can solve this issue!

**Comment by carpodaster** [comment]
Done in #777
