### ISSUE TITLE
Add T-Shirt cut to User profile

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#788]
Next to "T-Shirt size" we need another dropdown "T-Shirt cut" with possible values:
 - [blank]
 - Straight cut
 - Fitted cut

**Comment by mkalininait** [comment]
@alicetragedy Are you ok with it?

**Comment by alicetragedy** [comment]
👍

**Comment by carpodaster** [comment]
Closes in #797

**Comment by mkalininait** [comment]
Tested on prod, works well. Thank you @branquinhoaa and @carpodaster !
