### ISSUE TITLE
In conferences table: handle empty url's in views

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#792]
Conference are imported by csv. If the url field in the csv file is empty, the teams app shows a useless url, like `orga/conferences`. 

Find out how the url is set in the index and show views, and show something usefull (maybe an empty field?).
Make sure that `sanitizing` imported url's stays in place, if needed.

**Comment by branquinhoaa** [comment]
:+1:  what about the other empty fields? that will be allowed?
