### ISSUE TITLE
Bug in export of current students

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#803]
There is a bug in the exporter of current students. It adds not only current students to the list, but also users, who have a student role (e.g. were students in past) and are a part of a current season team (e.g. supervise a team). 

The same issue we have when we export students of the previous RGSoC editions.

Example: a person was a student in 2015, supervised a team in 2016 and two teams in 2017. This user appears in the exports students_2016 and current_students (twice).

**Comment by carpodaster** [comment]
Thanks @mkalininait – this must an error on how the different team-related scopes are joined. If that is the case, this error will probably show up elsewhere, too. I'll look into it!

**Comment by carpodaster** [comment]
@mkalininait I pushed a fix. Could you please check if it indeed fixed the thing?

**Comment by mkalininait** [comment]
@carpodaster It did! Thank you!! 🎉
