### ISSUE TITLE
Conference preferences: NONE option

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#806]
I think we should add the 'None' option to the conference preference dropdowns, in case a team doesn't want to attend any conference. Now it's impossible to set this option after a conference has been already selected and saved.

**Comment by juuh42dias** [comment]
@mkalininait  in my PR was included `include_blank: 'Conference' ` on Dropdown of Conferences.

**Comment by klappradla** [comment]
Yes, should already be fixed with #810 , you're right @juuh42dias 🎉  _(closing this @mkalininait , feel free to reopen if it the workflow does not cover all your use cases)_

**Comment by mkalininait** [comment]
@klappradla @juuh42dias Can we please rename it to "None"? Other than that it looks good to me.

**Comment by klappradla** [comment]
Should be resolved now via #812

**Comment by mkalininait** [comment]
@klappradla YAP!
