### ISSUE TITLE
Conference preferences: adding new conference UX

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#809]
Team edit view, conference preferences

This issue derives from here: https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/802#issuecomment-318490848

It would be great to add a new conference in an in-place edit or a popup form instead of opening a new page.

**Comment by LuisaAPF** [comment]
Hi! I'd like to work on this.

**Comment by klappradla** [comment]
Yay @LuisaAPF 🎉 

I'll go ahead an assign it to you. Do you need any more information upfront?

**Comment by LuisaAPF** [comment]
Hi... I'm confused.  You can or cannot assign me this issue?

**Comment by klappradla** [comment]
I cannot for technical reasons (Github doesn't allow me to).

Sorry for causing confusion, I could have skipped the whole assign-topic 😉

**Comment by LuisaAPF** [comment]
That's odd.. Do you think this might be some configuration on my site? Can I work on it anyway?

**Comment by klappradla** [comment]
No, it's simply the way Github works. **But yeah, of course you can work on it** 💚

**Comment by mkalininait** [comment]
I've just tested this issue and noticed the following: while the "We want to suggest another conference!" button works absolutely great for students on their team's page here `/teams/NNN`, it doesn't work at all for the admins in the orga space: `/orga/teams/NNN`. I think we should either make it work or delete it from there.

**Comment by klappradla** [comment]
Closed via #867
