### ISSUE TITLE
Conferences: show for accepted teams only

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#821]
I think we should show the 'Conference' block (incl. 'Conference preferences' and 'Conference offers') on the team view/edit pages only for accepted teams. Conference settings are absolutely useless for the teams who are applying for example.

I think such solution is better than showing the 'Conference' block depending on the current season/phase. We may want to see in which conferences the teams of the previous editions participated. Moreover, some teams have their conferences after the summer of code and they may want to see them on their team pages even after the summer is officially over.

Any thoughts?

**Comment by klappradla** [comment]
Perfect @mkalininait 💚
