### ISSUE TITLE
Test ConferencePreference scopes and ConferencePreferences exporter

### ISSUE THREAD

**Issue by klappradla** [rails-girls-summer-of-code/rgsoc-teams#823]
As said in #813, it would be nice to have a dedicated test for the `current_teams` scope in the `ConferencePreference` model specs. If that is properly tested, we can rely on this contract with the conference_preference exporter. This means: we stub out this method and make the test there less heavy on the database. It is enough for us to know **that `current_teams` get's called**, the internals of this method are tested elsewhere (in the model specs).

So, try to define what the actual behavior of the exporter is, and then test this, potentially stubbing out the internals of other parts of the system that are already tested elsewhere.

**Comment by carpodaster** [comment]
Done in #839
