### ISSUE TITLE
Conferences: adding a new conf from the list of confs

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#825]
It would be convenient to have a possibility to add a new conference from the list of conferences here: `/conferences`.

Add a button "+ New Conference" on the conference page (maybe the same way as it's done for `/teams`?). The button should open the "Create a new conference" form. 

Who should see the button: 
 - orga
 - students of accepted teams

**Comment by klappradla** [comment]
Any obligations in putting this into the `conferences` milestone @mkalininait ? I think it would make sense, now that @juuh42dias and @branquinhoaa are already touching this area of the app, not to leave any "holes".

**Comment by mkalininait** [comment]
@klappradla I'm fine with anything you decide :)

**Comment by klappradla** [comment]
Closing this via #829
