### ISSUE TITLE
Can't add a new conference in UI

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/rgsoc-teams#826]
When I try to add a new conference I get Error 500 on production. 
This is how the error looks locally:

![screen shot 2017-08-21 at 14 31 21](https://user-images.githubusercontent.com/1745735/29519404-a8e606f0-867d-11e7-8e39-3111aa1e23e6.png)

**Comment by mkalininait** [comment]
Hey @branquinhoaa I assigned you to this bug, but if it's not your area of responsibility, feel free to "unassign" yourself.

**Comment by branquinhoaa** [comment]
When you tried to add the conference, are you logged as an organizer? that error is because we use team id to generate the gid, if you are logged as an orga you have no team.

**Comment by mkalininait** [comment]
@branquinhoaa Ah, I see :) Yep, I am an orga without a team. Would be great to have a possibility to add a conference in this case, too.

If it works for the students, the bug becomes of a lower priority, I guess :)

**Comment by branquinhoaa** [comment]
Yeah, I submitted a PR fixing it. In cases where the user does not have a team, I'm using her user id to generate the GID.

**Comment by mkalininait** [comment]
@branquinhoaa 
Still getting an error when trying to create a new conf as an orga :/

UPD: my test conf (https://teams.railsgirlssummerofcode.org/conferences/110) has been created with a correct gid, so maybe this error is related to the redirect.

UPD 2: I created this conf from `/conferences`, not `/orga/conferences`, which is a valid use case IMO.

**Comment by mkalininait** [comment]
@branquinhoaa Am I getting this right that some confs will have a team id in their gids, and some a user id?

**Comment by carpodaster** [comment]
@mkalininait I got the error on Sentry. It's indeed the redirect. As an orga person, what's your expected/desired redirection target? Students get redirected to their team's edit form which doesn't work for organisers.

**Comment by mkalininait** [comment]
@carpodaster In all cases I'd prefer to get redirected to the same page, where I pressed the "New conference" button (regardless of my roles):
 - team edit page
 - conferences
 - orga/conferences

**Comment by branquinhoaa** [comment]
I will fix the redirect, we had a lot of changes related to this but now I think I can work properly on this issue. Just a minute.

**Comment by branquinhoaa** [comment]
@mkalininait PR #860 I think this will work!
