### ISSUE TITLE
Add projects to nav bar 

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#834]
There is not currently a link in the nav bar to the projects index page.
Add a link to projects#index in the dropdown in `Summer of Code`, under `Conferences`

<img width="524" alt="screen shot 2017-08-22 at 14 19 18" src="https://user-images.githubusercontent.com/6314687/29565170-21842a70-8745-11e7-9e5a-77685259bc21.png">

**Comment by Benjaminpjacobs** [comment]
HI @F3PiX, I notice that no one is assigned to this issue. If it is still available I'd love to take it on. Otherwise I'm happy to help out elsewhere.

**Comment by F3PiX** [comment]
Hi @Benjaminpjacobs You are very welcome to take this on! Thanks!

**Comment by Benjaminpjacobs** [comment]
Great! I'll get started on it and hit you back soon.

**Comment by Benjaminpjacobs** [comment]
@F3PiX I added the link in the nav bar section. I had a small issue regarding ruby '2.4.2'. I changed the gemfile just to work locally, and changed it back before pushing but it appears to still have recorded the change. Please let me know if this is a problem and I can scrap this branch and do it again without changing the gemfile.

**Comment by klappradla** [comment]
Hey @Benjaminpjacobs thanx for jumping on this 🎉 

There are some "featurish" specs for the navigation in [requests/navigation_spec.rb](https://github.com/rails-girls-summer-of-code/rgsoc-teams/blob/master/spec/requests/navigation_spec.rb) - probably makes most sense to look there for some additions.

**Comment by Benjaminpjacobs** [comment]
Thanks @klappradla! I've added a couple lines to include the projects_path in the appropriate request tests.

**Comment by klappradla** [comment]
Closed via #862
