### ISSUE TITLE
Discussion: static code analysis via Rubocop / Codeclimate

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#845]
Even though we currently state in our [CONTRIBUTION.md](https://github.com/rails-girls-summer-of-code/rgsoc-teams/blob/master/CONTRIBUTING.md) that we don't automatically lint code, it has been suggested by @F3PiX that we consider adding a couple of simple rules.

This issue exists to discuss how everyone is feeling about this and what kind of static code analysis would make sense.

**Comment by carpodaster** [comment]
I always thought that rubocop rules aren't very inviting for people new to the Ruby programming language. I may be wrong on this one, but I would still like to keep the linting rules to a minimum.

Things that come to mind (opinionated):

* Indentation rules: 2 whitespaces, no extra indentation for private methods
* New hash syntax (`{ foo: :bar }` instead of `{ :foo => :bar }`)
* Aligning `case` and `when` on the same level
* Lines not longer than ~100 characters
* No trailing whitespace
* First-level `describe` should be `RSpec.describe`
* No parentheses for method definitions _without_ args, mandatory parentheses for method definitions _with_ args
* Omit parenthesis on method calls without arguments
* Omit `FactoryGirl` and just use `create :foo`
* No explicit `self`
* No explicit `return` at the end of a method

I was looking at the first half of https://github.com/bbatsov/ruby-style-guide

**Comment by F3PiX** [comment]
FYI : Why I suggested Rubocop:
As discussed on Slack, I OTOH think that rubocop rules can be very accommodating for RubyNubies.
It helps me to avoid easily avoidable mistakes like indentations. It helps me delivering the best PR I can offer. And it helps with consistency between code reviews.

**Comment by F3PiX** [comment]
Great list!!! 🎯

**Comment by klappradla** [comment]
👍 for adding a `rubocop` step to our CI pipeline with some small and basic rules like the ones you described @carpodaster 💚
From my experience, it helps to reduce some efforts on keeping code consistent and I **hugely** agree with @F3PiX, it's an awesome resource for learning some best practises _(the docs are really great)_ - I really liked it when I started out with Ruby.

I would volunteer to set everything up ☝️ and update the guides and readme accordingly one we came to a decision (I'm on a conference next week, so I may have some free time).

**Comment by klappradla** [comment]
Small note on 
> Omit FactoryGirl and just use create :foo

Ben just moved everything over to the opposite 😹 - maybe a sign we should have a automated guideline for things like this.

**Comment by carpodaster** [comment]
> Ben just moved everything over to the opposite 😹 - maybe a sign we should have a automated guideline for things like this.

Haha, oh well. Nevermind, I'm not very invested in that rule

**Comment by branquinhoaa** [comment]
I think rubocop could help us! I agree about include it in CI :dancer:

**Comment by klappradla** [comment]
FYI: I started on [this branch](https://github.com/rails-girls-summer-of-code/rgsoc-teams/tree/feature/845-discussion-static-code-analysis-via-rubocop-codeclimate) if someone's curious.
