### ISSUE TITLE
Improve client side validations on conference form

### ISSUE THREAD

**Issue by LuisaAPF** [rails-girls-summer-of-code/rgsoc-teams#851]
I noticed that the client side validations for the conference form are not stopping the submit action. I'm not sure why this is happening.

**Comment by klappradla** [comment]
Thanx for reporting @LuisaAPF 💚 

I'm afraid I don't exactly get what you're describing here - could you eventually point me to the respective code, add a screenshot or a gif? From what I remember, we do not have client-side validations anywhere (yet) 🐒

**Comment by LuisaAPF** [comment]
I meant the presence of the attribute "required"

2017-09-11 20:25 GMT+02:00 Max Mulatz <notifications@github.com>:

**Comment by klappradla** [comment]
Oh good point 👍 

Seems it was not regarded a necessary feature some years ago: see [this line](https://github.com/rails-girls-summer-of-code/rgsoc-teams/blob/master/config/initializers/simple_form.rb#L121) in our config 🙈 

I would be totally up for having it though 🎉 

Do you wanna update the configuration while you're already working on these forms anyways?

**Comment by LuisaAPF** [comment]
Sure!

2017-09-11 22:32 GMT+02:00 Max Mulatz <notifications@github.com>:

**Comment by carpodaster** [comment]
I'm not sure if we should go for client-side (ie. browser-native) validations. I have no 1st hand experience, but I think I remember a frontend dev ranting about how it doesn't always work as advertised and that one is at the browser vendor's mercy with it.

**Comment by LuisaAPF** [comment]
I think we should give it a try. It definitely improves UX and if for some reason it does not work, we still have server side validations as a backup.

**Comment by F3PiX** [comment]
+1 for client side validations (at least 'required' validations) backed up by model validations.

**Comment by carpodaster** [comment]
Alright, let's give it a bash :)
