### ISSUE TITLE
Improve UI of “Past teams” dropdown

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#874]
The [list of teams](https://teams.railsgirlssummerofcode.org/teams) currently has a dropdown that allows you to view past teams, which is great! However the styling of the dropdown could be improved with the following:
1) Text and button shouldn't be grey/greyed out, as it gives the impression that it's disabled
2) some left padding for the content of the dropdown list would be great, right now the first number of each year is completely stuck to the left dropdown border, which is a little ugly and makes it difficult to read

I've attached a screenshot below. I haven't looked into the code so I don't know if this dropdown is using bootstrap styles or not, but I think it's a fairly beginner-friendly issue for someone interested in UI and CSS.

<img width="287" alt="screen shot 2017-11-13 at 14 57 53" src="https://user-images.githubusercontent.com/3143348/32729436-11000216-c884-11e7-8237-d934c4647e41.png">

**Comment by mbrien12** [comment]
PR for this here https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/877
