### ISSUE TITLE
Limiting the number of coaches per team

### ISSUE THREAD

**Issue by nerdyvaishali** [rails-girls-summer-of-code/rgsoc-teams#882]
Often we see that participants end up adding multiple coaches and not all of them are quite involved during the program. So, as discussed in the offsite meeting how about adding a feature in teams app which puts a limitation on adding a number of coaches per team [ideally 4 I assume]?

One of the other thing, which is slightly related to this is we want to allow project maintainers to add coaches this year. So, here is my idea of how things may look like at the end:

- For the project submission form, add in the description field that project maintainers can list coaches [basically just a better decsription for description field] and once the project is accepted I think coaches/co-maintainers can sign up as coaches.
- Add feature to teams app that doesn't allow more than 4 (?) coaches per team. These 4 coaches can be either from students or from projects. 

... But as we allow 2 project choices from students, it may possible that some project will have coaches from their side and some projects will not. And in that case how does this limitation feature will work? Should we implement this as a per team, per project feature? Any other ideas to implement this in a better way?

**Comment by klappradla** [comment]
Thanx for reporting this 💡 

**Limit number of coaches**
I get the problem of coaches not being involved enough into the program, but I don't understand how limiting the number of coaches solves or at least touches this problem 🙈 
Let's say a team picks 10 coaches and only 1 of them does actual *"work"*. If we now limit the number of coaches to 4, the team may pick 4 out of the 9 non-involved once and end up with *"no coaching"* at all. Or am I getting this wrong?

I agree that it does not make sense to add more then 4 coaches, plus that any number above that is likely to decrease quality of coaching. I would also add the respective logic for that, but I don't think it solved this problem:
> participants end up adding multiple coaches and not all of them are quite involved during the program

**Project-bound-coaches**
I think with the new community page (added as part of last year's summer of code) something along the lines of what you describe is already possible. It was actually one of the motivations for building the page - to allow students who don't already have a super strong coaching team to their side to look for people who are willing to coach and have a background in the technologies involved.

The only difference: coaches have to sign up **before** someone fills out the project application.

I'll quickly outline the scenario:
1. Mentor decides to submit project
1. All the coaches she has to her side sign up as users on the Teams App, confirm their profile, set their status to `available for coaching` _(or however it is phrased, don't know it by heart)_ and cite that they are proficient in the technologies involved in the project
1. In the project description, the mentor can then add links to the Teams App userprofiles of these coaches and "propose" them as potential candidates for coaches if a team is still looking for some. _(teams should not be forced to work with these coaches)_
1. 🎉 

☝️ I tbh prefer this process to adding new inputs and logic around the application process. It's already rather complex both for the dev as well as for the user facing side.
What do you think @nerdyvaishali ?

**Comment by nerdyvaishali** [comment]
**Limit number of coaches**
Well, I agree that the idea itself doesn't actually solve our issue of the involvement from coaches but this is basically a 1st step in the direction I believe. Few other things which we have been discussing or I have been thinking to implement is as follows:

- Communicate to a applicants in a way so that they choose coaches responsibly [students-guide?]. I believed that applicants were adding so many coaches so that atleast they have some supporting coaches at the end. If we limit the numbers, they may get selective about this and select/find/add the coaches responsibly.
- Improve the communication with coaches
- Coach agreements (?)

The above mentioned way may not solve the problem completely but I was hoping that it will improve the situation and having limited number of coaches means supervisors/orga have to communicate with the less number of people. 

**Project-bound-coaches**

`I'll quickly outline the scenario:
...
`
I definitely like this process for adding new inputs and logic around the application process. It seems perfect for the coaches that comes from the projects' side [which is always good I believe]. And sure we don't need to put limitation in that case.

But how will this be implemented for students' application forms? Do you think we can implement something in the similar way? I think it may need bit more thinking as we allow applicants to add 2 project choices. 

May be a separate issue for that discussion? Wdyt @klappradla?

**Comment by F3PiX** [comment]
Hmmm I agree with @klappradla. Adding new inputs to the form or limiting coaches in code wouldn't be my first choices for solving the problem.

**Comment by klappradla** [comment]
> means supervisors/orga have to communicate with the less number of people

☝️ that's a very good point @nerdyvaishali and would already be enough reason to limit the number of coaches ✅ 

For project-bound coaches:
The "problem" with your idea is, that it breaks with some key mechanisms of the application process. Right now, coaches commit to a team **before** the team applies, is accepted and a project for them is chosen. A coach basically says:
> I'll be in if you make it and I can help you on either projects

What you want to introduce with project-bound coaches is:
> I told 10 different teams that I can coach them on this specific project but will then only coach the team that gets picked for this specific project

What ☝️  basically means is: the process of finding the actual coaches is shifted from the before the application deadline to right at the beginning of the program. You will basically have a switching of the majority of team members of all the teams that get accepted once the summer starts, which is again a) solving a complex problem and b) takes away "summer-of-code-time".

So I think even though the goal is to have a stronger coach support, implementing this feature as logic within the app could easily result in having way weaker coaching support and less inside from the orga side when rating applications to be selected.

One solution could be: how about the students not dealing with the project-based-coaches upfront at all? Once they get in contact with the mentor he or she can still point them to a group of people with most knowledge about the app.

On the topic of new issue: please not, my Github notifications are already getting out of hand 😉

**Comment by nerdyvaishali** [comment]
`I'll be in if you make it and I can help you on either projects` 

Hmm, as far as I've seen/observed, there are basically 2 problems with the above approach which basically somehow also results into teams adding so many coaches and coaches not being active during the program.

- As we offer 2 project choices but coaches are common, most of the time it is very unlikely that every coach is well-versed with the tools/technologies being used in projects teams are applying for. And because in the end team is assigned either of the project, coaches who don't have idea about tools can't really help and end up being inactive during the program.
- Another problem [if it is actually a problem? - well that is debatable :)] doesn't stop here. Lot of these people who are inactive during the program [never answered mails, texts from participants /orga /supervisors etc] uses the name of a program and claims to be part of it. And technically they are part of a program without doing any work because they are listed as a coach on our teams app. So, this doesn't actually end up as an organizational or technical problem but also sort of as a community problem too. 

`I told 10 different teams that I can coach them on this specific project but will then only coach the team that gets picked for this specific project`

This is an excellent point. And I think it will again end up having coaches who are listed as a coaches for many teams but will be basically inactive for all of them except the team working on their project. I also agree with the problem that comes from implementing this as a feature in teams app. So, it doesn't seem that implementing project-bound coaches as a feature is going to work.

` how about the students not dealing with the project-based-coaches upfront at all? Once they get in contact with the mentor he or she can still point them to a group of people with most knowledge about the app.`

The above mentioned possible solution is basically the current scenario and not the best IMO. The problem with students not dealing with the project-based-coaches upfront is that, once the team is selected, usually mentors introduces them with the community members/non-official coaches etc who helps them with the project. Apparently that also then ends up being one of the reason why coaches from students who were probably willing to help but can't be active because students don't really need them in the end. 

But well, I can't really think of any other way to involve this coaches which comes from projects [may be co-mentor?] as of now. Although I think it would be good if mentor can probably add this information somewhere [basically a text that says there are these people who would be willing to help during the project]. They don't really need to be assigned any role. Probably this can help students to probably put less effort for finding coaches for that specific project. 

Also, on a side note I was also wondering if it is possible in future to implement something in the students' application process where they can say that which coaches will help them for which projects. And once the team is selected only coaches helping them with the project they are selected will be listed as a coaches. May be tags like **'coach for project xyz'** or something in a similar way. In this case, certainly don't know how much work will require on technical part. So, feel free to say no if this last point sounds crazy. :) 

P.S. Sorry for the large bunch of text. :)

**Comment by klappradla** [comment]
> P.S. Sorry for the large bunch of text. :)

No worries, that's perfect - I at least understand everything.

So wrapping this up, my "proposal" for now would be:
- [ ] In the Teams App, limit the number of coaches per Team to e.g. 4
- [ ] Update the students's guide to reflect ☝️ 
- [ ] Update the mentors' form descriptions to tell them it's possible to suggest coaches with links to their profiles in the Teams App
- [ ] Update the students' **and** mentors guide to reflect ☝️ (e.g. coaches have to sign up upfront and set themselves to "available", etc.)

What do you think?

On your idea for tagging coaches: a reasonable idea for the future, yes. But for now I would not do this. The application process is already super timeconsuming for the students and especially the outreach to coaches one of the most difficult things, not only for countries like Egypt where there are just not enough people around, but also for people in cities that for instance don't have a local chapter of Rails Girls, Clojure Bridge, etc. to get an introduction into the community.

**Comment by nerdyvaishali** [comment]
> So wrapping this up, my "proposal" for now would be:
> ...

This sounds perfcet to me. Thanks. :+1: 

> On your idea for tagging coaches:

Ok, I think this idea also requires some more thinking. But let's keep it for the next edition [2019]. :)

**Comment by F3PiX** [comment]
Re: limit number of coaches

Hmm. I see how the Proposal can be a solution for the described use cases, and I can think of quite a few use cases where it is not. From my own experience alone:
- We had a mixed frontend/backend team, with 2 frontend coaches (at the office location) and 3  backend coaches (outside). That were not enough backend coaching contact hours. 
- During summer, the frontend coaches went on holiday; we found 2 extra remote coaches as a backup.

**Comment by klappradla** [comment]
Valid point @F3PiX! For this I would go with better wording and explanations in both the coaches' guide and the place inside the app where they set themselves to "available". I don't see how more app logic could help to prevent this scenario, it's more something to deal with during the summer inside the team itself.

Again for finding a replacement for some weeks, maybe the community page or slack could be helpful.

**Comment by carpodaster** [comment]
Sorry for chiming in at this late stage of the discussion.

**Pre-acceptance vs. post-acceptance coaches list**
I have been asked to coach teams a couple of times and it was never about the actual project. As in: I haven't worked with the project the team was applying for before. I did state, however, that I can coach in `$LIST_OF_TECHNOLOGIES` and `$OTHER_AREA_OF_EXPERTISE` and I checked that the project the applicants were interested in was actually using that tech stack. If they did, I said: hello yes, I'll gladly be your coach! Is it really happening that students were applying for two projects with drastically differing tech stacks? Say: one would be Node, the other F# ? Sure, that would probably render half of the coaches useless, no matter which of the two projects they are selected for. It seems unlikely, though.

**Listing project-bound coaches**
I think the difficulty with this "free-roaming coaches" is that we conceptually try to bring them onto the teams' rosters as real team members. I don't think that's applicable for them. Maybe "coach" isn't the right term (and it boils down to properly naming things again…) – what about "project helpers",  "free radicals" 🙃 , "project gang" 🙃 🙃  or, or … (ok, I'll stop). We / the project maintainer could state that: _hey, should you get accepted for this project, you'll get this list of house elves as part of your support group. Ain't that swell?!_

**Comment by nerdyvaishali** [comment]
Hmm, I have been also thinking about using word 'coaches' for this supporting group as well and I agree with @carpodaster 's point. But I think lot of the time project mentors wants to bring in people who can share the responsibilities. For ex, one the team I was supervising this year didn't have any coach who can help them with the project they were selected for, so in that case project mentor got 2-3 community people who were discussing the tasks and reviewing the work of participants. So, in that case I think they were doing probably sort of similar work what other teams' coaches were doing. And I don't know if any other word could like better define their work at the moment [based on the roles we have defined in the program at the moment and this will again boil down to defining the roles of these 'free-roaming coaches'] . Well, I sort of like the word free-roaming coaches though :)

**Comment by alicetragedy** [comment]
How about “project coaches” since we often refer to the mentors as “project mentors” (because there's often this confusion between mentors and coaches)? It's kind of an easy way out in a way, I know... but at least we'd have a very straight-forward name :D

**Comment by ramonh** [comment]
As discussed, I'll be adding a limit for 4 team coaches

**Comment by nerdyvaishali** [comment]
@carpodaster Yes, this can be closed now. Thanks.
