### ISSUE TITLE
Chore: Re-label rgsoc-2017 issue with rgsoc-2018

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#884]
**Q**: Why not just rename the label?
**A**: It would also change closed issues and it is nice to have an archive of past years' accomplishments

What does it entail?

From the [list of **open** issues tagged with rgsoc-2017](https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues?q=is%3Aissue+is%3Aopen+label%3Argsoc-2017)…
* remove the `rgsoc-2017` label
* add the `rgsoc-2018` one

Yes, that probably is just one GH API call, but looking at the issues count, it might be quicker to do this manually.

**Comment by F3PiX** [comment]
✅  🎈

**Comment by carpodaster** [comment]
Thanks a lot, Maud!
