### ISSUE TITLE
Migrate `team.project_name` to `team.project_id`

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#892]
Related to #816 Add team to projects page

#816 restored the association between team and the project they are working on.
There is one task left: running the [rake task](  desc '2017-08-15: Change project_name to project_id') to migrate  the old `team.project_name` to the new `team.project_id`.

I am having cold feet for my first encounter with the production database. Who wants to pair with me?

**Comment by aSquare14** [comment]
I'd like to pair !

**Comment by F3PiX** [comment]
Hi @aSquare14 Welcome here! That is great to hear!
However, in this case the call for a pair is for someone who has access to the production database :-) 
You are very welcome to take another issue!! Ping me if you have questions,  or need help finding an issue.

**Comment by klappradla** [comment]
Just came across this in the app again. It still looks like as if the transition from `project_name` to `project_id` is only _half in_ 😉 

Will have a look into migrating this over. Makes more sense to use IDs rather then the name in my opinion.

**Comment by klappradla** [comment]
The impact of this single column is actually way bigger than I expected 😹

Anyways, on the way I was also wondering: will there ever be a case of two teams of the same season assigned to the same project? If not I could add a unique index on `id season_id project_id` for Teams... 🤔
