### ISSUE TITLE
Incorrect author name for a blog post 

### ISSUE THREAD

**Issue by teambundledore** [rails-girls-summer-of-code/rgsoc-teams#901]
In the blog post feed, under the title of the article, the correct name is not displayed. I am sorry if this has already been reported, please close the issue if you feel it has already been reported. Attaching a screenshot. 
![screenshot from 2018-01-02 18-51-54](https://user-images.githubusercontent.com/29810436/34485170-1d6b4b5e-efef-11e7-8ef2-ce6776b57007.png)

**Comment by nerdyvaishali** [comment]
I think this was reported in teams app. There was an issue with one team id where instead of team's daily logs, blog posts were appeared. I remember abourt some discussion, but I don't remember if it was solved or not.

**Comment by F3PiX** [comment]
@nerdyvaishali There was another issue with the blog posts, but that was a bit different. 

I'll follow up later with a description of the problem.

**Comment by klappradla** [comment]
It's 403s for all the images. I remember we had something similar when we tried to switch to the new AWS gem...

**Comment by carpodaster** [comment]
The root problem seems to be that a team has updated the list of web resources in their profile with a direct link to their blog post on rgsoc.org. Our feed url detection does the rest:

```ruby
require 'feed'
source = Source.new(url: "https://railsgirlssummerofcode.org/blog/2017-08-07-two-geeks-and-a-summer-of-code")
feed = Feed.new(source)
feed.send(:discover_feed_url)
# => "http://railsgirlssummerofcode.org/blog.xml"
```

**Comment by nerdyvaishali** [comment]
@F3PiX I found it I guess. It is issue 853: https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/853 

The problem seems to be with the same team's team id.

**Comment by F3PiX** [comment]
@carpodaster @nerdyvaishali 

I am not sure that is the problem here. These blogposts are by the orga's. 
  
![schermafbeelding 2018-01-03 om 11 29 08](https://user-images.githubusercontent.com/6314687/34516968-5d23fe78-f079-11e7-87df-c18c6613fb15.png)

I was thinking to look into two things:
1) the :display team name method, when there is not a team 
2) the way we pull in blogposts from the orga website.

**Comment by carpodaster** [comment]
@F3PiX the blog posts are posted by Team prodyoGEEKY and as you can see on [thir profile page](https://teams.railsgirlssummerofcode.org/teams/338), they are the ones referencing a railsgirlssummerofcode.org blog post. It was not added to the Teams App by the orga team.

> 2. the way we pull in blogposts from the orga website.

Yes, that's the reason. See https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/901#issuecomment-354977203 above: the Atom/RSS URL is automatically extracted in `lib/feed.rb`. I'm currently adding a quick fix to allow a single web page as a `Source` that won't be interpreted as a feed.

**Comment by carpodaster** [comment]
I updated the offending source and removed the unwanted blog posts from our activity listing. Thanks again, @teambundledore, for reporting this! :green_heart:

**Comment by amrtanair** [comment]
Happy to help ! @carpodaster
