### ISSUE TITLE
Application form: Clarify requirement of what university courses are being taken by applicant

### ISSUE THREAD

**Issue by ramonh** [rails-girls-summer-of-code/rgsoc-teams#914]
If a university student is applying for the summer of code, they'll be required to list what courses they're taking and how many weekly hours they take up.

**Comment by ramonh** [comment]
@nerdyvaishali I had a quick question about this. I had a look at the application form and couldn't quite figure out where this best fit. I thought about this field:

![screen shot 2018-01-25 at 11 13 37](https://user-images.githubusercontent.com/656318/35383271-1199408a-01c2-11e8-9214-011b8513d993.png)

Do you reckon this should go in the label above, or the hint below? I'm more for the label above.

**Comment by nerdyvaishali** [comment]
@ramonh I think yes, it should go in label above. Please goa head with that change. Thanks

**Comment by ramonh** [comment]
Will do, thanks for getting back to me so quick, @nerdyvaishali !

**Comment by klappradla** [comment]
Closed via #918

**Comment by klappradla** [comment]
As a follow up: the one field should probably then also be hidden from the pair in the emails sent out with the application data. Can you take care of this @ramonh or are you on something else today?
I won't be able to do this until Friday I fear.

**Comment by klappradla** [comment]
Or wait. It's such a tiny fix - I can probably even do it during the left overs of my lunchbreak.

**Comment by klappradla** [comment]
Here's the PR @ramonh https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/922

**Comment by ramonh** [comment]
Oh wow, that was fast, thanks @klappradla I'll review right away
