### ISSUE TITLE
Differentiating between part-time and full-time teams

### ISSUE THREAD

**Issue by ramonh** [rails-girls-summer-of-code/rgsoc-teams#925]
Up until recently, we were differentiating between `sponsored` and `volunteer` teams.

With the introduction of part-time and full-time, as well as replacing volunteer teams with these, we'll need a mechanism to differentiate between these.

For this, we'll need:

- [x] Integrate these changes into the reviewing process
- [x] Add these to the `kinds` for `Team`s
- [x] Show and filter these in the different `index` views

**Comment by klappradla** [comment]
With #948 being merged, can this be considered done now @ramonh ?

**Comment by ramonh** [comment]
Yes! Totally, thanks @klappradla
