### ISSUE TITLE
Teams decided to not listed in the team overview should have more privacy

### ISSUE THREAD

**Issue by ArushiSinghal** [rails-girls-summer-of-code/rgsoc-teams#932]
If the team decides not to get listed in the team overview, then their team name should also not be shown in the team-member profile. This can help the members to remain more private until their selection.

**Comment by ramonh** [comment]
Thanks for pointing this out, @ArushiSinghal! Will look into this 👍

**Comment by klappradla** [comment]
Should be fixed via #938 now @ArushiSinghal - thanx again for reporting 💚
