### ISSUE TITLE
The link to the Rails-App from tthe RGSOC website

### ISSUE THREAD

**Issue by ArushiSinghal** [rails-girls-summer-of-code/rgsoc-teams#933]
In the RGSOC website (https://railsgirlssummerofcode.org/) there should be direct link/button to go to the "Rails Team APP" (https://teams.railsgirlssummerofcode.org/) to improve user experience as it's difficult for the user to find the site for "Rails Team App".

**Comment by ramonh** [comment]
Thanks for this, @ArushiSinghal! 

We already have issues related to linking to the teams app [here](https://github.com/rails-girls-summer-of-code/summer-of-code/issues/97) and [here](https://github.com/rails-girls-summer-of-code/summer-of-code/issues/439) that have more broadly to do with restructuring the website, so I'll go ahead and close this.

**Comment by ArushiSinghal** [comment]
@ramonh  Thanks for the information.
