### ISSUE TITLE
Disappearance of questions from the application form.

### ISSUE THREAD

**Issue by valaparthvi** [rails-girls-summer-of-code/rgsoc-teams#937]
**Bug** - The questions asked on [application form](https://teams.railsgirlssummerofcode.org/apply) hides as soon as we click on the answer box. It will be much more helpful if the questions stayed visible while we answer them.

**Expected Behaviour**: The questions should stay visible.

**Actual Behaviour**: 
_Before:_
![Before](https://user-images.githubusercontent.com/11015077/36162940-d2895adc-110d-11e8-9cbc-5bb62d9a8a6b.png)

_After clicking on the answer box:_
![After clicking on the answer box](https://user-images.githubusercontent.com/11015077/36162941-d2c8f728-110d-11e8-87a1-4f84aa4f900a.png)

**Comment by bajajerk** [comment]
I couldnt reproduce this bug @valaparthvi

**Comment by valaparthvi** [comment]
@bajajerk
I'm not sure which application form you tried but, this application form [here](https://teams.railsgirlssummerofcode.org/apply) is causing the bug.

**Comment by klappradla** [comment]
Hey @valaparthvi, thanx for reporting 🙏 

I tbh have a hard time reproducing this as well 🙈  Can you maybe give me some more detailed information about your setup? Which version of which browser are you using? Plus: **can you quickly try out if everything behaves normally if you disable your `Grammarly` extension**? (I only heard weird things about this extension so far 🙈 )

I cannot come up with an explanation why the labels should disappear once one clicks into the field, other then a browser extension messing with the page 😉

**Comment by valaparthvi** [comment]
Hey @klappradla, Looks like you were correct 😬. Grammarly and Firefox was a bad combination. I couldn't reproduce the bug once I disabled Grammarly. I tried to reproduce the bug on Google Chrome(I have Grammarly installed there too), couldn't reproduce it there.
Anyway, thanks to both of you.🙂 I'll close this issue then.
