### ISSUE TITLE
Deadline for RGSoC

### ISSUE THREAD

**Issue by dimi-23** [rails-girls-summer-of-code/rgsoc-teams#943]
A new feature can be added to the RGSoC TeamsApp wherein the time left/deadline for the application process of RGSoC to end can be shown, so as to remind the participants whenever they access the site. Also, other information like dates for declaration of results can be incorporated.

**Comment by dimi-23** [comment]
I would like to work on this if it seems essential to be integrated.

**Comment by carpodaster** [comment]
Hello @dimi-23, thank you for your suggestion!

This is nothing that is on our immediate schedule, but we are more than happy to accept pull requests that address this. So yes, please go ahead :smile: 

I would still like to close this issue as we strive to keep our open issues count small (we're kind of failing in that regard already :cry: ). So when you open a pull request, feel free to refer this issue even if it has been closed.

Thanks in advance for your contribution!
