### ISSUE TITLE
Move fake data sets out of the seeds 

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#953]
Goal: Distinguish between seeds and fake data
- Seeds only for data that is required to make the app run
- Fake data for dev happiness

How
- Keep the basic data as seeds 
- Create a rake task for populating the database with fake data. 
- Update Readme

**Comment by carpodaster** [comment]
@F3PiX we do not have to seed the production DB ever again so seeding it is only ever for developer happiness. Which use case are you thinking of?

**Comment by F3PiX** [comment]
@carpodaster It [came up here](https://github.com/rails-girls-summer-of-code/rgsoc-teams/pull/946#issuecomment-368801758)
Do you agree?

**Comment by carpodaster** [comment]
Oh, I missed the discussion that took place there :see_no_evil: 

I see the reasoning about `rake db:setup`, but still: we're not going to ever re-setup the prod DB. And even though the fake data goes beyond the minimal requirement to get the app running, it will remove one setup step for a new contributor and they're ready to rumble with some initial fake data that better illustrates how the app looks like.

Happy to be overruled, though :)

Cc: @klappradla

**Comment by klappradla** [comment]
💡 the extra step part is of course something I totally did not think about 🙈 

Very good point @carpodaster! So let's just close this for now and instead just make the seeds better ✌️
