### ISSUE TITLE
Send email confirmation after students submitting a proposal

### ISSUE THREAD

**Issue by stefannibrasil** [rails-girls-summer-of-code/rgsoc-teams#954]
After submitting for the Rails Girls Summer of Code we could send an email containing the team name, the time it was submitted and more useful info for the participants to keep a record of it.

**Comment by ramonh** [comment]
Hi there, thank you for reporting this!

We had this functionality this year, but found some issues with it, so we've had to temporarily disable it, as shown in PR #951 

I'll put up an issue to get the ball rolling on fixing this, so I hope you don't mind that I close this to avoid confusion.

Thank you once again! 😄

**Comment by stefannibrasil** [comment]
Hi, thanks for the info! No problem! :)
