### ISSUE TITLE
Make information about application submissions consistent across the teams app

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#958]
We have different views where we show information on applications connected to a certain project:

- the project list overview (`/projects`)
  - this lists all projects, is accessible to all users (also non-signed-in users) and shows numbers for applications in draft mode as well as applications that have been submitted for each project
- the single project view (`/projects/id-project-name`)
  - this lists a single project, is accessible to all users (also non-signed-in users) and shows the *total* of applications connected to the project, regardless of whether they've been submitted or not
- the mentor dashboard (`/mentors/applications`)
  - this is accessible to a project submitter only and it lists all *submitted applications* attached to each project of said submitter

As an organiser, I tend to look at the project list overview to see how many projects have how many applications attached to them. But as a mentor, I might (actually, I probably _would_) simply be interested in my own project, meaning I'd get those numbers from my own project page (`/projects/id-project-name`). Unfortunately, that and the mentor dashboard have “conflicting“ information, in the sense that the number of applications shown in those views is not always the same. 

There are different ways to change this:
- remove the numbers of in-progress applications on the project list overview, and only show the number of submitted applications
- move the draft vs. submitted count to the organizer project overview (`organizers/projects`) if this is a number that is more relevant for organizers than anyone else
- add rows in the table on the single project view to split the sum of applications into applications submitted vs. applications in-progress
- clarify the wording in the table on the single project view to explain that this is a TOTAL and not just submitted applications
- probably other possibilities which I'm not thinking of right now

This is not an urgent or critical issue, but something that we should definitely change in the future, depending on what we want the mentors to know and what they are interested in knowing.

**Comment by alicetragedy** [comment]
(realising now that the first two options are a no-go because we need that info there, but I'll leave them for posterity)

**Comment by klappradla** [comment]
What kind of number make most sense and are easiest to understand without knowing the internals of the program?
I thought about something like this for `/projects/id-project-name`:

| etc | etc |
|---------------------------------------------|:------:|
|Applications 1st Choice (drafts / submitted)  | 10 / 8 |
|Applications 2nd Choice (drafts / submitted) | 5 / 5  |

One would read it _(and it means)_ e.g. for the 1st choice: there were 10 drafts and out of the 10, 8 were submitted.
