### ISSUE TITLE
Application table: “Flags” column shows wrong content

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/rgsoc-teams#975]
In the application table for reviewers, the column “Hours per Week” has been split into two sections: the hours per week selected by the applicants, as well as a section that should contain the explanation for these selected hours. However, the content for that section seems to have moved over to the “Flags” column and vice versa (meaning that application flags are shown under “Hours per Week”, and reasons for hours per week are shown in the “Flags” column) — see screenshot below.

![screenshot](https://user-images.githubusercontent.com/3143348/37972491-c88441d2-31d8-11e8-8a04-b4ff14b6e68b.jpg)

**Comment by ramonh** [comment]
Oops! I just saw this 🙊  Thanks for noticing! I'll get on this.

**Comment by klappradla** [comment]
Closed via #978
