### ISSUE TITLE
ReadMe: Dependency Badge is broken

### ISSUE THREAD

**Issue by F3PiX** [rails-girls-summer-of-code/rgsoc-teams#999]
Gemnasium is closed after it was acquired by GitLab. The badge is broken too:

![schermafbeelding 2018-05-15 om 22 16 27](https://user-images.githubusercontent.com/6314687/40081370-0f261c06-588e-11e8-86f0-6541cf993084.png)

Can we live without it? Solve it?

**Comment by klappradla** [comment]
It's part of Gitlab CI now which also has an integration with Github - so we could in theory continue using it, just have to set it up differently _(also my account - which the Teams App was running on is closed now...)_. There are also some alternatives like [dependabot](https://github.com/marketplace/dependabot) and [synk](https://github.com/marketplace/snyk) but I haven't used any of them.

I'll for not just remove the badge and will look into alternatives once I have time. Free for suggestions of course as well 🤗 

It's however not super necessary to have this tool. I just personally find it handy.

**Comment by ramonh** [comment]
If I understood correctly, this is fixed, right? Can we close?

**Comment by carpodaster** [comment]
Yes, closed in #999
